# README  
This is an exmaple with FLAGS.fast = True set which means only use 1/100 data for train/eval, incase you want to run all data you might need about 300-500g memrory, so 512G mem is recommended, which exceeds TPU V3 300G mem.    
NOTICE as I used random seed due to randomness, there might be slightly diff for LB/PB score, especially LB score.  
To get my best single model score just set   
FLAGS.mode = 'infer'  
FLAGS.fast = False   
FLAGS.use_ext = True  
FLAGS.n_models = 1  
FLAGS.history_avg = False   
FLAGS.model_dir = '../input/aeroclub-recsys-2025-model1'  
To get ensemble moels score just set FLAGS.n_models = 0  
To get even better score you could set:  
FLAGS.history_avg = True   
FLAGS.model_dir = '../input/aeroclub-recsys-2025-model2'   
In case you want to run training just set FLAGS.mode = 'train' but you need to train on local machine with 512G+ mem recommened.

# Dependences
!pip install icecream  
!pip install airportsdata  
!pip install timezonefinder

In [1]:
!pip install icecream --no-index --find-links=file:///kaggle/input/icecream/ 
!pip install airportsdata --no-index --find-links=file:///kaggle/input/airportsdata/ 
!pip install timezonefinder --no-index --find-links=file:///kaggle/input/timezonefinder/ 
!pip install polars --no-index --find-links=file:///kaggle/input/polars/ 
!pip install xgboost --no-index --find-links=file:///kaggle/input/xgboost/

Looking in links: file:///kaggle/input/icecream/

Processing /kaggle/input/icecream/icecream-2.1.1-py2.py3-none-any.whl
Requirement already satisfied: pygments>=2.2.0 in /usr/local/lib/python3.10/site-packages (from icecream) (2.19.2)
Requirement already satisfied: asttokens>=2.0.1 in /usr/local/lib/python3.10/site-packages (from icecream) (3.0.0)
Processing /kaggle/input/icecream/colorama-0.4.4-py2.py3-none-any.whl
Requirement already satisfied: executing>=0.3.1 in /usr/local/lib/python3.10/site-packages (from icecream) (2.2.0)

Installing collected packages: colorama, icecream

Successfully installed colorama-0.4.4 icecream-2.1.1
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

Looking in links: file:///kaggle/input/airportsdata/

Processing /kaggle/input/airportsdata/airportsdata-20250811-py3-none-any.whl

Installing collected packages: airportsdata

Successfully installed airportsdata-20250811
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

Looking in links: file:///kaggle/input/timezonefinder/
Processing /kaggle/input/timezonefinder/timezonefinder-8.0.0-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl

Requirement already satisfied: numpy<3,>=1.23 in /usr/local/lib/python3.10/site-packages (from timezonefinder) (2.0.2)
Requirement already satisfied: flatbuffers>=25.2.10 in /usr/local/lib/python3.10/site-packages (from timezonefinder) (25.2.10)
Processing /kaggle/input/timezonefinder/h3-4.3.1-cp310-cp310-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl

Requirement already satisfied: cffi<2,>=1.15.1 in /usr/local/lib/python3.10/site-packages (from timezonefinder) (1.17.1)
Requirement already satisfied: pycparser in /usr/local/lib/python3.10/site-packages (from cffi<2,>=1.15.1->timezonefinder) (2.22)

Installing collected packages: h3, timezonefinder

Successfully installed h3-4.3.1 timezonefinder-8.0.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

Looking in links: file:///kaggle/input/polars/

Processing /kaggle/input/polars/polars-1.32.3-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl

Installing collected packages: polars

Successfully installed polars-1.32.3
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

Looking in links: file:///kaggle/input/xgboost/
Processing /kaggle/input/xgboost/xgboost-3.0.4-py3-none-manylinux_2_28_x86_64.whl

Requirement already satisfied: scipy in /usr/local/lib/python3.10/site-packages (from xgboost) (1.15.3)
Requirement already satisfied: nvidia-nccl-cu12 in /usr/local/lib/python3.10/site-packages (from xgboost) (2.21.5)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/site-packages (from xgboost) (2.0.2)

Installing collected packages: xgboost

Successfully installed xgboost-3.0.4
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

In [2]:
from icecream import ic
import sys
import os
import pickle
import numpy as np
import polars as pl
import pandas as pd
from tqdm.auto import tqdm
import json
import glob
import logging
import time
import math
import polars.selectors as cs
from collections import OrderedDict
from itertools import chain
from IPython.display import display

/usr/local/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [3]:
import airportsdata
from timezonefinder import TimezoneFinder
import pytz
from datetime import datetime
from zoneinfo import ZoneInfo

In [4]:
logger = logging.getLogger('aeroclub')
#handler = logging.StreamHandler()
from rich.logging import RichHandler
handler = RichHandler(rich_tracebacks=True)
handler.setLevel(logging.INFO)
formatter = logging.Formatter("%(asctime)s [%(levelname)s] %(message)s")
handler.setFormatter(formatter)

logger.addHandler(handler)
logger.setLevel(logging.INFO)
logger.propagate = False   # 如果不想传到 root
logger.info('start!')
ic.configureOutput(prefix='', outputFunction=logger.info)

[08/25/25 04:28:34] INFO     2025-08-25 04:28:34,706 [INFO] start!                                 ]8;id=446193;file:///tmp/ipykernel_74/1991131677.py\1991131677.py]8;;\:]8;id=310575;file:///tmp/ipykernel_74/1991131677.py#12\12]8;;\

# FLAGS

In [5]:
class FLAGS:
  root = '../input/aeroclub-recsys-2025'
  # tree model here can be 'xgb' or 'lgb' 
  # not used here as I will present 4 xgb models only which coul get similar score offline and online
  tm = 'xgb'
  # objective here can be ndcg,map,pariwse for xgb and lambdarank,xendcg for lgb
  obj = 'ndcg'
  # task could be ranking or classification
  task = 'ranking'
  # this is a bit hack as I created 5 folds and only use fold 4 wich is train on day 1-103 valid on day 104-166
  folds = 5
  fold = 4
  
  cat_method = 'count'
  # remove cast means all cat cols to be treated as numer cols 
  remove_cats = True
  reserve_cats = False
  # weather to use train/test for stats or only use train
  stats_all = True
  trees = 1000
  seed = 42
  
  # if false only use original csv existed cols as feats
  add_feats = True
  
  # weather to use history of selected data 
  # notice adding this could improve a lot on LB/PB but it is added after the game finished
  # and code copy from https://www.kaggle.com/code/mikhailgolubchik/sm-xgboost-single
  # also the feat generate using more time likely about 20-30 mintues and more memory needed about 400-500g
  history_avg = True
  # history_avg = False

  # model_dir = '../input/aeroclub-recsys-2025-model1'
  model_dir = '../input/aeroclub-recsys-2025-model2'
  
  external_dir = '../input/aeroclub-recsys-2025-external'
  out_dir = '../working'
    
  # wether use json files, not affect much
  use_ext = True
  # use_ext = False
  
  # online = False means offline train/valid mode, online = True means train on all train data for submission
  # for better LB/PB you need to set online = True, but if set online = True local valid is overly optimistic as we valid on data which also in train
  # online = False
  online = True
  
  # fast = True means for debug only which will run pipline using 0.01 ratio data and train model using 100 trees only
  # fast = True
  fast = False
  
  # n_models = 0 means not limit using all 4 models, n_models=1 means the best single model only with objective rank:ndcg
  # n_models = 1
  n_models = 0
  
  # mode = 'train' means train + eval + test this need CPU MEM more then 200-300g without his_avg
  # mode = 'infer'/'test' means only load from pretrained model and do infer online
  # mode = 'train'
  mode = 'infer'
  
  device = 'gpu'

In [6]:
def in_notebook():
  try:
    from IPython import get_ipython
    if 'IPKernelApp' not in get_ipython().config:  # pragma: no cover
      return False
  except Exception as e:
    return False
  return True

if not in_notebook():
  if len(sys.argv) > 1:
    FLAGS.fast = bool(int(sys.argv[1]))
    FLAGS.online = bool(int(sys.argv[2]))
    FLAGS.use_ext = bool(int(sys.argv[3]))
    FLAGS.history_avg = bool(int(sys.argv[4]))
  else:
    if 'fast' in os.environ:
      FLAGS.fast = bool(int(os.environ['fast']))
    if 'online' in os.environ:
      FLAGS.online = bool(int(os.environ['online']))
    if 'use_ext' in os.environ:
      FLAGS.use_ext = bool(int(os.environ['use_ext']))
    if 'history_avg' in os.environ:
      FLAGS.history_avg = bool(int(os.environ['history_avg']))

In [7]:
# online + not use_ext + not use history_avg about 250G memory needed after preprocess and neeed 360G before xgb train
FLAGS.out_dir = f'{FLAGS.out_dir}/fast{int(FLAGS.fast)}-online{int(FLAGS.online)}-use_ext{int(FLAGS.use_ext)}-history_avg{int(FLAGS.history_avg)}'
ic(FLAGS.fast)
ic(FLAGS.online)
ic(FLAGS.use_ext)
ic(FLAGS.history_avg)
ic(FLAGS.out_dir)
os.system(f'mkdir -p {FLAGS.out_dir}')

[08/25/25 04:28:35] INFO     2025-08-25 04:28:35,015 [INFO] FLAGS.fast: False                       ]8;id=782648;file:///usr/local/lib/python3.10/site-packages/icecream/icecream.py\icecream.py]8;;\:]8;id=961882;file:///usr/local/lib/python3.10/site-packages/icecream/icecream.py#185\185]8;;\

                    INFO     2025-08-25 04:28:35,026 [INFO] FLAGS.online: True                      ]8;id=433595;file:///usr/local/lib/python3.10/site-packages/icecream/icecream.py\icecream.py]8;;\:]8;id=538209;file:///usr/local/lib/python3.10/site-packages/icecream/icecream.py#185\185]8;;\

                    INFO     2025-08-25 04:28:35,034 [INFO] FLAGS.use_ext: True                     ]8;id=560270;file:///usr/local/lib/python3.10/site-packages/icecream/icecream.py\icecream.py]8;;\:]8;id=342899;file:///usr/local/lib/python3.10/site-packages/icecream/icecream.py#185\185]8;;\

                    INFO     2025-08-25 04:28:35,042 [INFO] FLAGS.history_avg: True                 ]8;id=938457;file:///usr/local/lib/python3.10/site-packages/icecream/icecream.py\icecream.py]8;;\:]8;id=383679;file:///usr/local/lib/python3.10/site-packages/icecream/icecream.py#185\185]8;;\

                    INFO     2025-08-25 04:28:35,050 [INFO] FLAGS.out_dir:                          ]8;id=811490;file:///usr/local/lib/python3.10/site-packages/icecream/icecream.py\icecream.py]8;;\:]8;id=765471;file:///usr/local/lib/python3.10/site-packages/icecream/icecream.py#185\185]8;;\
                             '../working/fast0-online1-use_ext1-history_avg1'

0

In [8]:
params_xgb = {
    'objective': 'rank:ndcg',
    'eval_metric': 'ndcg@3',
    'max_depth': 12,
    'min_child_weight': 10,
    'subsample': 0.8,
    'colsample_bytree': 0.8,
    'lambda': 100,
    'learning_rate': 0.05,
    'n_estimators': 1000,
    'seed': 42,
}

# this is what I used for lgb but it is fine to only train and ensemble xgb models
params_lgb = {
      'objective': 'lambdarank',
      'eval_metric': ['ndcg@3'],
      'ndcg_eval_at': [3], 
      'eval_at': [3],  
      'boosting_type': 'gbdt',
      'num_leaves': 63,
      'max_depth': 12,
      'min_data_in_leaf': 50,
      'feature_fraction': 0.8,
      'bagging_fraction': 0.8,
      'bagging_freq': 5,
      'lambda_l1': 0.1,
      'lambda_l2': 100,
      'learning_rate': 0.05,
      'n_estimators': 1000,
      'seed': 42,
}

In [9]:
if FLAGS.fast:
  FLAGS.trees = 100

# Predefined cols

In [10]:
COLS_TO_COMPARE = [
  "legs0_departureAt", 
  "legs0_arrivalAt", 
  "legs1_departureAt",
  "legs1_arrivalAt", 
  "legs0_segments0_flightNumber",
  "legs1_segments0_flightNumber"
]

IGNORE_COLS = [
  'Id', 
  'ranker_id',
  'selected',
  'fold',
  'uid',
  'day',
  'group_day',
  'sample_weight',
  'requestDate', #DateTime
  'bySelf', #train only 1 unique value, test half 0 half 1
  'pricingInfo_passengerCount', # nunique==1
  'legs0_departureAt',  # original time will be converted
  'legs0_arrivalAt',
  'legs1_departureAt',
  'legs1_arrivalAt',
  'legs0_segments3_baggage_count',
  'legs1_segments3_baggage_count',
  'legs0_segments3_baggage_weight',
  'legs1_segments3_baggage_weight',
  'requestReturnDate',
  'requestDepartureDate',
  'legs0_segments3_baggageAllowance_weightMeasurementType',
  'legs0_segments3_cabinClass',
  'legs1_segments3_baggageAllowance_quantity',
  'legs1_segments3_baggageAllowance_weightMeasurementType',
  'legs1_segments3_cabinClass',
  'legs1_segments3_seatsAvailable',
  'legs1_seg3_dep_offset', 
  'legs0_departureAirport',
  'legs1_departureAirport',
  'legs1_seg3_arr_offset',
  'isGlobal',
  'flight_hash',
]

rank_order = {
    'totalPrice': 'asc',
    'flight_duration_total': 'asc',
    'book_lead_time_hours': 'desc',
    'flight_duration_travel_ratio': 'asc',
    'seg_legs_all_count': 'asc',
    'avg_cabin_legs_all': 'desc',
    'avg_baggage_count_legs_all': 'desc',
    'avg_baggage_weight_legs_all': 'desc',
    'direct_price_per_km': 'asc',
}

source_cols = [
        'time_legs0_departureAt_hour',
        'time_legs1_departureAt_hour',
        'time_legs0_arrivalAt_hour',
        'time_legs1_arrivalAt_hour',
        'rank_totalPrice',
        'rank_flight_duration_total',
        'avg_cabin_legs_all',
        'avg_baggage_count_legs_all',
        'avg_baggage_weight_legs_all',
        'direct_price_per_km',
        'miniRules1_statusInfos',
        'miniRules0_statusInfos',
]

# preprocess for raw data
Parse out requestDepartureDate requestReturnDate age from json files
Though this not affect much, need 15-25 minutes

In [11]:
def load_external_data(n_files=0):
  datas = []
  json_files = glob.glob(f'{FLAGS.root}/raw/*.json')
  
  if FLAGS.fast:
    ic('fast mode just use 10 json files')
    json_files = json_files[:10]
  
  if n_files:
    json_files = json_files[:n_files]

  for json_file in tqdm(json_files, desc='json_files'):
    with open(json_file) as fh:
      data = json.load(fh)
      datas.append(data)
  
  l = []
  for data in tqdm(datas, desc='datas'):
    m = {
      'ranker_id': data['ranker_id']
    }
    routeData = data['routeData']
    m.update({
      'requestDepartureDate': routeData.get('requestDepartureDate', None),
      'requestReturnDate': routeData.get('requestReturnDate', None),
    })
    personalData = data['personalData']
    m['hasAssistant'] = personalData.get('hasAssistant', None)
    m['isGlobal'] = personalData.get('isGlobal', None)
    m['age'] = None
    if 'yearOfBirth' in personalData:
      try:
        m['age'] = 2024 - personalData['yearOfBirth']
      except Exception as e:
        m['age'] = None
    l.append(m)

  ic('to df_ext')
  df_ext = pl.DataFrame(l)
  ic(df_ext['requestReturnDate'].n_unique())
  return df_ext

In [12]:
def create_days(df):
  if df["requestDate"].dtype != pl.Datetime:
    df = df.with_columns(
        [pl.col("requestDate").str.to_datetime().alias("requestDate")])

  min_date = df["requestDate"].min()
  max_date = df["requestDate"].max()

  ic(f"Date range: {min_date} to {max_date}")

  df = df.with_columns([
      # 计算相对天数（从1开始）
      ((pl.col("requestDate") - min_date).dt.total_days() + 1
      ).cast(pl.Int32).alias("day")
  ])

  max_day = df["day"].max()
  min_day = df["day"].min()
  ic(f"Day range: {min_day} to {max_day}")

  group_day_mapping = (df.group_by("ranker_id", maintain_order=True).agg(
      pl.mean("day").alias("group_day")))

  df = df.join(group_day_mapping, on="ranker_id", how="left")
  return df

In [13]:
def get_bool_cols(df: pl.DataFrame) -> list[str]:
  return df.select(cs.boolean()).columns

def get_cat_cols(df: pl.DataFrame) -> list[str]:
  cat_cols = df.select(cs.string() | cs.categorical()).columns
  return cat_cols

def get_numer_cols(df: pl.DataFrame) -> list[str]:
  num_cols = df.select(cs.numeric() | cs.boolean()).columns
  return num_cols

def bool2int(df):
  return df.with_columns([pl.col(c).cast(pl.Int8) for c in get_bool_cols(df)])

In [14]:
def icl(lst, n=5):
  if not ic.enabled:
    return

  import inspect

  frame = inspect.currentframe().f_back
  vars_dict = frame.f_locals.items()
  # ic(vars_dict)

  var_names = [name for name, value in vars_dict if value is lst]
  var_name = var_names[0] if var_names else "unknown"

  if isinstance(lst, list):
    if len(lst) > n * 2:
      logger.info(f'{var_name} first {n}: {lst[:n]}')
      logger.info(f'{var_name} last {n}: {lst[-n:]}')
    else:
      logger.info(f'{var_name}: {lst}')
    logger.info(f'len({var_name}): {len(lst)}')
  else:
    logger.info(f'{var_name}: {lst}')

In [15]:
def timeit(info=''):

  def decorator(func):
    @functools.wraps(func)
    def wrapper(*args, **kwargs):
      logger.info(f'{info} ---------------- {func.__name__} start')
      start = time.time()
      result = func(*args, **kwargs)
      end = time.time()
      logger.info(f'{info} ################ {func.__name__} elapsed: {end - start:.4f} seconds')
      return result

    return wrapper

  return decorator

import functools
def monitor_feats(info='', out_index=0):
  def decorator(func):
    @functools.wraps(func)
    def wrapper(df, *args, **kwargs):
      original_columns = set(getattr(df, "columns", []))
      ret = func(df, *args, **kwargs)

      if isinstance(ret, (tuple, list)):
        if out_index >= len(ret):
          return ret
        new_df = ret[out_index]
      else:
        new_df = ret

      cols = getattr(new_df, "columns", None)
      if cols is None:
        return ret

      new_cols = [col for col in cols if col not in original_columns]
      logger.info(f"{info} {func.__name__} added:")
      icl(new_cols, 10)

      return ret
    return wrapper
  return decorator


def time_feats(info=''):
  def decorator(func):
    decorated_func = monitor_feats(info)(func)
    decorated_func = timeit(info)(decorated_func)
    return decorated_func
  return decorator

## Using hour not minutes

In [16]:
def dur_to_min(col: pl.Expr) -> pl.Expr:
  # extract day（ '3.05:10:00' -> 3）
  days = col.str.extract(r"^(\d+)\.", 1).cast(pl.Int64).fill_null(0) * 24 * 60

  # extract time part
  time_str = pl.when(col.str.contains(r"^\d+\.")) \
                .then(col.str.replace(r"^\d+\.", "")) \
                .otherwise(col)

  hours = time_str.str.extract(r"^(\d+):", 1).cast(pl.Int64).fill_null(0) * 60
  minutes = time_str.str.extract(r":(\d+):", 1).cast(pl.Int64).fill_null(0)

  return (days + hours + minutes).fill_null(0)


@timeit()
def durs_to_unit(df):
  exprs = []

  for leg in (0, 1):
    col = f"legs{leg}_duration"
    assert col in df.columns
    exprs.append((dur_to_min(pl.col(col)) / 60))

    for s in range(4):
      col = f"legs{leg}_segments{s}_duration"
      assert col in df.columns
      exprs.append((dur_to_min(pl.col(col)) / 60))

  df = df.with_columns(exprs)
  return df

In [17]:
def load_df(use_ext=True):
  df_train = pl.read_parquet(f'{FLAGS.root}/train.parquet').drop('__index_level_0__')    
  df_test = pl.read_parquet(f'{FLAGS.root}/test.parquet').drop('__index_level_0__')
  df_test = df_test.with_columns(pl.lit(-1, dtype=pl.Int64).alias('selected'))
  df = pl.concat([df_train, df_test], how='vertical')
  df = create_days(df)
  
  df = df.with_columns(
    pl.col('profileId').alias('uid')
  )
  
  if use_ext:
    if os.path.exists(FLAGS.external_dir):
      logger.info('load external data from pre dumped external.parquet')
      df_ext = pl.read_parquet(f'{FLAGS.external_dir}/external.parquet')
    else:
      logger.info('load external data from json files')
      df_ext = load_external_data()
    
    ic(df_ext['requestReturnDate'].n_unique())
    display(df_ext)
    df = df.join(df_ext, on='ranker_id', how='left')
    assert 'age' in df.columns

  df = df.with_columns(
    pl.col('profileId').cast(pl.Utf8)
  )
  
  cat_cols = [
    'profileId',
    'companyID', 
    'corporateTariffCode', 
    'nationality',
  ]
    
  df = df.with_columns(
    pl.col(col).cast(pl.Utf8) for col in cat_cols 
  )
 
  df = df.with_columns([
      pl.concat_str([
          pl.col(c).cast(str).fill_null("NULL") 
          for c in COLS_TO_COMPARE
      ]).alias("flight_hash")
  ])

  df = bool2int(df)
  df = durs_to_unit(df)
  return df

In [18]:
def get_valid(df):
  df_valid = df.filter(pl.col('fold') <= FLAGS.fold)
  return df_valid

def get_train(df):
  if not FLAGS.online:
    df_train = df.filter(pl.col('fold') > FLAGS.fold)
  else:
    df_train = df
    
  return df_train

def get_test(df):
  return df.filter(pl.col('selected') == -1)

def get_nontest(df):
  # Keep only non-test data
  return df.filter(pl.col('selected') != -1)

def get_train_valid(df):
  # leave out test
  df = df.filter(pl.col('selected') != -1)

  df_train = get_train(df)
  df_valid = get_valid(df)

  return df_train, df_valid

In [19]:
def set_fold(df):
  df_train = df.filter(pl.col('selected') != -1)
  df_test = df.filter(pl.col('selected') == -1)
  # Group by ranker_id and find the latest requestDate for each
  # Original code that sorts by request date
  ranker_dates = (df_train
            .group_by('ranker_id', maintain_order=True)
            .agg(pl.col('requestDate').max().alias('last_request'))
            .sort('last_request'))
  
  # Modified code that preserves original ranker_id order
  unique_rankers = ranker_dates.select('ranker_id').unique(maintain_order=True)

  # Total number of unique ranker_ids
  n_rankers = unique_rankers.height
  
  # Initialize fold column with the last fold number
  unique_rankers = unique_rankers.with_columns(pl.lit(FLAGS.folds).alias('fold'))
  
  # Calculate how many ranker_ids for each fold (10% per fold)
  fold_size = int(n_rankers * 0.1)
  ic(fold_size)
  
  # Update fold values for the newest (FLAGS.folds - 1) groups
  for i in range(FLAGS.folds):
    # Get ranker_ids for current fold (10% of data)
    start_idx = n_rankers - (i + 1) * fold_size
    end_idx = n_rankers - i * fold_size
    len_ = end_idx - start_idx
    # Get the list of ranker_ids for this fold
    fold_rankers = unique_rankers.slice(start_idx, len_).get_column('ranker_id')
    
    # Update the fold value for these ranker_ids
    unique_rankers = unique_rankers.with_columns(
      pl.when(pl.col('ranker_id').is_in(fold_rankers))
      .then(i)
      .otherwise(pl.col('fold'))
      .alias('fold')
    )
  
  # Join fold assignments back to the training data
  df_train = df_train.join(
    unique_rankers.select('ranker_id', 'fold'),
    on='ranker_id'
  )

  df_train = df_train.with_columns(pl.col('fold').cast(pl.Int32))
  ic(len(df_train))
  df_test = df_test.with_columns(pl.lit(-1, dtype=pl.Int32).alias('fold'))
  df = pl.concat([df_train, df_test], how='vertical')

  ic(df.group_by('fold').agg(pl.len()).sort('fold'))
  
  df_valid = get_valid(df_train)
  ic(df_valid['day'].min(), df_valid['day'].max(), df_valid['day'].max() - df_valid['day'].min())
  
  return df

In [20]:
def filter(df, ratio=0.01, seed=42):
  unique_ids = df.select("ranker_id").unique()
  keep_ids = np.random.default_rng(seed).choice(
    unique_ids["ranker_id"].to_list(),
    size=int(len(unique_ids) * ratio),  
    replace=False
  )
  df = df.filter(pl.col("ranker_id").is_in(keep_ids))
  return df

In [21]:
@timeit()
def smart_fillnull(df: pl.DataFrame, numer_cols: list[str], cat_cols: list[str]) -> pl.DataFrame:
  zero_flags = df.select([
      (pl.col(col) == 0).any().alias(col)
      for col in numer_cols
  ])

  fill_map = {
      col: -1 if zero_flags[col][0] else 0
      for col in numer_cols
  }

  exprs = [
      pl.col(col).fill_null(fill_map[col]) for col in numer_cols
  ] + [
      pl.col(col).fill_null("missing") for col in cat_cols
  ]

  return df.with_columns(exprs)

def promote_dtype(dtypes):  
  unique_types = set(dtypes)
  is_float = lambda dt: pl.datatypes.is_float_dtype(dt)
  is_int = lambda dt: pl.datatypes.is_integer_dtype(dt)

  # int + float
  if any(is_float(dt) for dt in unique_types) and any(is_int(dt) for dt in unique_types):
    max_float_bits = max(dt.bit_width for dt in unique_types if is_float(dt))
    return pl.Float64 if max_float_bits > 32 else pl.Float32

  # all float
  if all(is_float(dt) for dt in unique_types):
    max_bits = max(dt.bit_width for dt in unique_types)
    return pl.Float64 if max_bits > 32 else pl.Float32

  # all int
  if all(is_int(dt) for dt in unique_types):
    max_bits = max(dt.bit_width for dt in unique_types)
    return {8: pl.Int8, 16: pl.Int16, 32: pl.Int32, 64: pl.Int64}[max_bits]

  # fallback
  return list(unique_types)[0]


def align_and_concat(dfs, verbose=True):
  from builtins import set

  if not dfs:
    raise ValueError("DataFrame empty")

  common_cols = set.intersection(*(set(df.columns) for df in dfs))

  for col in sorted(common_cols):
    dtypes = [df[col].dtype for df in dfs]
    if len(set(dtypes)) > 1:
      if verbose:
        print(f"[col type not same] {col}")
        for i, dt in enumerate(dtypes):
          print(f"  DF[{i}] dtype: {dt}")
      target_type = promote_dtype(dtypes)
      if verbose:
        print(f"  → convert to: {target_type}\n")
      dfs = [df.with_columns(pl.col(col).cast(target_type)) for df in dfs]

  return pl.concat(dfs, how="vertical")

# Counting based category encoding

In [22]:
unified_features = {
    'airport_iata': [],
    'airport_city_iata': [],
    'marketingCarrier_code': [],
    'operatingCarrier_code': [],
    'aircraft_code': [],
    'flightNumber': [],
    'searchRoute': [],
    'statusInfos': [],
    # 'baggageAllowance_weightMeasurementType': [],
    # # 'baggageAllowance_quantity': [],
    # 'cabinClass': [],
}

def get_unified_cat(col):
  for key in unified_features:
    if key in col:
      return key

  return col


def get_unified_cat_columns(cat_cols):
  for col in cat_cols:
    for key in unified_features:
      if key in col:
        unified_features[key].append(col)

  return unified_features

@timeit()
def encode_unified_cats(df_train,
                        unified_features,
                        id_col=None,
                        method='count',
                        num_workers=1):
  unified_cats = OrderedDict()

  for feature_type, columns in tqdm(unified_features.items(), desc='encode_unified_cats'):
    if not columns:
      continue

    all_values = []
    for col in columns:
      if col in df_train.columns:
        all_values.extend(
            df_train.select(pl.col(col)).drop_nulls().to_series().to_list())

    if method == 'count':
      from collections import Counter
      value_counts = Counter(all_values)
      sorted_values = [val for val, count in value_counts.most_common()]
      feature_dict = {val: idx for idx, val in enumerate(sorted_values)}
    elif method == 'val':
      unique_values = sorted(list(set(all_values)))
      feature_dict = {val: idx for idx, val in enumerate(unique_values)}
    elif method == 'seq':
      seen = set()
      unique_values = []
      for val in all_values:
        if val not in seen:
          unique_values.append(val)
          seen.add(val)
      feature_dict = {val: idx for idx, val in enumerate(unique_values)}

    unified_cats[feature_type] = feature_dict

  return unified_cats

@timeit()
def encode_cat_byseq(df_train, cat_cols, id_col=None):
  cats = OrderedDict()
  if id_col:
    df_train = sort_dataframe(df_train, id_col)

  for col in tqdm(cat_cols, desc='encode_cat_byseq'):
    categories = df_train[col].unique(maintain_order=True).to_list()
    category_dict = {category: idx for idx, category in enumerate(categories)}
    cats.update({col: category_dict})

  return cats

@timeit()
def encode_cat_bycount(df_train, cat_cols, id_col=None, num_workers=1):
  cats = OrderedDict()

  def process_column(col):
    dg = df_train.group_by(col).agg(pl.len().alias('count')).sort(
        'count', descending=True)

    return {col: {val: idx for idx, val in enumerate(dg[col].to_list())}}

  results = []
  for col in tqdm(cat_cols, desc='encode_cat_bycount'):
    results.append(process_column(col))

  for result in results:
    cats.update(result)

  return cats

@timeit()
def encode_cat_byval(df_train, cat_cols, num_workers=1):
  cats = OrderedDict()

  def process_column(col):
    categories = df_train.select(
        pl.col(col)).unique().sort(col).to_series().to_list()
    return {col: {val: idx for idx, val in enumerate(categories)}}

  for cat in tqdm(cat_cols, desc='encode_cat_byval'):
    results.append(process_column(cat))

  for result in results:
    cats.update(result)

  return cats

@timeit()
def encode_cat(df_train, cat_cols, id_col=None, method='count', num_workers=1):
  cats = None
  if method == 'seq':
    cats = encode_cat_byseq(df_train, cat_cols, id_col)
  elif method == 'count':
    cats = encode_cat_bycount(df_train, cat_cols, id_col, num_workers=num_workers)
  elif method == 'val':
    # same as rank('dense') in polars
    cats = encode_cat_byval(df_train, cat_cols, num_workers=num_workers)
  else:
    raise ValueError(f"Unsupported method: {method}")
  
  return cats

@timeit()
def encode_cat_unified(df_train,
                       cat_cols,
                       id_col=None,
                       method='count',
                       num_workers=1):

  unified_features = get_unified_cat_columns(cat_cols)

  unified_cols = set()
  for columns in unified_features.values():
    unified_cols.update(columns)

  unified_cat_cols = [col for col in cat_cols if col in unified_cols]
  regular_cat_cols = [col for col in cat_cols if col not in unified_cols]

  unified_cats = encode_unified_cats(df_train, unified_features, id_col, method, num_workers)

  regular_cats = encode_cat(df_train, regular_cat_cols, id_col, method,num_workers)

  all_cats = OrderedDict()
  all_cats.update(unified_cats)
  all_cats.update(regular_cats)

  return all_cats

# Manual feats

In [23]:
@time_feats()
def add_group_feats(df: pl.DataFrame) -> pl.DataFrame:
  df = df.with_columns([
      pl.col("Id").count().over("ranker_id").alias(
          "group_size"),  
  ])
  return df

@time_feats()
def add_user_feats(df: pl.DataFrame) -> pl.DataFrame:
  df = df.with_columns(
      [pl.col("frequentFlyer").fill_null("").alias("frequentFlyer")])

  unique_combos = (
      df.select("frequentFlyer").unique().get_column("frequentFlyer").to_list())

  all_codes = sorted(
      set(chain.from_iterable(
          code.split("/") for code in unique_combos if code)))

  for code in all_codes:
    df = df.with_columns([
        pl.col("frequentFlyer").str.split("/").list.contains(code).cast(
            pl.Int8).alias(f"ff_{code}")
    ])

  df = df.with_columns(
      [pl.col("frequentFlyer").str.split("/").list.get(0).alias("ff_primary")])

  df = df.with_columns(
      [pl.col("frequentFlyer").str.count_matches("/").add(1).alias("ff_count")])

  df = df.with_columns([
      pl.when(pl.col("frequentFlyer") == "").then(0).otherwise(
          pl.col("ff_count")).alias("ff_count")
  ])

  df = df.drop("frequentFlyer")
  return df

@time_feats()
def add_searchRoute_feats(df):
  df = df.with_columns([
      pl.col("searchRoute").str.contains("/").not_().cast(
          pl.Int8).alias("isDirect")
  ])

  df = df.with_columns([
      pl.col("searchRoute").str.split("/").list.first().str.slice(
          0, 6).alias("base_searchRoute")
  ]).with_columns([
      pl.col("base_searchRoute").str.slice(0, 3).alias("p1"),
      pl.col("base_searchRoute").str.slice(3, 3).alias("p2"),
  ]).with_columns([
      pl.when(pl.col("p1") <= pl.col("p2")).then(
          pl.concat_str([pl.col("p1"), pl.col("p2")])).otherwise(
              pl.concat_str([pl.col("p2"),
                             pl.col("p1")])).alias("normed_searchRoute")
  ]).drop(["p1", "p2"])

  return df

@time_feats()
def add_segment_feats(df: pl.DataFrame) -> pl.DataFrame:
  exprs = []
  for leg in (0, 1):
    seg_cols = [
        f"legs{leg}_segments{s}_duration" for s in range(4)
        if f"legs{leg}_segments{s}_duration" in df.columns
    ]
    assert seg_cols, f"legs{leg} seg_cols is empty"
    exprs.append(
        pl.sum_horizontal([
            (pl.col(c) > 0).cast(pl.UInt8) for c in seg_cols
        ]).cast(pl.Int32).alias(f"seg_legs{leg}_count"))

  df = df.with_columns(exprs)

  df = df.with_columns([
      pl.sum_horizontal([
          pl.col(c) for c in ["seg_legs0_count", "seg_legs1_count"]
      ]).alias("seg_legs_all_count"),
  ])

  df = df.with_columns([
      pl.col("legs0_segments0_departureFrom_airport_iata").alias(
          "legs0_departureAirport"),
      pl.col("legs1_segments0_departureFrom_airport_iata").alias(
          "legs1_departureAirport"),
      pl.when(pl.col("seg_legs0_count") == 1
             ).then(pl.col("legs0_segments0_arrivalTo_airport_iata")
                   ).when(pl.col("seg_legs0_count") == 2).then(
                       pl.col("legs0_segments1_arrivalTo_airport_iata")
                   ).when(pl.col("seg_legs0_count") == 3).then(
                       pl.col("legs0_segments2_arrivalTo_airport_iata")
                   ).when(pl.col("seg_legs0_count") == 4).then(
                       pl.col("legs0_segments3_arrivalTo_airport_iata")
                   ).otherwise(None).alias("legs0_arrival_airport_iata"),

      pl.when(pl.col("seg_legs1_count") == 1
             ).then(pl.col("legs1_segments0_arrivalTo_airport_iata")
                   ).when(pl.col("seg_legs1_count") == 2).then(
                       pl.col("legs1_segments1_arrivalTo_airport_iata")
                   ).when(pl.col("seg_legs1_count") == 3).then(
                       pl.col("legs1_segments2_arrivalTo_airport_iata")
                   ).when(pl.col("seg_legs1_count") == 4).then(
                       pl.col("legs1_segments3_arrivalTo_airport_iata")
                   ).otherwise(None).alias("legs1_arrival_airport_iata"),
  ])

  return df

@time_feats()
def add_flight_duration_feats(df: pl.DataFrame) -> pl.DataFrame:
  df = df.with_columns([
      (pl.col("legs0_duration") +
       pl.col("legs1_duration")).alias("flight_duration_total"),
  ])
  df = df.with_columns([
      (pl.col("legs0_duration") /
       (pl.col("flight_duration_total") + 1e-5)).alias("legs0_duration_ratio"),
      (pl.col("legs1_duration") /
       (pl.col("flight_duration_total") + 1e-5)).alias("legs1_duration_ratio"),
  ])
  return df

def get_utc_offset(timezone_str):
  try:
    tz = ZoneInfo(timezone_str)
    now = datetime.now(tz)
    offset = now.utcoffset().total_seconds() / 3600
    return offset
  except Exception as e:
    print(f"Invalid timezone: {timezone_str} → {e}")
    return None


AIRPORTS_DB = None
TIMEZONE_FINDER = None

@timeit()
def get_airport_timezone_mapping():
  global AIRPORTS_DB, TIMEZONE_FINDER

  if AIRPORTS_DB is None:
    AIRPORTS_DB = airportsdata.load('IATA')
    TIMEZONE_FINDER = TimezoneFinder()

  airport_tz_map = {}
  for iata, info in AIRPORTS_DB.items():
    if info.get('lat') and info.get('lon'):
      timezone = TIMEZONE_FINDER.timezone_at(lat=info['lat'], lng=info['lon'])
      if timezone:
        airport_tz_map[iata] = timezone
      else:
        airport_tz_map[iata] = 'UTC'
    else:
      airport_tz_map[iata] = 'UTC'

  return airport_tz_map

def haversine_distance_expr(lat1, lon1, lat2, lon2):
  lat1_rad = lat1 * (math.pi / 180)
  lon1_rad = lon1 * (math.pi / 180)
  lat2_rad = lat2 * (math.pi / 180)
  lon2_rad = lon2 * (math.pi / 180)

  dlat = lat2_rad - lat1_rad
  dlon = lon2_rad - lon1_rad

  a = (dlat / 2
      ).sin().pow(2) + lat1_rad.cos() * lat2_rad.cos() * (dlon / 2).sin().pow(2)
  c = 2 * a.sqrt().arcsin()

  return c * 6371  

@time_feats()
def add_segment_geography_time_feats(df: pl.DataFrame) -> pl.DataFrame:
  logger.info('Adding segment geography and time features - merged version')

  global AIRPORTS_DB
  if AIRPORTS_DB is None:
    AIRPORTS_DB = airportsdata.load('IATA')

  airport_info_data = []
  for iata, info in AIRPORTS_DB.items():
    timezone_str = info.get('tz', 'UTC')
    airport_info_data.append({
        'airport_code': iata,
        # 'country': info.get('country', ''),
        # 'city': info.get('city', ''),
        'lat': info.get('lat'),
        'lon': info.get('lon'),
        # 'elevation': info.get('elevation'),
        'timezone': timezone_str,
        'utc_offset_hours': get_utc_offset(timezone_str)
    })

  airport_info_df = pl.DataFrame(airport_info_data)

  geo_time_exprs = []

  for leg in [0, 1]:
    for seg in range(4):
      dep_airport_col = f"legs{leg}_segments{seg}_departureFrom_airport_iata"
      arr_airport_col = f"legs{leg}_segments{seg}_arrivalTo_airport_iata"
      duration_col = f"legs{leg}_segments{seg}_duration"

      if all(col in df.columns
             for col in [dep_airport_col, arr_airport_col, duration_col]):
        df = df.join(
            airport_info_df.select([
                'airport_code',
                # 'country',
                # 'city',
                'lat',
                'lon',
                'utc_offset_hours'
            ]).rename({
                'airport_code': dep_airport_col,
                # 'country': f"legs{leg}_seg{seg}_dep_country",
                # 'city': f"legs{leg}_seg{seg}_dep_city",
                'lat': f"legs{leg}_seg{seg}_dep_lat",
                'lon': f"legs{leg}_seg{seg}_dep_lon",
                'utc_offset_hours': f"legs{leg}_seg{seg}_dep_offset"
            }),
            on=dep_airport_col,
            how='left'
        ).with_columns([
            pl.when((pl.col(dep_airport_col).is_not_null()) &
                    (pl.col(duration_col) > 0)).then(
                        pl.col(f"legs{leg}_seg{seg}_dep_offset").fill_null(0)
                    ).otherwise(None).alias(f"legs{leg}_seg{seg}_dep_offset"),
            # pl.when((pl.col(dep_airport_col).is_not_null()) & (pl.col(duration_col) > 0))
            #   .then(pl.col(f"legs{leg}_seg{seg}_dep_country"))
            #   .otherwise(None)
            #   .alias(f"legs{leg}_seg{seg}_dep_country"),
            # pl.when((pl.col(dep_airport_col).is_not_null()) & (pl.col(duration_col) > 0))
            #   .then(pl.col(f"legs{leg}_seg{seg}_dep_city"))
            #   .otherwise(None)
            #   .alias(f"legs{leg}_seg{seg}_dep_city"),
            pl.when((pl.col(dep_airport_col).is_not_null()) &
                    (pl.col(duration_col) > 0)).then(
                        pl.col(f"legs{leg}_seg{seg}_dep_lat")
                    ).otherwise(None).alias(f"legs{leg}_seg{seg}_dep_lat"),
            pl.when((pl.col(dep_airport_col).is_not_null()) &
                    (pl.col(duration_col) > 0)).then(
                        pl.col(f"legs{leg}_seg{seg}_dep_lon")).otherwise(
                            None).alias(f"legs{leg}_seg{seg}_dep_lon"),
        ])

        df = df.join(
            airport_info_df.select([
                'airport_code',
                # 'country',
                # 'city',
                'lat',
                'lon',
                'utc_offset_hours'
            ]).rename({
                'airport_code': arr_airport_col,
                # 'country': f"legs{leg}_seg{seg}_arr_country",
                # 'city': f"legs{leg}_seg{seg}_arr_city",
                'lat': f"legs{leg}_seg{seg}_arr_lat",
                'lon': f"legs{leg}_seg{seg}_arr_lon",
                'utc_offset_hours': f"legs{leg}_seg{seg}_arr_offset"
            }),
            on=arr_airport_col,
            how='left'
        ).with_columns([
            pl.when((pl.col(arr_airport_col).is_not_null()) &
                    (pl.col(duration_col) > 0)).then(
                        pl.col(f"legs{leg}_seg{seg}_arr_offset").fill_null(0)).
            otherwise(None).alias(f"legs{leg}_seg{seg}_arr_offset"),
            # pl.when((pl.col(arr_airport_col).is_not_null()) & (pl.col(duration_col) > 0))
            #   .then(pl.col(f"legs{leg}_seg{seg}_arr_country"))
            #   .otherwise(None)
            #   .alias(f"legs{leg}_seg{seg}_arr_country"),
            # pl.when((pl.col(arr_airport_col).is_not_null()) & (pl.col(duration_col) > 0))
            #   .then(pl.col(f"legs{leg}_seg{seg}_arr_city"))
            #   .otherwise(None)
            #   .alias(f"legs{leg}_seg{seg}_arr_city"),
            pl.when((pl.col(arr_airport_col).is_not_null()) &
                    (pl.col(duration_col) > 0)).then(
                        pl.col(f"legs{leg}_seg{seg}_arr_lat")
                    ).otherwise(None).alias(f"legs{leg}_seg{seg}_arr_lat"),
            pl.when((pl.col(arr_airport_col).is_not_null()) &
                    (pl.col(duration_col) > 0)).then(
                        pl.col(f"legs{leg}_seg{seg}_arr_lon")).otherwise(
                            None).alias(f"legs{leg}_seg{seg}_arr_lon"),
        ])

        valid_coords_condition = (
            pl.col(f"legs{leg}_seg{seg}_dep_lat").is_not_null() &
            pl.col(f"legs{leg}_seg{seg}_dep_lon").is_not_null() &
            pl.col(f"legs{leg}_seg{seg}_arr_lat").is_not_null() &
            pl.col(f"legs{leg}_seg{seg}_arr_lon").is_not_null() &
            (pl.col(duration_col) > 0))

        valid_offset_condition = (
            (pl.col(duration_col) > 0) &
            (pl.col(f"legs{leg}_seg{seg}_dep_offset").is_not_null()) &
            (pl.col(f"legs{leg}_seg{seg}_arr_offset").is_not_null()))

        geo_time_exprs.extend([
            pl.when(valid_coords_condition).then(
                haversine_distance_expr(pl.col(f"legs{leg}_seg{seg}_dep_lat"),
                                        pl.col(f"legs{leg}_seg{seg}_dep_lon"),
                                        pl.col(f"legs{leg}_seg{seg}_arr_lat"),
                                        pl.col(f"legs{leg}_seg{seg}_arr_lon"))
            ).otherwise(0.0).alias(f"legs{leg}_seg{seg}_distance_km"),

            # pl.when(valid_coords_condition)
            #   .then((pl.col(f"legs{leg}_seg{seg}_dep_country") != pl.col(f"legs{leg}_seg{seg}_arr_country")).cast(pl.Int8))
            #   .otherwise(0)
            #   .alias(f"legs{leg}_seg{seg}_is_international"),

            # pl.when(valid_coords_condition)
            #   .then((pl.col(f"legs{leg}_seg{seg}_dep_city") == pl.col(f"legs{leg}_seg{seg}_arr_city")).cast(pl.Int8))
            #   .otherwise(0)
            #   .alias(f"legs{leg}_seg{seg}_is_same_city"),
        ])

  legs_airport_pairs = [
      ('legs0_departureAirport', 'legs0_dep_country', 'legs0_dep_city',
       'legs0_dep_lat', 'legs0_dep_lon', 'legs0_dep_offset'),
      ('legs0_arrival_airport_iata', 'legs0_arr_country', 'legs0_arr_city',
       'legs0_arr_lat', 'legs0_arr_lon', 'legs0_arr_offset'),
      ('legs1_departureAirport', 'legs1_dep_country', 'legs1_dep_city',
       'legs1_dep_lat', 'legs1_dep_lon', 'legs1_dep_offset'),
      ('legs1_arrival_airport_iata', 'legs1_arr_country', 'legs1_arr_city',
       'legs1_arr_lat', 'legs1_arr_lon', 'legs1_arr_offset'),
  ]

  for airport_col, country_col, city_col, lat_col, lon_col, offset_col in legs_airport_pairs:
    if airport_col in df.columns:
      df = df.join(
          airport_info_df.select([
              'airport_code',
              # 'country',
              # 'city',
              'lat',
              'lon',
              'utc_offset_hours'
          ]).rename({
              'airport_code': airport_col,
              # 'country': country_col,
              # 'city': city_col,
              'lat': lat_col,
              'lon': lon_col,
              'utc_offset_hours': offset_col,
          }),
          on=airport_col,
          how='left').with_columns([
              pl.when(pl.col(airport_col).is_not_null()
                     ).then(pl.col(offset_col).fill_null(0)
                           ).otherwise(0).alias(offset_col)
          ])

  if geo_time_exprs:
    df = df.with_columns(geo_time_exprs)

  legs_geo_exprs = []

  if all(col in df.columns for col in
         ['legs0_dep_lat', 'legs0_dep_lon', 'legs0_arr_lat', 'legs0_arr_lon']):
    legs_geo_exprs.extend([
        pl.when(
            pl.col('legs0_dep_lat').is_not_null() &
            pl.col('legs0_dep_lon').is_not_null() &
            pl.col('legs0_arr_lat').is_not_null() &
            pl.col('legs0_arr_lon').is_not_null()).then(
                haversine_distance_expr(pl.col('legs0_dep_lat'),
                                        pl.col('legs0_dep_lon'),
                                        pl.col('legs0_arr_lat'),
                                        pl.col('legs0_arr_lon'))
            ).otherwise(None).alias('legs0_direct_distance_km'),

        # (pl.col('legs0_dep_country') != pl.col('legs0_arr_country')).cast(pl.Int8).alias('legs0_is_international'),

        # (pl.col('legs0_dep_city') == pl.col('legs0_arr_city')).cast(pl.Int8).alias('legs0_is_same_city'),
    ])

  if all(col in df.columns for col in
         ['legs1_dep_lat', 'legs1_dep_lon', 'legs1_arr_lat', 'legs1_arr_lon']):
    legs_geo_exprs.extend([
        # legs1直线距离
        pl.when(
            pl.col('legs1_dep_lat').is_not_null() &
            pl.col('legs1_dep_lon').is_not_null() &
            pl.col('legs1_arr_lat').is_not_null() &
            pl.col('legs1_arr_lon').is_not_null()).then(
                haversine_distance_expr(pl.col('legs1_dep_lat'),
                                        pl.col('legs1_dep_lon'),
                                        pl.col('legs1_arr_lat'),
                                        pl.col('legs1_arr_lon'))
            ).otherwise(0.0).alias('legs1_direct_distance_km'),

        # (pl.col('legs1_dep_country') != pl.col('legs1_arr_country')).cast(pl.Int8).alias('legs1_is_international'),

        # (pl.col('legs1_dep_city') == pl.col('legs1_arr_city')).cast(pl.Int8).alias('legs1_is_same_city'),
    ])

  if legs_geo_exprs:
    df = df.with_columns(legs_geo_exprs)

  assert 'legs0_seg0_distance_km' in df.columns

  summary_exprs = []

  for leg in [0, 1]:
    seg_distance_cols = [
        f"legs{leg}_seg{seg}_distance_km" for seg in range(4)
        if f"legs{leg}_seg{seg}_distance_km" in df.columns
    ]
    assert seg_distance_cols
    summary_exprs.append(
        pl.sum_horizontal([pl.col(col) for col in seg_distance_cols
                          ]).alias(f"legs{leg}_total_segment_distance_km"))

  df = df.with_columns(summary_exprs)
  assert 'legs0_total_segment_distance_km' in df.columns

  summary_exprs = []
  for leg in [0, 1]:
    summary_exprs.append((pl.col(f"legs{leg}_total_segment_distance_km") /
                          (pl.col(f"legs{leg}_direct_distance_km") +
                           1)).alias(f"legs{leg}_detour_ratio"))

    # seg_distance_cols = [f"legs{leg}_seg{seg}_distance_km" for seg in range(4)
    #                       if f"legs{leg}_seg{seg}_distance_km" in df.columns]

    # # if len(seg_distance_cols) > 1:
    # summary_exprs.append(
    #   pl.concat_list([pl.col(col) for col in seg_distance_cols])
    #     .list.eval(pl.element().filter(pl.element() > 0))  # 过滤掉0距离
    #     .list.std()
    #     .alias(f"legs{leg}_segment_distance_std")
    # )

    # international_cols = [f"legs{leg}_seg{seg}_is_international" for seg in range(4)]
    # # if international_cols:
    # summary_exprs.append(
    #   pl.sum_horizontal([pl.col(col) for col in international_cols])
    #     .alias(f"legs{leg}_international_segments_count")
    # )

  df = df.with_columns(summary_exprs)

  assert 'legs0_total_segment_distance_km' in df.columns

  df = df.with_columns([
      (pl.col("legs0_total_segment_distance_km") +
       pl.col("legs1_total_segment_distance_km").fill_null(0)
      ).alias("total_flight_distance_km"),
      (pl.col("legs0_direct_distance_km") +
       pl.col("legs1_direct_distance_km").fill_null(0)
      ).alias("direct_flight_distance_km"),
  ])

  df = df.with_columns([
      (pl.col("total_flight_distance_km") /
       (pl.col("flight_duration_total") + 1e-5)).alias("avg_flight_speed_kmh"),

      (pl.col("totalPrice") / (pl.col("total_flight_distance_km") + 1)
      ).alias("flight_price_per_km"),

      (pl.col("direct_flight_distance_km") /
       (pl.col("flight_duration_total") + 1e-5)).alias("avg_direct_speed_kmh"),

      (pl.col("totalPrice") / (pl.col("direct_flight_distance_km") + 1)
      ).alias("direct_price_per_km"),
  ])

  # region_exprs = []
  # country_cols = []
  # for leg in [0, 1]:
  #   country_cols.extend([f"legs{leg}_dep_country", f"legs{leg}_arr_country"])
  #   for seg in range(4):
  #     country_cols.extend([f"legs{leg}_seg{seg}_dep_country", f"legs{leg}_seg{seg}_arr_country"])

  # region_exprs.append(
  #   pl.concat_list([pl.col(col) for col in country_cols if col in df.columns])
  #     .list.drop_nulls()
  #     .list.unique()
  #     .list.len()
  #     .alias("total_unique_countries")
  # )

  # df = df.with_columns(region_exprs)

  return df

@time_feats()
def add_travel_duration_feats(df: pl.DataFrame) -> pl.DataFrame:
  utc_time_exprs = []
  time_offset_pairs = [
      ('legs0_departureAt', 'legs0_dep_offset', 'legs0_departure_utc'),
      ('legs0_arrivalAt', 'legs0_arr_offset', 'legs0_arrival_utc'),
      ('legs1_departureAt', 'legs1_dep_offset', 'legs1_departure_utc'),
      ('legs1_arrivalAt', 'legs1_arr_offset', 'legs1_arrival_utc'),
  ]

  for time_col, offset_col, utc_col in time_offset_pairs:
    if time_col in df.columns and offset_col in df.columns:
      utc_time_exprs.append(
          (pl.col(time_col).str.to_datetime() -
           pl.duration(hours=pl.col(offset_col))).alias(utc_col))

  df = df.with_columns(utc_time_exprs)

  exprs = []

  exprs.extend([
      ((pl.col("legs0_arrival_utc") -
        pl.col("legs0_departure_utc")).dt.total_seconds() /
       3600).alias("travel_duration_legs0"),
      ((pl.col("legs1_arrival_utc") -
        pl.col("legs1_departure_utc")).dt.total_seconds() /
       3600).alias("travel_duration_legs1"),
      ((pl.col("legs1_departure_utc") -
        pl.col("legs0_arrival_utc")).dt.total_seconds() / 3600
      ).alias("travel_connection_duration"),
      ((pl.col("legs1_arrival_utc") -
        pl.col("legs0_departure_utc")).dt.total_seconds() / 3600
      ).alias("travel_duration_total"),
  ])

  df = df.with_columns(exprs)

  df = df.with_columns([
      pl.max_horizontal(pl.col("travel_connection_duration"),
                        1).alias("travel_connection_duration"),
      pl.max_horizontal(pl.col("travel_duration_total"),
                        1).alias("travel_duration_total"),
  ])

  df = df.with_columns([
      (pl.col("travel_connection_duration") /
       (pl.col("travel_duration_total") +
        1e-5)).alias("travel_connection_duration_ratio"),
      (pl.col("flight_duration_total") /
       (pl.col("travel_duration_total") +
        1e-5)).alias("flight_duration_travel_ratio"),
  ])

  exprs = [
      (((pl.col("legs0_departure_utc") -
         pl.col("requestDate")).dt.total_seconds()) / 3600
      ).alias("book_lead_time_hours"),
      (((pl.col("legs1_arrival_utc") -
         pl.col("requestDate")).dt.total_seconds()) /
       3600).alias("book_after_time_hours"),
  ]
  if 'requestDepartureDate' in df.columns:
    exprs += [
        (((pl.col("legs0_departureAt").str.to_datetime() -
           pl.col("requestDepartureDate").str.to_datetime()).dt.total_seconds())
         / 3600).alias("requestDepartureDate_diff_hours"),
        (((pl.col("legs1_departureAt").str.to_datetime() -
           pl.col("requestReturnDate").str.to_datetime()).dt.total_seconds()) /
         3600).alias("requestReturnDate_diff_hours"),
    ]
  df = df.with_columns(exprs)

  df = df.with_columns(
      (pl.col('travel_duration_total') / 24).alias('travel_total_days'),
      (pl.col('book_lead_time_hours') / 24).alias("book_lead_time_days"),
      (pl.col('book_after_time_hours') / 24).alias("book_after_time_days"),
  )

  temp_cols = [
      'legs0_departure_utc',
      'legs0_arrival_utc',
      'legs1_departure_utc',
      'legs1_arrival_utc',
      'legs0_dep_tz',
      'legs0_arr_tz',
      'legs1_dep_tz',
      'legs1_arr_tz',
      'legs0_departureAirport',
      # 'legs0_segments0_departureFrom_airport_iata',
      #  'legs0_arrivalAirport',
      'legs1_departureAirport',
      # 'legs1_segments0_departureFrom_airport_iata',
      #  'legs1_arrivalAirport'
  ]
  df = df.drop([col for col in temp_cols if col in df.columns])

  return df

@time_feats()
def add_time_feats(df: pl.DataFrame) -> pl.DataFrame:
  exprs = []
  time_cols = [
      "legs0_departureAt",
      "legs0_arrivalAt",
      "legs1_departureAt",
      "legs1_arrivalAt",
      "requestDepartureDate",
      "requestReturnDate",
  ]
  # for leg in [0, 1]:
  #   for seg in range(2):
  #     time_cols.extend([
  #       f'legs{leg}_seg{seg}_departure_local',
  #       f'legs{leg}_seg{seg}_arrival_local'
  #     ])
  ic(time_cols)

  for c in time_cols:
    # assert c in df.columns
    if c not in df.columns:
      logger.info(f"Column {c} is missing from DataFrame")
      continue
    if not c.endswith('_local'):
      dt = pl.col(c).str.to_datetime()
    else:
      dt = pl.col(c)
    hour_col = dt.dt.hour()
    weekday_col = dt.dt.weekday()
    month_col = dt.dt.month()
    exprs += [
        hour_col.alias(f"time_{c}_hour"),
        weekday_col.alias(f"time_{c}_weekday"),
        month_col.alias(f"time_{c}_month"),
        (dt.dt.weekday() >= 5).cast(pl.Int32).alias(f"time_{c}_is_weekend"),
        (dt.dt.hour().is_between(6, 9) | dt.dt.hour().is_between(17, 20)
        ).cast(pl.Int32).alias(f"time_{c}_is_peak"),
        (dt.dt.hour().is_between(0, 5)
        ).cast(pl.Int32).alias(f"time_{c}_is_red_eye"),
        pl.when(hour_col.is_between(5, 8)).then(0)  
        .when(hour_col.is_between(9, 11)).then(1)  
        .when(hour_col.is_between(12, 17)).then(2)  
        .when(hour_col.is_between(18, 22)).then(3)  
        .otherwise(4)  
        .alias(f"time_{c}_period"),

        pl.when(month_col.is_in([12, 1, 2])).then(0)
        .when(month_col.is_in([3, 4, 5])).then(1)  
        .when(month_col.is_in([6, 7, 8])).then(2)  
        .otherwise(3) 
        .alias(f"time_{c}_season"),

        (weekday_col.is_between(1, 5) & hour_col.is_between(8, 18)
        ).cast(pl.Int8).alias(f"time_{c}_is_business_hours"),

        (hour_col * (2 * np.pi / 24)).sin().alias(f"time_{c}_hour_sin"),
        (hour_col * (2 * np.pi / 24)).cos().alias(f"time_{c}_hour_cos"),
        (weekday_col * (2 * np.pi / 7)).sin().alias(f"time_{c}_weekday_sin"),
        (weekday_col * (2 * np.pi / 7)).cos().alias(f"time_{c}_weekday_cos"),
        (month_col * (2 * np.pi / 12)).sin().alias(f"time_{c}_month_sin"),
        (month_col * (2 * np.pi / 12)).cos().alias(f"time_{c}_month_cos"),
    ]
  df = df.with_columns(exprs)
  time_cols = [col for col in time_cols if col in df.columns]
  df = df.drop(time_cols)

  return df

In [24]:
@time_feats()
def add_cabin_feats(df: pl.DataFrame) -> pl.DataFrame:
  exprs = []
  for leg in (0, 1):
    cabin_cols = [
        f"legs{leg}_segments{s}_cabinClass" for s in range(4)
        if f"legs{leg}_segments{s}_cabinClass" in df.columns
    ]

    assert cabin_cols, f"leg{leg} cabin_cols is empty"
    exprs.append(
        pl.mean_horizontal(
            pl.col(c) for c in cabin_cols).alias(f"avg_cabin_legs{leg}"))

  df = df.with_columns(exprs)

  df = df.with_columns([
      pl.mean_horizontal(
          pl.col(c) for c in ["avg_cabin_legs0", "avg_cabin_legs1"]).alias(
              "avg_cabin_legs_all"),
  ])

  return df

@time_feats()
def add_baggage_feats(df: pl.DataFrame) -> pl.DataFrame:
  drop_cols = []
  exprs = []
  for leg in (0, 1):
    for s in range(4):
      exprs.extend([
          # baggage_count: only keep quantity if type is 'piece'
          pl.when(
              pl.col(
                  f"legs{leg}_segments{s}_baggageAllowance_weightMeasurementType"
              ) == 0
          ).then(
              pl.col(f"legs{leg}_segments{s}_baggageAllowance_quantity").cast(
                  pl.Int8)
          ).otherwise(None).alias(f"legs{leg}_segments{s}_baggage_count"),
          # baggage_weight: only keep quantity if type is 'weight'
          pl.when(
              pl.col(
                  f"legs{leg}_segments{s}_baggageAllowance_weightMeasurementType"
              ) == 1
          ).then(
              pl.col(f"legs{leg}_segments{s}_baggageAllowance_quantity").cast(
                  pl.Float32)
          ).otherwise(None).alias(f"legs{leg}_segments{s}_baggage_weight")
      ])
      drop_cols.append(f"legs{leg}_segments{s}_baggageAllowance_quantity")
  df = df.with_columns(exprs)
  df = df.drop(drop_cols)

  exprs = []
  for leg in (0, 1):
    baggage_cols = [
        f"legs{leg}_segments{s}_baggage_count" for s in range(4)
        if f"legs{leg}_segments{s}_baggage_count" in df.columns
    ]

    assert baggage_cols, f"leg{leg} baggage_cols is empty"
    exprs.append(
        pl.mean_horizontal([pl.col(c) for c in baggage_cols
                           ]).alias(f"avg_baggage_count_legs{leg}"))

  for leg in (0, 1):
    baggage_cols = [
        f"legs{leg}_segments{s}_baggage_weight" for s in range(4)
        if f"legs{leg}_segments{s}_baggage_weight" in df.columns
    ]

    assert baggage_cols, f"leg{leg} baggage_cols is empty"
    exprs.append(
        pl.mean_horizontal([pl.col(c) for c in baggage_cols
                           ]).alias(f"avg_baggage_weight_legs{leg}"))

  df = df.with_columns(exprs)

  df = df.with_columns([
      pl.mean_horizontal(
          pl.col(c)
          for c in ["avg_baggage_count_legs0", "avg_baggage_count_legs1"
                   ]).alias("avg_baggage_count_legs_all"),
      pl.mean_horizontal(
          pl.col(c)
          for c in ["avg_baggage_weight_legs0", "avg_baggage_weight_legs1"
                   ]).alias("avg_baggage_weight_legs_all"),
  ])

  return df

@time_feats()
def add_seats_feats(df: pl.DataFrame) -> pl.DataFrame:
  exprs = []
  for leg in (0, 1):
    seats_cols = [
        f"legs{leg}_segments{s}_seatsAvailable" for s in range(4)
        if f"legs{leg}_segments{s}_seatsAvailable" in df.columns
    ]

    assert seats_cols, f"leg{leg} seats_cols is empty"
    exprs.append(
        pl.mean_horizontal(
            pl.col(c) for c in seats_cols).alias(f"avg_seats_count_legs{leg}"))

  df = df.with_columns(exprs)

  df = df.with_columns([
      pl.mean_horizontal(
          pl.col(c) for c in ["avg_seats_count_legs0", "avg_seats_count_legs1"]
      ).alias("avg_seats_count_legs_all"),
  ])
  return df

@time_feats()
def add_carrier_feats(df: pl.DataFrame) -> pl.DataFrame:
  mc_cols = []
  for leg in (0, 1):
    mc_cols.extend([
        f"legs{leg}_segments{s}_marketingCarrier_code" for s in range(4)
        if f"legs{leg}_segments{s}_marketingCarrier_code" in df.columns
    ])

    assert mc_cols, f"leg{leg} mc_cols is empty"

  df = df.with_columns(
    pl.struct(mc_cols)
      .map_elements(lambda s: len(set(v for v in s.values() if v is not None)), return_dtype=pl.UInt8)
      .alias("num_unique_carriers")
  )

  df = df.with_columns([
      (pl.col('num_unique_carriers') / pl.max_horizontal(
          pl.col('seg_legs_all_count'), 1)).alias('carrier_diversity_ratio'),
  ])

  return df

In [25]:
@time_feats()
def add_ranking_feats(df, group_col, suffix=''):
  exprs = []
  for col, order in rank_order.items():
    if col in df.columns:
      exprs.append(
          pl.col(col).rank(method='average', descending=(
              order == 'desc')).over(group_col).alias(f'rank_{col}{suffix}'))
    else:
      logger.warning(f"Column {col} not found in DataFrame, skipping ranking.")
  df = df.with_columns(exprs)

  return df

@time_feats()
def add_flighthash_feats(df):
  df = (df.with_columns([
      pl.len().over(["ranker_id", "flight_hash"]).alias("flight_hash_count"),
  ]).with_columns([
      (pl.col("flight_hash_count") /
       pl.col("group_size")).alias("flight_hash_ratio"),
      pl.col("flight_hash_count").rank(
          "dense",
          descending=True).over("ranker_id").alias("rank_flight_hash_count"),
  ]))
  return df

#Notice not consider label/selected and df is (train and test) combined
@time_feats()
def add_stats_feats(df, group_col='profileId'):
  exprs = []
  for col in rank_order.keys():
    if col in df.columns:
      exprs.extend([
        pl.col(col).mean().over(group_col).alias(f"avg_{col}_{group_col}_stats"),
        pl.col(col).min().over(group_col).alias(f"min_{col}_{group_col}_stats"),
        pl.col(col).max().over(group_col).alias(f"max_{col}_{group_col}_stats"),
        pl.col(col).std().over(group_col).alias(f"std_{col}_{group_col}_stats"),
        pl.col(col).median().over(group_col).alias(f"median_{col}_{group_col}_stats"),
      ])
  df = df.with_columns(exprs)
  exprs = []
  for col in rank_order.keys():
    if col in df.columns:
      exprs.extend([
        ((pl.col(col) - pl.col(f"avg_{col}_{group_col}_stats")) / (pl.col(f"std_{col}_{group_col}_stats") + 1e-5)).alias(f"{col}_zscore_{group_col}_stats"),
        ((pl.col(col) - pl.col(f"min_{col}_{group_col}_stats")) / (pl.col(f"max_{col}_{group_col}_stats") - pl.col(f"min_{col}_{group_col}_stats") + 1e-5)).alias(f"{col}_minmax_{group_col}_stats"),
        (pl.col(col) / (pl.col(f"avg_{col}_{group_col}_stats") + 1e-5)).alias(f"{col}_{group_col}_stats_ratio"),
      ])

  df = df.with_columns(exprs)
  return df

# Make history avg feat 
https://www.kaggle.com/code/mikhailgolubchik/sm-xgboost-single
Notice this is added after contest ends, it could boost online LB/PB +0.008

In [26]:
@time_feats()
def make_history_avg(df, source_cols, group_col, suffix):
  ori_cols = [col for col in df.columns]
  selected_df = df.filter(
      pl.col("selected") == 1).select(["ranker_id", "requestDate", group_col] +
                                      source_cols)

  ranker_to_profile = dict(
      zip(selected_df["ranker_id"].to_list(), selected_df[group_col].to_list()))

  ranker_to_timestamp = dict(
      zip(selected_df["ranker_id"].to_list(),
          selected_df["requestDate"].to_list()))

  history_df = selected_df.select(["ranker_id", "requestDate", group_col] +
                                  source_cols)

  all_stats_dict = {}  # ranker_id -> {col_mean: val, col_std: val}

  unique_ranker_ids = df["ranker_id"].unique().to_list()

  for current_ranker_id in tqdm(unique_ranker_ids,
                                desc="Обработка ranker_id",
                                mininterval=10.0):
    current_profile_id = ranker_to_profile.get(current_ranker_id)

    current_timestamp = ranker_to_timestamp.get(current_ranker_id)

    profile_history = history_df.filter(
        (pl.col(group_col) == current_profile_id) &
        (pl.col("ranker_id") != current_ranker_id) &
        (pl.col("requestDate") < current_timestamp))

    agg_result = profile_history.select([
        *[
            pl.col(col).mean().alias(f"{col}{suffix}_mean")
            for col in source_cols
        ],
        *[pl.col(col).std().alias(f"{col}{suffix}_std") for col in source_cols],
        *[
            pl.col(col).count().alias(f"{col}{suffix}_count")
            for col in source_cols
        ],  
        *[
            pl.col(col).median().alias(f"{col}{suffix}_median")
            for col in source_cols
        ],
        *[
            pl.col(col).quantile(0.25).alias(f"{col}{suffix}_q25")
            for col in source_cols
        ],
        *[
            pl.col(col).quantile(0.75).alias(f"{col}{suffix}_q75")
            for col in source_cols
        ]
    ])

    if agg_result.height > 0:
      row = agg_result.row(0)
      n_cols = len(source_cols)
      all_stats_dict[current_ranker_id] = {
          **{
              f"{col}{suffix}_mean": row[i] for i, col in enumerate(source_cols)
          },
          **{
              f"{col}{suffix}_std": row[i + n_cols] for i, col in enumerate(source_cols)
          },
          **{
              f"{col}{suffix}_count": row[i + 2 * n_cols] for i, col in enumerate(source_cols)
          },
          **{
              f"{col}{suffix}_median": row[i + 3 * n_cols] for i, col in enumerate(source_cols)
          },
          **{
              f"{col}{suffix}_q25": row[i + 4 * n_cols] for i, col in enumerate(source_cols)
          },
          **{
              f"{col}{suffix}_q75": row[i + 5 * n_cols] for i, col in enumerate(source_cols)
          },
      }

  update_data = []
  for ranker_id, stats in all_stats_dict.items():
    row = {"ranker_id": ranker_id, **stats}
    update_data.append(row)

  schema = {"ranker_id": pl.Utf8} 
  for col in source_cols:
    schema[f"{col}{suffix}_mean"] = pl.Float32
    schema[f"{col}{suffix}_std"] = pl.Float32
    schema[f"{col}{suffix}_count"] = pl.Int32
    schema[f"{col}{suffix}_median"] = pl.Float32
    schema[f"{col}{suffix}_q25"] = pl.Float32
    schema[f"{col}{suffix}_q75"] = pl.Float32

  update_df = pl.DataFrame(update_data, schema=schema)

  df = df.join(update_df, on="ranker_id", how="left")

  agg_exprs = []
  for col in source_cols:
    agg_exprs.extend([
      pl.col(col).mean().alias(f"{col}{suffix}_mean"),
      pl.col(col).std().alias(f"{col}{suffix}_std"),
      pl.col(col).count().alias(f"{col}{suffix}_count"),
      pl.col(col).median().alias(f"{col}{suffix}_median"),
      pl.col(col).quantile(0.25).alias(f"{col}{suffix}_q25"),
      pl.col(col).quantile(0.75).alias(f"{col}{suffix}_q75")
    ])

  df_stats = (df.filter(
      pl.col("selected") == 1).group_by(group_col).agg(agg_exprs))

  stats_cols = [c for c in df.columns if c.endswith((
    "_mean", "_std", "_median", "_q25", "_q75")) and c not in ori_cols]
  count_cols = [c for c in df.columns if c.endswith("_count") and c not in ori_cols]

  df = df.with_columns([
    pl.col(stats_cols).cast(pl.Float32),
    pl.col(count_cols).cast(pl.Int32)
  ])
  df_stats = df_stats.with_columns([
    pl.col(stats_cols).cast(pl.Float32),
    pl.col(count_cols).cast(pl.Int32)
  ])

  return df, df_stats

In [27]:
@time_feats()
def gen_feats(df):
  df = add_group_feats(df)
  df = add_user_feats(df)
  df = add_searchRoute_feats(df)
  df = add_segment_feats(df)
  df = add_flight_duration_feats(df)
  df = add_segment_geography_time_feats(df)
  df = add_travel_duration_feats(df)
  df = add_time_feats(df)
  
  temp_geo_cols = []
  for leg in [0, 1]:
    temp_geo_cols.extend([
        f'legs{leg}_dep_lat', f'legs{leg}_dep_lon', f'legs{leg}_arr_lat',
        f'legs{leg}_arr_lon'
    ])
    for seg in range(4):
      temp_geo_cols.extend([
          f"legs{leg}_seg{seg}_dep_lat",
          f"legs{leg}_seg{seg}_dep_lon",
          f"legs{leg}_seg{seg}_arr_lat",
          f"legs{leg}_seg{seg}_arr_lon",

      ])

  drop_cols = [col for col in temp_geo_cols if col in df.columns]
  ic(drop_cols)
  df = df.drop(drop_cols)
  
  df = add_cabin_feats(df)
  df = add_baggage_feats(df)
  df = add_seats_feats(df)
  df = add_carrier_feats(df)
  
  df = add_flighthash_feats(df)
  df = add_ranking_feats(df, 'ranker_id')
  df = add_ranking_feats(df, ['ranker_id', 'flight_hash'], '_in_hash_group')
  
  df = add_stats_feats(df, 'uid')
  df = add_stats_feats(df, 'companyID')
  
  drop_cols = [
      col for col in df.columns if any(['_utc' in col, '_local' in col])
  ]
  ic(drop_cols)
  df = df.drop(drop_cols)
  
  if FLAGS.history_avg:
    test = get_test(df)
    
    df = get_nontest(df)
    train = get_train(df)
    
    # if not training using all train data, valid data need to merge stats similar as test
    if not FLAGS.online:
      valid = get_valid(df)
      test = pl.concat([valid, test], how='vertical')

    train, df_stats_pr = make_history_avg(train,
                                       source_cols=source_cols,
                                       group_col="uid",
                                       suffix='_uid')
    test = test.join(df_stats_pr, on='uid', how='left')
    
    train, df_stats_co = make_history_avg(train,
                                       source_cols=source_cols,
                                       group_col="companyID",
                                       suffix='_company')
    test = test.join(df_stats_co, on='companyID', how='left')

    # test = test.select(train.columns)
    
    df = align_and_concat([train, test])
  return df

In [28]:
def preprocess(add_feats=True):
  df = load_df(use_ext=FLAGS.use_ext)
  df = set_fold(df)
  if FLAGS.fast:
    df_train = get_nontest(df)
    df_test = get_test(df)
    df_train = filter(df_train, 0.01, FLAGS.seed)
    df = pl.concat([df_train, df_test], how='vertical')
       
  if add_feats:
    df = gen_feats(df)
  
  numer_cols = get_numer_cols(df)
  cat_cols = get_cat_cols(df)
  feat_cols = numer_cols + cat_cols
  
  df = smart_fillnull(df, numer_cols, cat_cols)
  
  ignore_cols = [col for col in IGNORE_COLS]
  cat_cols = [col for col in cat_cols if col not in ignore_cols]
  numer_cols = [col for col in numer_cols if col not in ignore_cols]
  feat_cols = [col for col in feat_cols if col not in ignore_cols]
  
  train = get_train(df) if not FLAGS.stats_all else df
  cats = encode_cat_unified(train, cat_cols, method=FLAGS.cat_method, num_workers=1)
  ic(cats.keys())
  df = df.with_columns([
      pl.col(col).replace_strict(cats[get_unified_cat(col)], default=-1) for col in cat_cols
  ])
  
  if FLAGS.remove_cats:  
    if not FLAGS.reserve_cats:
      numer_cols += cat_cols
      cat_cols = []
    else:
      reserve_cats = ['profileId', 'companyID', 'corporateTariffCode', 'nationality', 'companyCode']
      numer_cols += [col for col in cat_cols if col not in reserve_cats]
      cat_cols = [col for col in cat_cols if col in reserve_cats] 
   
  icl(numer_cols, 10) 
  icl(cat_cols, 10) 
  cols_dict = {
        'numer': numer_cols,  
        'cat': cat_cols,    
        'feat': feat_cols,           
  }  
  return df, cols_dict

In [29]:
df, cols_dict = preprocess(add_feats=FLAGS.add_feats)
df

[08/25/25 04:28:40] INFO     2025-08-25 04:28:40,867 [INFO] f"Date range: {min_date} to             ]8;id=425080;file:///usr/local/lib/python3.10/site-packages/icecream/icecream.py\icecream.py]8;;\:]8;id=804722;file:///usr/local/lib/python3.10/site-packages/icecream/icecream.py#185\185]8;;\
                             {max_date}": 'Date range: 2024-05-17 03:03:08 to 2024-12-31 18:54:00'

[08/25/25 04:28:44] INFO     2025-08-25 04:28:44,583 [INFO] f"Day range: {min_day} to {max_day}":   ]8;id=658358;file:///usr/local/lib/python3.10/site-packages/icecream/icecream.py\icecream.py]8;;\:]8;id=441998;file:///usr/local/lib/python3.10/site-packages/icecream/icecream.py#185\185]8;;\
                             'Day range: 1 to 229'

[08/25/25 04:28:45] INFO     2025-08-25 04:28:45,078 [INFO] load external data from pre dumped      ]8;id=815400;file:///tmp/ipykernel_74/692935989.py\692935989.py]8;;\:]8;id=190231;file:///tmp/ipykernel_74/692935989.py#14\14]8;;\
                             external.parquet

                    INFO     2025-08-25 04:28:45,435 [INFO] df_ext['requestReturnDate'].n_unique(): ]8;id=987856;file:///usr/local/lib/python3.10/site-packages/icecream/icecream.py\icecream.py]8;;\:]8;id=863282;file:///usr/local/lib/python3.10/site-packages/icecream/icecream.py#185\185]8;;\
                             3351

shape: (150_770, 6)
┌──────────────────────┬─────────────────────┬─────────────────────┬──────────────┬──────────┬─────┐
│ ranker_id            ┆ requestDepartureDat ┆ requestReturnDate   ┆ hasAssistant ┆ isGlobal ┆ age │
│ ---                  ┆ e                   ┆ ---                 ┆ ---          ┆ ---      ┆ --- │
│ str                  ┆ ---                 ┆ str                 ┆ bool         ┆ bool     ┆ i64 │
│                      ┆ str                 ┆                     ┆              ┆          ┆     │
╞══════════════════════╪═════════════════════╪═════════════════════╪══════════════╪══════════╪═════╡
│ 0027af83767841fe9bf5 ┆ 2025-01-02T00:00:00 ┆ 2025-01-09T00:00:00 ┆ false        ┆ false    ┆ 38  │
│ 6a33586052…          ┆                     ┆                     ┆              ┆          ┆     │
│ bf9bb86e71ed43fbb0ab ┆ 2024-08-26T00:00:00 ┆ null                ┆ false        ┆ false    ┆ 46  │
│ b3a5d6bb98…          ┆                     ┆                     ┆              ┆          ┆     │
│ 0df86a6eb5484a99a3be ┆ 2024-12-02T00:00:00 ┆ null                ┆ false        ┆ false    ┆ 29  │
│ 7e7e2c0e36…          ┆                     ┆                     ┆              ┆          ┆     │
│ 1967e98940c44b518ac2 ┆ 2024-06-24T00:00:00 ┆ null                ┆ false        ┆ false    ┆ 44  │
│ cb74487145…          ┆                     ┆                     ┆              ┆          ┆     │
│ 6957276eef2c4df685d5 ┆ 2024-09-01T00:00:00 ┆ 2024-09-06T00:00:00 ┆ false        ┆ false    ┆ 29  │
│ 2c98bfbbe8…          ┆                     ┆                     ┆              ┆          ┆     │
│ …                    ┆ …                   ┆ …                   ┆ …            ┆ …        ┆ …   │
│ 9037371c77c04dbcbe31 ┆ 2024-08-01T00:00:00 ┆ null                ┆ false        ┆ false    ┆ 42  │
│ 8c84b1772b…          ┆                     ┆                     ┆              ┆          ┆     │
│ a3a735e6550f42c88058 ┆ 2024-07-09T00:00:00 ┆ 2024-07-10T00:00:00 ┆ false        ┆ false    ┆ 57  │
│ 83906a5948…          ┆                     ┆                     ┆              ┆          ┆     │
│ 9192c360b8094cfeb97e ┆ 2024-11-06T00:00:00 ┆ 2024-11-08T00:00:00 ┆ false        ┆ false    ┆ 39  │
│ db3c1d993a…          ┆                     ┆                     ┆              ┆          ┆     │
│ d44fcecb4424435fbdb5 ┆ 2024-07-05T00:00:00 ┆ null                ┆ false        ┆ false    ┆ 58  │
│ 296125bca8…          ┆                     ┆                     ┆              ┆          ┆     │
│ 35b528e0e6ae410d8f47 ┆ 2024-08-11T00:00:00 ┆ null                ┆ false        ┆ false    ┆ 30  │
│ 521b7a048b…          ┆                     ┆                     ┆              ┆          ┆     │
└──────────────────────┴─────────────────────┴─────────────────────┴──────────────┴──────────┴─────┘

[08/25/25 04:28:52] INFO     2025-08-25 04:28:52,893 [INFO]  ---------------- durs_to_unit start      ]8;id=897034;file:///tmp/ipykernel_74/99047541.py\99047541.py]8;;\:]8;id=715336;file:///tmp/ipykernel_74/99047541.py#6\6]8;;\

[08/25/25 04:29:09] INFO     2025-08-25 04:29:09,030 [INFO]  ################ durs_to_unit elapsed:  ]8;id=401995;file:///tmp/ipykernel_74/99047541.py\99047541.py]8;;\:]8;id=968174;file:///tmp/ipykernel_74/99047541.py#10\10]8;;\
                             16.1311 seconds

[08/25/25 04:29:10] INFO     2025-08-25 04:29:10,145 [INFO] fold_size: 10553                        ]8;id=490654;file:///usr/local/lib/python3.10/site-packages/icecream/icecream.py\icecream.py]8;;\:]8;id=45259;file:///usr/local/lib/python3.10/site-packages/icecream/icecream.py#185\185]8;;\

/tmp/ipykernel_74/775212364.py:34: DeprecationWarning: `is_in` with a collection of the same datatype is ambiguous and deprecated.
Please use `implode` to return to previous behavior.

See https://github.com/pola-rs/polars/issues/22149 for more information.
  unique_rankers = unique_rankers.with_columns(

[08/25/25 04:29:11] INFO     2025-08-25 04:29:11,797 [INFO] len(df_train): 18145372                 ]8;id=628745;file:///usr/local/lib/python3.10/site-packages/icecream/icecream.py\icecream.py]8;;\:]8;id=767570;file:///usr/local/lib/python3.10/site-packages/icecream/icecream.py#185\185]8;;\

                    INFO     2025-08-25 04:29:11,923 [INFO]                                         ]8;id=459258;file:///usr/local/lib/python3.10/site-packages/icecream/icecream.py\icecream.py]8;;\:]8;id=703196;file:///usr/local/lib/python3.10/site-packages/icecream/icecream.py#185\185]8;;\
                             df.group_by('fold').agg(pl.len()).sort('fold'): shape: (7, 2)
                                                                             ┌──────┬─────────┐
                                                                             │ fold ┆ len     │
                                                                             │ ---  ┆ ---     │
                                                                             │ i32  ┆ u32     │
                                                                             ╞══════╪═════════╡
                                                                             │ -1   ┆ 6897776 │
                                                                             │ 0    ┆ 1658934 │
                                                                             │ 1    ┆ 1549793 │
                                                                             │ 2    ┆ 1595175 │
                                                                             │ 3    ┆ 1782522 │
                                                                             │ 4    ┆ 2311308 │
                                                                             │ 5    ┆ 9247640 │
                                                                             └──────┴─────────┘

                    INFO     2025-08-25 04:29:11,981 [INFO] df_valid['day'].min(): 104              ]8;id=871780;file:///usr/local/lib/python3.10/site-packages/icecream/icecream.py\icecream.py]8;;\:]8;id=682379;file:///usr/local/lib/python3.10/site-packages/icecream/icecream.py#185\185]8;;\
                             df_valid['day'].max(): 166
                             df_valid['day'].max() - df_valid['day'].min(): 62

                    INFO     2025-08-25 04:29:11,987 [INFO]  ---------------- gen_feats start         ]8;id=166456;file:///tmp/ipykernel_74/99047541.py\99047541.py]8;;\:]8;id=700237;file:///tmp/ipykernel_74/99047541.py#6\6]8;;\

                    INFO     2025-08-25 04:29:11,991 [INFO]  ---------------- add_group_feats start   ]8;id=969416;file:///tmp/ipykernel_74/99047541.py\99047541.py]8;;\:]8;id=249854;file:///tmp/ipykernel_74/99047541.py#6\6]8;;\

[08/25/25 04:29:12] INFO     2025-08-25 04:29:12,186 [INFO]  add_group_feats added:                  ]8;id=763235;file:///tmp/ipykernel_74/99047541.py\99047541.py]8;;\:]8;id=217024;file:///tmp/ipykernel_74/99047541.py#37\37]8;;\

                    INFO     2025-08-25 04:29:12,192 [INFO] new_cols: ['group_size']               ]8;id=431816;file:///tmp/ipykernel_74/4113492531.py\4113492531.py]8;;\:]8;id=574473;file:///tmp/ipykernel_74/4113492531.py#19\19]8;;\

                    INFO     2025-08-25 04:29:12,197 [INFO] len(new_cols): 1                       ]8;id=269100;file:///tmp/ipykernel_74/4113492531.py\4113492531.py]8;;\:]8;id=817220;file:///tmp/ipykernel_74/4113492531.py#20\20]8;;\

                    INFO     2025-08-25 04:29:12,204 [INFO]  ################ add_group_feats        ]8;id=202271;file:///tmp/ipykernel_74/99047541.py\99047541.py]8;;\:]8;id=882751;file:///tmp/ipykernel_74/99047541.py#10\10]8;;\
                             elapsed: 0.2085 seconds

                    INFO     2025-08-25 04:29:12,209 [INFO]  ---------------- add_user_feats start    ]8;id=376064;file:///tmp/ipykernel_74/99047541.py\99047541.py]8;;\:]8;id=880043;file:///tmp/ipykernel_74/99047541.py#6\6]8;;\

[08/25/25 04:31:23] INFO     2025-08-25 04:31:23,093 [INFO]  add_user_feats added:                   ]8;id=94087;file:///tmp/ipykernel_74/99047541.py\99047541.py]8;;\:]8;id=7963;file:///tmp/ipykernel_74/99047541.py#37\37]8;;\

                    INFO     2025-08-25 04:31:23,098 [INFO] new_cols first 10: ['ff_- ЮТэйр ЗАО',  ]8;id=385938;file:///tmp/ipykernel_74/4113492531.py\4113492531.py]8;;\:]8;id=258323;file:///tmp/ipykernel_74/4113492531.py#16\16]8;;\
                             'ff_2G', 'ff_5N', 'ff_6R', 'ff_6W', 'ff_9W', 'ff_9X', 'ff_A3',
                             'ff_A4', 'ff_AA']

                    INFO     2025-08-25 04:31:23,103 [INFO] new_cols last 10: ['ff_U6', 'ff_UA',   ]8;id=194679;file:///tmp/ipykernel_74/4113492531.py\4113492531.py]8;;\:]8;id=158839;file:///tmp/ipykernel_74/4113492531.py#17\17]8;;\
                             'ff_UN', 'ff_UT', 'ff_VN', 'ff_VS', 'ff_WY', 'ff_Y7', 'ff_primary',
                             'ff_count']

                    INFO     2025-08-25 04:31:23,108 [INFO] len(new_cols): 75                      ]8;id=443196;file:///tmp/ipykernel_74/4113492531.py\4113492531.py]8;;\:]8;id=945001;file:///tmp/ipykernel_74/4113492531.py#20\20]8;;\

                    INFO     2025-08-25 04:31:23,113 [INFO]  ################ add_user_feats         ]8;id=815826;file:///tmp/ipykernel_74/99047541.py\99047541.py]8;;\:]8;id=668726;file:///tmp/ipykernel_74/99047541.py#10\10]8;;\
                             elapsed: 130.8999 seconds

                    INFO     2025-08-25 04:31:23,118 [INFO]  ---------------- add_searchRoute_feats   ]8;id=408322;file:///tmp/ipykernel_74/99047541.py\99047541.py]8;;\:]8;id=462524;file:///tmp/ipykernel_74/99047541.py#6\6]8;;\
                             start

[08/25/25 04:31:29] INFO     2025-08-25 04:31:29,848 [INFO]  add_searchRoute_feats added:            ]8;id=662317;file:///tmp/ipykernel_74/99047541.py\99047541.py]8;;\:]8;id=963317;file:///tmp/ipykernel_74/99047541.py#37\37]8;;\

                    INFO     2025-08-25 04:31:29,854 [INFO] new_cols: ['isDirect',                 ]8;id=460161;file:///tmp/ipykernel_74/4113492531.py\4113492531.py]8;;\:]8;id=471407;file:///tmp/ipykernel_74/4113492531.py#19\19]8;;\
                             'base_searchRoute', 'normed_searchRoute']

                    INFO     2025-08-25 04:31:29,859 [INFO] len(new_cols): 3                       ]8;id=942884;file:///tmp/ipykernel_74/4113492531.py\4113492531.py]8;;\:]8;id=440539;file:///tmp/ipykernel_74/4113492531.py#20\20]8;;\

                    INFO     2025-08-25 04:31:29,864 [INFO]  ################ add_searchRoute_feats  ]8;id=164467;file:///tmp/ipykernel_74/99047541.py\99047541.py]8;;\:]8;id=592509;file:///tmp/ipykernel_74/99047541.py#10\10]8;;\
                             elapsed: 6.7421 seconds

                    INFO     2025-08-25 04:31:29,869 [INFO]  ---------------- add_segment_feats start ]8;id=992855;file:///tmp/ipykernel_74/99047541.py\99047541.py]8;;\:]8;id=722028;file:///tmp/ipykernel_74/99047541.py#6\6]8;;\

[08/25/25 04:31:31] INFO     2025-08-25 04:31:31,586 [INFO]  add_segment_feats added:                ]8;id=48217;file:///tmp/ipykernel_74/99047541.py\99047541.py]8;;\:]8;id=699139;file:///tmp/ipykernel_74/99047541.py#37\37]8;;\

                    INFO     2025-08-25 04:31:31,591 [INFO] new_cols: ['seg_legs0_count',          ]8;id=506298;file:///tmp/ipykernel_74/4113492531.py\4113492531.py]8;;\:]8;id=297382;file:///tmp/ipykernel_74/4113492531.py#19\19]8;;\
                             'seg_legs1_count', 'seg_legs_all_count', 'legs0_departureAirport',
                             'legs1_departureAirport', 'legs0_arrival_airport_iata',
                             'legs1_arrival_airport_iata']

                    INFO     2025-08-25 04:31:31,596 [INFO] len(new_cols): 7                       ]8;id=576453;file:///tmp/ipykernel_74/4113492531.py\4113492531.py]8;;\:]8;id=453150;file:///tmp/ipykernel_74/4113492531.py#20\20]8;;\

                    INFO     2025-08-25 04:31:31,600 [INFO]  ################ add_segment_feats      ]8;id=780498;file:///tmp/ipykernel_74/99047541.py\99047541.py]8;;\:]8;id=760622;file:///tmp/ipykernel_74/99047541.py#10\10]8;;\
                             elapsed: 1.7254 seconds

                    INFO     2025-08-25 04:31:31,604 [INFO]  ----------------                         ]8;id=78715;file:///tmp/ipykernel_74/99047541.py\99047541.py]8;;\:]8;id=661407;file:///tmp/ipykernel_74/99047541.py#6\6]8;;\
                             add_flight_duration_feats start

                    INFO     2025-08-25 04:31:31,780 [INFO]  add_flight_duration_feats added:        ]8;id=395335;file:///tmp/ipykernel_74/99047541.py\99047541.py]8;;\:]8;id=193800;file:///tmp/ipykernel_74/99047541.py#37\37]8;;\

                    INFO     2025-08-25 04:31:31,785 [INFO] new_cols: ['flight_duration_total',    ]8;id=148137;file:///tmp/ipykernel_74/4113492531.py\4113492531.py]8;;\:]8;id=877733;file:///tmp/ipykernel_74/4113492531.py#19\19]8;;\
                             'legs0_duration_ratio', 'legs1_duration_ratio']

                    INFO     2025-08-25 04:31:31,789 [INFO] len(new_cols): 3                       ]8;id=520780;file:///tmp/ipykernel_74/4113492531.py\4113492531.py]8;;\:]8;id=907820;file:///tmp/ipykernel_74/4113492531.py#20\20]8;;\

                    INFO     2025-08-25 04:31:31,794 [INFO]  ################                        ]8;id=886581;file:///tmp/ipykernel_74/99047541.py\99047541.py]8;;\:]8;id=70113;file:///tmp/ipykernel_74/99047541.py#10\10]8;;\
                             add_flight_duration_feats elapsed: 0.1851 seconds

                    INFO     2025-08-25 04:31:31,798 [INFO]  ----------------                         ]8;id=585386;file:///tmp/ipykernel_74/99047541.py\99047541.py]8;;\:]8;id=885384;file:///tmp/ipykernel_74/99047541.py#6\6]8;;\
                             add_segment_geography_time_feats start

                    INFO     2025-08-25 04:31:31,802 [INFO] Adding segment geography and time     ]8;id=328067;file:///tmp/ipykernel_74/3279070257.py\3279070257.py]8;;\:]8;id=752245;file:///tmp/ipykernel_74/3279070257.py#179\179]8;;\
                             features - merged version

[08/25/25 04:31:45] INFO     2025-08-25 04:31:45,866 [INFO]  add_segment_geography_time_feats added: ]8;id=551794;file:///tmp/ipykernel_74/99047541.py\99047541.py]8;;\:]8;id=49667;file:///tmp/ipykernel_74/99047541.py#37\37]8;;\

                    INFO     2025-08-25 04:31:45,871 [INFO] new_cols first 10:                     ]8;id=488589;file:///tmp/ipykernel_74/4113492531.py\4113492531.py]8;;\:]8;id=543668;file:///tmp/ipykernel_74/4113492531.py#16\16]8;;\
                             ['legs0_seg0_dep_lat', 'legs0_seg0_dep_lon', 'legs0_seg0_dep_offset',
                             'legs0_seg0_arr_lat', 'legs0_seg0_arr_lon', 'legs0_seg0_arr_offset',
                             'legs0_seg1_dep_lat', 'legs0_seg1_dep_lon', 'legs0_seg1_dep_offset',
                             'legs0_seg1_arr_lat']

                    INFO     2025-08-25 04:31:45,876 [INFO] new_cols last 10:                      ]8;id=600721;file:///tmp/ipykernel_74/4113492531.py\4113492531.py]8;;\:]8;id=712548;file:///tmp/ipykernel_74/4113492531.py#17\17]8;;\
                             ['legs0_total_segment_distance_km',
                             'legs1_total_segment_distance_km', 'legs0_detour_ratio',
                             'legs1_detour_ratio', 'total_flight_distance_km',
                             'direct_flight_distance_km', 'avg_flight_speed_kmh',
                             'flight_price_per_km', 'avg_direct_speed_kmh', 'direct_price_per_km']

                    INFO     2025-08-25 04:31:45,881 [INFO] len(new_cols): 80                      ]8;id=93371;file:///tmp/ipykernel_74/4113492531.py\4113492531.py]8;;\:]8;id=351234;file:///tmp/ipykernel_74/4113492531.py#20\20]8;;\

                    INFO     2025-08-25 04:31:45,885 [INFO]  ################                        ]8;id=714822;file:///tmp/ipykernel_74/99047541.py\99047541.py]8;;\:]8;id=561783;file:///tmp/ipykernel_74/99047541.py#10\10]8;;\
                             add_segment_geography_time_feats elapsed: 14.0833 seconds

                    INFO     2025-08-25 04:31:45,890 [INFO]  ----------------                         ]8;id=436709;file:///tmp/ipykernel_74/99047541.py\99047541.py]8;;\:]8;id=199543;file:///tmp/ipykernel_74/99047541.py#6\6]8;;\
                             add_travel_duration_feats start

[08/25/25 04:32:13] INFO     2025-08-25 04:32:13,340 [INFO]  add_travel_duration_feats added:        ]8;id=382573;file:///tmp/ipykernel_74/99047541.py\99047541.py]8;;\:]8;id=802422;file:///tmp/ipykernel_74/99047541.py#37\37]8;;\

                    INFO     2025-08-25 04:32:13,346 [INFO] new_cols: ['travel_duration_legs0',    ]8;id=603735;file:///tmp/ipykernel_74/4113492531.py\4113492531.py]8;;\:]8;id=628033;file:///tmp/ipykernel_74/4113492531.py#19\19]8;;\
                             'travel_duration_legs1', 'travel_connection_duration',
                             'travel_duration_total', 'travel_connection_duration_ratio',
                             'flight_duration_travel_ratio', 'book_lead_time_hours',
                             'book_after_time_hours', 'requestDepartureDate_diff_hours',
                             'requestReturnDate_diff_hours', 'travel_total_days',
                             'book_lead_time_days', 'book_after_time_days']

                    INFO     2025-08-25 04:32:13,351 [INFO] len(new_cols): 13                      ]8;id=65940;file:///tmp/ipykernel_74/4113492531.py\4113492531.py]8;;\:]8;id=74255;file:///tmp/ipykernel_74/4113492531.py#20\20]8;;\

                    INFO     2025-08-25 04:32:13,355 [INFO]  ################                        ]8;id=131981;file:///tmp/ipykernel_74/99047541.py\99047541.py]8;;\:]8;id=61690;file:///tmp/ipykernel_74/99047541.py#10\10]8;;\
                             add_travel_duration_feats elapsed: 27.4612 seconds

                    INFO     2025-08-25 04:32:13,360 [INFO]  ---------------- add_time_feats start    ]8;id=101521;file:///tmp/ipykernel_74/99047541.py\99047541.py]8;;\:]8;id=405812;file:///tmp/ipykernel_74/99047541.py#6\6]8;;\

                    INFO     2025-08-25 04:32:13,517 [INFO] time_cols: ['legs0_departureAt',        ]8;id=208844;file:///usr/local/lib/python3.10/site-packages/icecream/icecream.py\icecream.py]8;;\:]8;id=33653;file:///usr/local/lib/python3.10/site-packages/icecream/icecream.py#185\185]8;;\
                                         'legs0_arrivalAt',
                                         'legs1_departureAt',
                                         'legs1_arrivalAt',
                                         'requestDepartureDate',
                                         'requestReturnDate']

[08/25/25 04:33:18] INFO     2025-08-25 04:33:18,119 [INFO]  add_time_feats added:                   ]8;id=519149;file:///tmp/ipykernel_74/99047541.py\99047541.py]8;;\:]8;id=458693;file:///tmp/ipykernel_74/99047541.py#37\37]8;;\

                    INFO     2025-08-25 04:33:18,125 [INFO] new_cols first 10:                     ]8;id=793401;file:///tmp/ipykernel_74/4113492531.py\4113492531.py]8;;\:]8;id=622987;file:///tmp/ipykernel_74/4113492531.py#16\16]8;;\
                             ['time_legs0_departureAt_hour', 'time_legs0_departureAt_weekday',
                             'time_legs0_departureAt_month', 'time_legs0_departureAt_is_weekend',
                             'time_legs0_departureAt_is_peak',
                             'time_legs0_departureAt_is_red_eye', 'time_legs0_departureAt_period',
                             'time_legs0_departureAt_season',
                             'time_legs0_departureAt_is_business_hours',
                             'time_legs0_departureAt_hour_sin']

                    INFO     2025-08-25 04:33:18,130 [INFO] new_cols last 10:                      ]8;id=256994;file:///tmp/ipykernel_74/4113492531.py\4113492531.py]8;;\:]8;id=496044;file:///tmp/ipykernel_74/4113492531.py#17\17]8;;\
                             ['time_requestReturnDate_is_red_eye',
                             'time_requestReturnDate_period', 'time_requestReturnDate_season',
                             'time_requestReturnDate_is_business_hours',
                             'time_requestReturnDate_hour_sin', 'time_requestReturnDate_hour_cos',
                             'time_requestReturnDate_weekday_sin',
                             'time_requestReturnDate_weekday_cos',
                             'time_requestReturnDate_month_sin',
                             'time_requestReturnDate_month_cos']

                    INFO     2025-08-25 04:33:18,136 [INFO] len(new_cols): 90                      ]8;id=885466;file:///tmp/ipykernel_74/4113492531.py\4113492531.py]8;;\:]8;id=66334;file:///tmp/ipykernel_74/4113492531.py#20\20]8;;\

                    INFO     2025-08-25 04:33:18,140 [INFO]  ################ add_time_feats         ]8;id=691154;file:///tmp/ipykernel_74/99047541.py\99047541.py]8;;\:]8;id=86907;file:///tmp/ipykernel_74/99047541.py#10\10]8;;\
                             elapsed: 64.7752 seconds

                    INFO     2025-08-25 04:33:18,169 [INFO] drop_cols: ['legs0_dep_lat',            ]8;id=608661;file:///usr/local/lib/python3.10/site-packages/icecream/icecream.py\icecream.py]8;;\:]8;id=913319;file:///usr/local/lib/python3.10/site-packages/icecream/icecream.py#185\185]8;;\
                                         'legs0_dep_lon',
                                         'legs0_arr_lat',
                                         'legs0_arr_lon',
                                         'legs0_seg0_dep_lat',
                                         'legs0_seg0_dep_lon',
                                         'legs0_seg0_arr_lat',
                                         'legs0_seg0_arr_lon',
                                         'legs0_seg1_dep_lat',
                                         'legs0_seg1_dep_lon',
                                         'legs0_seg1_arr_lat',
                                         'legs0_seg1_arr_lon',
                                         'legs0_seg2_dep_lat',
                                         'legs0_seg2_dep_lon',
                                         'legs0_seg2_arr_lat',
                                         'legs0_seg2_arr_lon',
                                         'legs0_seg3_dep_lat',
                                         'legs0_seg3_dep_lon',
                                         'legs0_seg3_arr_lat',
                                         'legs0_seg3_arr_lon',
                                         'legs1_dep_lat',
                                         'legs1_dep_lon',
                                         'legs1_arr_lat',
                                         'legs1_arr_lon',
                                         'legs1_seg0_dep_lat',
                                         'legs1_seg0_dep_lon',
                                         'legs1_seg0_arr_lat',
                                         'legs1_seg0_arr_lon',
                                         'legs1_seg1_dep_lat',
                                         'legs1_seg1_dep_lon',
                                         'legs1_seg1_arr_lat',
                                         'legs1_seg1_arr_lon',
                                         'legs1_seg2_dep_lat',
                                         'legs1_seg2_dep_lon',
                                         'legs1_seg2_arr_lat',
                                         'legs1_seg2_arr_lon',
                                         'legs1_seg3_dep_lat',
                                         'legs1_seg3_dep_lon',
                                         'legs1_seg3_arr_lat',
                                         'legs1_seg3_arr_lon']

                    INFO     2025-08-25 04:33:18,180 [INFO]  ---------------- add_cabin_feats start   ]8;id=844380;file:///tmp/ipykernel_74/99047541.py\99047541.py]8;;\:]8;id=749124;file:///tmp/ipykernel_74/99047541.py#6\6]8;;\

[08/25/25 04:33:19] INFO     2025-08-25 04:33:19,215 [INFO]  add_cabin_feats added:                  ]8;id=320884;file:///tmp/ipykernel_74/99047541.py\99047541.py]8;;\:]8;id=298060;file:///tmp/ipykernel_74/99047541.py#37\37]8;;\

                    INFO     2025-08-25 04:33:19,220 [INFO] new_cols: ['avg_cabin_legs0',          ]8;id=658107;file:///tmp/ipykernel_74/4113492531.py\4113492531.py]8;;\:]8;id=629116;file:///tmp/ipykernel_74/4113492531.py#19\19]8;;\
                             'avg_cabin_legs1', 'avg_cabin_legs_all']

                    INFO     2025-08-25 04:33:19,225 [INFO] len(new_cols): 3                       ]8;id=849516;file:///tmp/ipykernel_74/4113492531.py\4113492531.py]8;;\:]8;id=282643;file:///tmp/ipykernel_74/4113492531.py#20\20]8;;\

                    INFO     2025-08-25 04:33:19,230 [INFO]  ################ add_cabin_feats        ]8;id=888394;file:///tmp/ipykernel_74/99047541.py\99047541.py]8;;\:]8;id=538826;file:///tmp/ipykernel_74/99047541.py#10\10]8;;\
                             elapsed: 1.0449 seconds

                    INFO     2025-08-25 04:33:19,234 [INFO]  ---------------- add_baggage_feats start ]8;id=848893;file:///tmp/ipykernel_74/99047541.py\99047541.py]8;;\:]8;id=555367;file:///tmp/ipykernel_74/99047541.py#6\6]8;;\

[08/25/25 04:33:20] INFO     2025-08-25 04:33:20,743 [INFO]  add_baggage_feats added:                ]8;id=386254;file:///tmp/ipykernel_74/99047541.py\99047541.py]8;;\:]8;id=445979;file:///tmp/ipykernel_74/99047541.py#37\37]8;;\

                    INFO     2025-08-25 04:33:20,748 [INFO] new_cols first 10:                     ]8;id=462045;file:///tmp/ipykernel_74/4113492531.py\4113492531.py]8;;\:]8;id=866409;file:///tmp/ipykernel_74/4113492531.py#16\16]8;;\
                             ['legs0_segments0_baggage_count', 'legs0_segments0_baggage_weight',
                             'legs0_segments1_baggage_count', 'legs0_segments1_baggage_weight',
                             'legs0_segments2_baggage_count', 'legs0_segments2_baggage_weight',
                             'legs0_segments3_baggage_count', 'legs0_segments3_baggage_weight',
                             'legs1_segments0_baggage_count', 'legs1_segments0_baggage_weight']

                    INFO     2025-08-25 04:33:20,754 [INFO] new_cols last 10:                      ]8;id=584;file:///tmp/ipykernel_74/4113492531.py\4113492531.py]8;;\:]8;id=540696;file:///tmp/ipykernel_74/4113492531.py#17\17]8;;\
                             ['legs1_segments2_baggage_count', 'legs1_segments2_baggage_weight',
                             'legs1_segments3_baggage_count', 'legs1_segments3_baggage_weight',
                             'avg_baggage_count_legs0', 'avg_baggage_count_legs1',
                             'avg_baggage_weight_legs0', 'avg_baggage_weight_legs1',
                             'avg_baggage_count_legs_all', 'avg_baggage_weight_legs_all']

                    INFO     2025-08-25 04:33:20,759 [INFO] len(new_cols): 22                      ]8;id=571259;file:///tmp/ipykernel_74/4113492531.py\4113492531.py]8;;\:]8;id=25845;file:///tmp/ipykernel_74/4113492531.py#20\20]8;;\

                    INFO     2025-08-25 04:33:20,764 [INFO]  ################ add_baggage_feats      ]8;id=432684;file:///tmp/ipykernel_74/99047541.py\99047541.py]8;;\:]8;id=48971;file:///tmp/ipykernel_74/99047541.py#10\10]8;;\
                             elapsed: 1.5244 seconds

                    INFO     2025-08-25 04:33:20,769 [INFO]  ---------------- add_seats_feats start   ]8;id=493072;file:///tmp/ipykernel_74/99047541.py\99047541.py]8;;\:]8;id=842769;file:///tmp/ipykernel_74/99047541.py#6\6]8;;\

[08/25/25 04:33:21] INFO     2025-08-25 04:33:21,908 [INFO]  add_seats_feats added:                  ]8;id=718204;file:///tmp/ipykernel_74/99047541.py\99047541.py]8;;\:]8;id=856324;file:///tmp/ipykernel_74/99047541.py#37\37]8;;\

                    INFO     2025-08-25 04:33:21,914 [INFO] new_cols: ['avg_seats_count_legs0',    ]8;id=96701;file:///tmp/ipykernel_74/4113492531.py\4113492531.py]8;;\:]8;id=176717;file:///tmp/ipykernel_74/4113492531.py#19\19]8;;\
                             'avg_seats_count_legs1', 'avg_seats_count_legs_all']

                    INFO     2025-08-25 04:33:21,918 [INFO] len(new_cols): 3                       ]8;id=872257;file:///tmp/ipykernel_74/4113492531.py\4113492531.py]8;;\:]8;id=373101;file:///tmp/ipykernel_74/4113492531.py#20\20]8;;\

                    INFO     2025-08-25 04:33:21,923 [INFO]  ################ add_seats_feats        ]8;id=974133;file:///tmp/ipykernel_74/99047541.py\99047541.py]8;;\:]8;id=119790;file:///tmp/ipykernel_74/99047541.py#10\10]8;;\
                             elapsed: 1.1487 seconds

                    INFO     2025-08-25 04:33:21,927 [INFO]  ---------------- add_carrier_feats start ]8;id=892537;file:///tmp/ipykernel_74/99047541.py\99047541.py]8;;\:]8;id=672846;file:///tmp/ipykernel_74/99047541.py#6\6]8;;\

[08/25/25 04:34:11] INFO     2025-08-25 04:34:11,900 [INFO]  add_carrier_feats added:                ]8;id=599038;file:///tmp/ipykernel_74/99047541.py\99047541.py]8;;\:]8;id=337898;file:///tmp/ipykernel_74/99047541.py#37\37]8;;\

                    INFO     2025-08-25 04:34:11,906 [INFO] new_cols: ['num_unique_carriers',      ]8;id=86874;file:///tmp/ipykernel_74/4113492531.py\4113492531.py]8;;\:]8;id=271054;file:///tmp/ipykernel_74/4113492531.py#19\19]8;;\
                             'carrier_diversity_ratio']

                    INFO     2025-08-25 04:34:11,911 [INFO] len(new_cols): 2                       ]8;id=338544;file:///tmp/ipykernel_74/4113492531.py\4113492531.py]8;;\:]8;id=11834;file:///tmp/ipykernel_74/4113492531.py#20\20]8;;\

                    INFO     2025-08-25 04:34:11,916 [INFO]  ################ add_carrier_feats      ]8;id=128563;file:///tmp/ipykernel_74/99047541.py\99047541.py]8;;\:]8;id=200755;file:///tmp/ipykernel_74/99047541.py#10\10]8;;\
                             elapsed: 49.9843 seconds

                    INFO     2025-08-25 04:34:11,920 [INFO]  ---------------- add_flighthash_feats    ]8;id=8353;file:///tmp/ipykernel_74/99047541.py\99047541.py]8;;\:]8;id=203763;file:///tmp/ipykernel_74/99047541.py#6\6]8;;\
                             start

[08/25/25 04:34:13] INFO     2025-08-25 04:34:13,304 [INFO]  add_flighthash_feats added:             ]8;id=223323;file:///tmp/ipykernel_74/99047541.py\99047541.py]8;;\:]8;id=784607;file:///tmp/ipykernel_74/99047541.py#37\37]8;;\

                    INFO     2025-08-25 04:34:13,310 [INFO] new_cols: ['flight_hash_count',        ]8;id=273237;file:///tmp/ipykernel_74/4113492531.py\4113492531.py]8;;\:]8;id=336369;file:///tmp/ipykernel_74/4113492531.py#19\19]8;;\
                             'flight_hash_ratio', 'rank_flight_hash_count']

                    INFO     2025-08-25 04:34:13,314 [INFO] len(new_cols): 3                       ]8;id=861102;file:///tmp/ipykernel_74/4113492531.py\4113492531.py]8;;\:]8;id=548991;file:///tmp/ipykernel_74/4113492531.py#20\20]8;;\

                    INFO     2025-08-25 04:34:13,319 [INFO]  ################ add_flighthash_feats   ]8;id=997522;file:///tmp/ipykernel_74/99047541.py\99047541.py]8;;\:]8;id=554540;file:///tmp/ipykernel_74/99047541.py#10\10]8;;\
                             elapsed: 1.3945 seconds

                    INFO     2025-08-25 04:34:13,324 [INFO]  ---------------- add_ranking_feats start ]8;id=9375;file:///tmp/ipykernel_74/99047541.py\99047541.py]8;;\:]8;id=380356;file:///tmp/ipykernel_74/99047541.py#6\6]8;;\

[08/25/25 04:34:14] INFO     2025-08-25 04:34:14,781 [INFO]  add_ranking_feats added:                ]8;id=925928;file:///tmp/ipykernel_74/99047541.py\99047541.py]8;;\:]8;id=522749;file:///tmp/ipykernel_74/99047541.py#37\37]8;;\

                    INFO     2025-08-25 04:34:14,787 [INFO] new_cols: ['rank_totalPrice',          ]8;id=811503;file:///tmp/ipykernel_74/4113492531.py\4113492531.py]8;;\:]8;id=831272;file:///tmp/ipykernel_74/4113492531.py#19\19]8;;\
                             'rank_flight_duration_total', 'rank_book_lead_time_hours',
                             'rank_flight_duration_travel_ratio', 'rank_seg_legs_all_count',
                             'rank_avg_cabin_legs_all', 'rank_avg_baggage_count_legs_all',
                             'rank_avg_baggage_weight_legs_all', 'rank_direct_price_per_km']

                    INFO     2025-08-25 04:34:14,796 [INFO] len(new_cols): 9                       ]8;id=209710;file:///tmp/ipykernel_74/4113492531.py\4113492531.py]8;;\:]8;id=902727;file:///tmp/ipykernel_74/4113492531.py#20\20]8;;\

                    INFO     2025-08-25 04:34:14,804 [INFO]  ################ add_ranking_feats      ]8;id=635703;file:///tmp/ipykernel_74/99047541.py\99047541.py]8;;\:]8;id=845250;file:///tmp/ipykernel_74/99047541.py#10\10]8;;\
                             elapsed: 1.4753 seconds

                    INFO     2025-08-25 04:34:14,810 [INFO]  ---------------- add_ranking_feats start ]8;id=285270;file:///tmp/ipykernel_74/99047541.py\99047541.py]8;;\:]8;id=769911;file:///tmp/ipykernel_74/99047541.py#6\6]8;;\

[08/25/25 04:34:27] INFO     2025-08-25 04:34:27,133 [INFO]  add_ranking_feats added:                ]8;id=233391;file:///tmp/ipykernel_74/99047541.py\99047541.py]8;;\:]8;id=884615;file:///tmp/ipykernel_74/99047541.py#37\37]8;;\

                    INFO     2025-08-25 04:34:27,138 [INFO] new_cols:                              ]8;id=988921;file:///tmp/ipykernel_74/4113492531.py\4113492531.py]8;;\:]8;id=733147;file:///tmp/ipykernel_74/4113492531.py#19\19]8;;\
                             ['rank_totalPrice_in_hash_group',
                             'rank_flight_duration_total_in_hash_group',
                             'rank_book_lead_time_hours_in_hash_group',
                             'rank_flight_duration_travel_ratio_in_hash_group',
                             'rank_seg_legs_all_count_in_hash_group',
                             'rank_avg_cabin_legs_all_in_hash_group',
                             'rank_avg_baggage_count_legs_all_in_hash_group',
                             'rank_avg_baggage_weight_legs_all_in_hash_group',
                             'rank_direct_price_per_km_in_hash_group']

                    INFO     2025-08-25 04:34:27,144 [INFO] len(new_cols): 9                       ]8;id=481518;file:///tmp/ipykernel_74/4113492531.py\4113492531.py]8;;\:]8;id=244991;file:///tmp/ipykernel_74/4113492531.py#20\20]8;;\

                    INFO     2025-08-25 04:34:27,149 [INFO]  ################ add_ranking_feats      ]8;id=64188;file:///tmp/ipykernel_74/99047541.py\99047541.py]8;;\:]8;id=198468;file:///tmp/ipykernel_74/99047541.py#10\10]8;;\
                             elapsed: 12.3353 seconds

                    INFO     2025-08-25 04:34:27,154 [INFO]  ---------------- add_stats_feats start   ]8;id=33050;file:///tmp/ipykernel_74/99047541.py\99047541.py]8;;\:]8;id=661022;file:///tmp/ipykernel_74/99047541.py#6\6]8;;\

[08/25/25 04:34:28] INFO     2025-08-25 04:34:28,759 [INFO]  add_stats_feats added:                  ]8;id=289995;file:///tmp/ipykernel_74/99047541.py\99047541.py]8;;\:]8;id=20444;file:///tmp/ipykernel_74/99047541.py#37\37]8;;\

                    INFO     2025-08-25 04:34:28,764 [INFO] new_cols first 10:                     ]8;id=341188;file:///tmp/ipykernel_74/4113492531.py\4113492531.py]8;;\:]8;id=451339;file:///tmp/ipykernel_74/4113492531.py#16\16]8;;\
                             ['avg_totalPrice_uid_stats', 'min_totalPrice_uid_stats',
                             'max_totalPrice_uid_stats', 'std_totalPrice_uid_stats',
                             'median_totalPrice_uid_stats', 'avg_flight_duration_total_uid_stats',
                             'min_flight_duration_total_uid_stats',
                             'max_flight_duration_total_uid_stats',
                             'std_flight_duration_total_uid_stats',
                             'median_flight_duration_total_uid_stats']

                    INFO     2025-08-25 04:34:28,769 [INFO] new_cols last 10:                      ]8;id=139318;file:///tmp/ipykernel_74/4113492531.py\4113492531.py]8;;\:]8;id=538700;file:///tmp/ipykernel_74/4113492531.py#17\17]8;;\
                             ['avg_cabin_legs_all_uid_stats_ratio',
                             'avg_baggage_count_legs_all_zscore_uid_stats',
                             'avg_baggage_count_legs_all_minmax_uid_stats',
                             'avg_baggage_count_legs_all_uid_stats_ratio',
                             'avg_baggage_weight_legs_all_zscore_uid_stats',
                             'avg_baggage_weight_legs_all_minmax_uid_stats',
                             'avg_baggage_weight_legs_all_uid_stats_ratio',
                             'direct_price_per_km_zscore_uid_stats',
                             'direct_price_per_km_minmax_uid_stats',
                             'direct_price_per_km_uid_stats_ratio']

                    INFO     2025-08-25 04:34:28,774 [INFO] len(new_cols): 72                      ]8;id=20477;file:///tmp/ipykernel_74/4113492531.py\4113492531.py]8;;\:]8;id=932469;file:///tmp/ipykernel_74/4113492531.py#20\20]8;;\

                    INFO     2025-08-25 04:34:28,778 [INFO]  ################ add_stats_feats        ]8;id=254522;file:///tmp/ipykernel_74/99047541.py\99047541.py]8;;\:]8;id=976143;file:///tmp/ipykernel_74/99047541.py#10\10]8;;\
                             elapsed: 1.6188 seconds

                    INFO     2025-08-25 04:34:28,782 [INFO]  ---------------- add_stats_feats start   ]8;id=99435;file:///tmp/ipykernel_74/99047541.py\99047541.py]8;;\:]8;id=636226;file:///tmp/ipykernel_74/99047541.py#6\6]8;;\

[08/25/25 04:34:30] INFO     2025-08-25 04:34:30,608 [INFO]  add_stats_feats added:                  ]8;id=671625;file:///tmp/ipykernel_74/99047541.py\99047541.py]8;;\:]8;id=282752;file:///tmp/ipykernel_74/99047541.py#37\37]8;;\

                    INFO     2025-08-25 04:34:30,613 [INFO] new_cols first 10:                     ]8;id=92745;file:///tmp/ipykernel_74/4113492531.py\4113492531.py]8;;\:]8;id=523362;file:///tmp/ipykernel_74/4113492531.py#16\16]8;;\
                             ['avg_totalPrice_companyID_stats', 'min_totalPrice_companyID_stats',
                             'max_totalPrice_companyID_stats', 'std_totalPrice_companyID_stats',
                             'median_totalPrice_companyID_stats',
                             'avg_flight_duration_total_companyID_stats',
                             'min_flight_duration_total_companyID_stats',
                             'max_flight_duration_total_companyID_stats',
                             'std_flight_duration_total_companyID_stats',
                             'median_flight_duration_total_companyID_stats']

                    INFO     2025-08-25 04:34:30,619 [INFO] new_cols last 10:                      ]8;id=153953;file:///tmp/ipykernel_74/4113492531.py\4113492531.py]8;;\:]8;id=408426;file:///tmp/ipykernel_74/4113492531.py#17\17]8;;\
                             ['avg_cabin_legs_all_companyID_stats_ratio',
                             'avg_baggage_count_legs_all_zscore_companyID_stats',
                             'avg_baggage_count_legs_all_minmax_companyID_stats',
                             'avg_baggage_count_legs_all_companyID_stats_ratio',
                             'avg_baggage_weight_legs_all_zscore_companyID_stats',
                             'avg_baggage_weight_legs_all_minmax_companyID_stats',
                             'avg_baggage_weight_legs_all_companyID_stats_ratio',
                             'direct_price_per_km_zscore_companyID_stats',
                             'direct_price_per_km_minmax_companyID_stats',
                             'direct_price_per_km_companyID_stats_ratio']

                    INFO     2025-08-25 04:34:30,624 [INFO] len(new_cols): 72                      ]8;id=792575;file:///tmp/ipykernel_74/4113492531.py\4113492531.py]8;;\:]8;id=602819;file:///tmp/ipykernel_74/4113492531.py#20\20]8;;\

                    INFO     2025-08-25 04:34:30,628 [INFO]  ################ add_stats_feats        ]8;id=812829;file:///tmp/ipykernel_74/99047541.py\99047541.py]8;;\:]8;id=385143;file:///tmp/ipykernel_74/99047541.py#10\10]8;;\
                             elapsed: 1.8418 seconds

                    INFO     2025-08-25 04:34:30,645 [INFO] drop_cols: []                           ]8;id=422660;file:///usr/local/lib/python3.10/site-packages/icecream/icecream.py\icecream.py]8;;\:]8;id=564253;file:///usr/local/lib/python3.10/site-packages/icecream/icecream.py#185\185]8;;\

                    INFO     2025-08-25 04:34:30,723 [INFO]  ---------------- make_history_avg start  ]8;id=122924;file:///tmp/ipykernel_74/99047541.py\99047541.py]8;;\:]8;id=355325;file:///tmp/ipykernel_74/99047541.py#6\6]8;;\

Обработка ranker_id:   0%|          | 0/105539 [00:00<?, ?it/s]

Обработка ranker_id:   2%|▏         | 1670/105539 [00:10<10:22, 166.94it/s]

Обработка ranker_id:   3%|▎         | 3340/105539 [00:20<10:12, 166.95it/s]

Обработка ranker_id:   5%|▍         | 5010/105539 [00:30<10:02, 166.94it/s]

Обработка ranker_id:   6%|▋         | 6680/105539 [00:40<09:52, 166.87it/s]

Обработка ranker_id:   8%|▊         | 8348/105539 [00:50<09:42, 166.84it/s]

Обработка ranker_id:   9%|▉         | 10016/105539 [01:00<09:33, 166.57it/s]

Обработка ranker_id:  11%|█         | 11677/105539 [01:10<09:25, 166.12it/s]

Обработка ranker_id:  13%|█▎        | 13344/105539 [01:20<09:14, 166.29it/s]

Обработка ranker_id:  14%|█▍        | 15014/105539 [01:30<09:03, 166.50it/s]

Обработка ranker_id:  16%|█▌        | 16685/105539 [01:40<08:53, 166.66it/s]

Обработка ranker_id:  17%|█▋        | 18356/105539 [01:50<08:42, 166.71it/s]

Обработка ranker_id:  19%|█▉        | 20043/105539 [02:00<08:31, 167.30it/s]

Обработка ranker_id:  21%|██        | 21730/105539 [02:10<08:21, 167.27it/s]

Обработка ranker_id:  22%|██▏       | 23402/105539 [02:20<08:11, 167.22it/s]

Обработка ranker_id:  24%|██▍       | 25073/105539 [02:30<08:01, 166.97it/s]

Обработка ranker_id:  25%|██▌       | 26738/105539 [02:40<07:53, 166.31it/s]

Обработка ranker_id:  27%|██▋       | 28405/105539 [02:50<07:43, 166.41it/s]

Обработка ranker_id:  28%|██▊       | 30072/105539 [03:00<07:33, 166.24it/s]

Обработка ranker_id:  30%|███       | 31732/105539 [03:10<07:24, 166.14it/s]

Обработка ranker_id:  32%|███▏      | 33410/105539 [03:20<07:12, 166.64it/s]

Обработка ranker_id:  33%|███▎      | 35088/105539 [03:30<07:03, 166.26it/s]

Обработка ranker_id:  35%|███▍      | 36768/105539 [03:40<06:52, 166.75it/s]

Обработка ranker_id:  36%|███▋      | 38448/105539 [03:50<06:42, 166.48it/s]

Обработка ranker_id:  38%|███▊      | 40112/105539 [04:00<06:33, 166.44it/s]

Обработка ranker_id:  40%|███▉      | 41782/105539 [04:10<06:22, 166.59it/s]

Обработка ranker_id:  41%|████      | 43468/105539 [04:20<06:11, 167.19it/s]

Обработка ranker_id:  43%|████▎     | 45154/105539 [04:30<06:01, 166.95it/s]

Обработка ranker_id:  44%|████▍     | 46830/105539 [04:40<05:51, 167.11it/s]

Обработка ranker_id:  46%|████▌     | 48506/105539 [04:50<05:41, 166.87it/s]

Обработка ranker_id:  48%|████▊     | 50169/105539 [05:00<05:32, 166.55it/s]

Обработка ranker_id:  49%|████▉     | 51836/105539 [05:10<05:22, 166.60it/s]

Обработка ranker_id:  51%|█████     | 53503/105539 [05:21<05:12, 166.40it/s]

Обработка ranker_id:  52%|█████▏    | 55168/105539 [05:31<05:02, 166.42it/s]

Обработка ranker_id:  54%|█████▍    | 56833/105539 [05:41<04:52, 166.30it/s]

Обработка ranker_id:  55%|█████▌    | 58503/105539 [05:51<04:42, 166.48it/s]

Обработка ranker_id:  57%|█████▋    | 60183/105539 [06:01<04:31, 166.92it/s]

Обработка ranker_id:  59%|█████▊    | 61863/105539 [06:11<04:21, 166.71it/s]

Обработка ranker_id:  60%|██████    | 63527/105539 [06:21<04:12, 166.60it/s]

Обработка ranker_id:  62%|██████▏   | 65191/105539 [06:31<04:02, 166.22it/s]

Обработка ranker_id:  63%|██████▎   | 66858/105539 [06:41<03:52, 166.34it/s]

Обработка ranker_id:  65%|██████▍   | 68525/105539 [06:51<03:42, 166.15it/s]

Обработка ranker_id:  67%|██████▋   | 70202/105539 [07:01<03:32, 166.59it/s]

Обработка ranker_id:  68%|██████▊   | 71879/105539 [07:11<03:22, 166.42it/s]

Обработка ranker_id:  70%|██████▉   | 73542/105539 [07:21<03:12, 166.37it/s]

Обработка ranker_id:  71%|███████▏  | 75209/105539 [07:31<03:02, 166.45it/s]

Обработка ranker_id:  73%|███████▎  | 76876/105539 [07:41<02:52, 166.20it/s]

Обработка ranker_id:  74%|███████▍  | 78533/105539 [07:51<02:42, 165.97it/s]

Обработка ranker_id:  76%|███████▌  | 80199/105539 [08:01<02:32, 166.15it/s]

Обработка ranker_id:  78%|███████▊  | 81865/105539 [08:11<02:22, 166.22it/s]

Обработка ranker_id:  79%|███████▉  | 83538/105539 [08:21<02:12, 166.52it/s]

Обработка ranker_id:  81%|████████  | 85211/105539 [08:31<02:02, 166.62it/s]

Обработка ranker_id:  82%|████████▏ | 86885/105539 [08:41<01:51, 166.82it/s]

Обработка ranker_id:  84%|████████▍ | 88559/105539 [08:51<01:41, 166.65it/s]

Обработка ranker_id:  86%|████████▌ | 90237/105539 [09:01<01:31, 166.97it/s]

Обработка ranker_id:  87%|████████▋ | 91915/105539 [09:11<01:21, 166.84it/s]

Обработка ranker_id:  89%|████████▊ | 93581/105539 [09:21<01:11, 166.54it/s]

Обработка ranker_id:  90%|█████████ | 95249/105539 [09:31<01:01, 166.59it/s]

Обработка ranker_id:  92%|█████████▏| 96917/105539 [09:41<00:51, 166.62it/s]

Обработка ranker_id:  93%|█████████▎| 98597/105539 [09:51<00:41, 167.03it/s]

Обработка ranker_id:  95%|█████████▌| 100277/105539 [10:01<00:31, 166.91it/s]

Обработка ranker_id:  97%|█████████▋| 101944/105539 [10:11<00:21, 166.59it/s]

Обработка ranker_id:  98%|█████████▊| 103607/105539 [10:21<00:11, 166.50it/s]

Обработка ranker_id: 100%|█████████▉| 105270/105539 [10:31<00:01, 165.97it/s]

Обработка ranker_id: 100%|██████████| 105539/105539 [10:33<00:00, 166.56it/s]

[08/25/25 04:45:21] INFO     2025-08-25 04:45:21,508 [INFO]  make_history_avg added:                 ]8;id=741617;file:///tmp/ipykernel_74/99047541.py\99047541.py]8;;\:]8;id=438385;file:///tmp/ipykernel_74/99047541.py#37\37]8;;\

                    INFO     2025-08-25 04:45:21,515 [INFO] new_cols first 10:                     ]8;id=323092;file:///tmp/ipykernel_74/4113492531.py\4113492531.py]8;;\:]8;id=944003;file:///tmp/ipykernel_74/4113492531.py#16\16]8;;\
                             ['time_legs0_departureAt_hour_uid_mean',
                             'time_legs0_departureAt_hour_uid_std',
                             'time_legs0_departureAt_hour_uid_count',
                             'time_legs0_departureAt_hour_uid_median',
                             'time_legs0_departureAt_hour_uid_q25',
                             'time_legs0_departureAt_hour_uid_q75',
                             'time_legs1_departureAt_hour_uid_mean',
                             'time_legs1_departureAt_hour_uid_std',
                             'time_legs1_departureAt_hour_uid_count',
                             'time_legs1_departureAt_hour_uid_median']

                    INFO     2025-08-25 04:45:21,520 [INFO] new_cols last 10:                      ]8;id=102250;file:///tmp/ipykernel_74/4113492531.py\4113492531.py]8;;\:]8;id=219862;file:///tmp/ipykernel_74/4113492531.py#17\17]8;;\
                             ['miniRules1_statusInfos_uid_count',
                             'miniRules1_statusInfos_uid_median',
                             'miniRules1_statusInfos_uid_q25', 'miniRules1_statusInfos_uid_q75',
                             'miniRules0_statusInfos_uid_mean', 'miniRules0_statusInfos_uid_std',
                             'miniRules0_statusInfos_uid_count',
                             'miniRules0_statusInfos_uid_median',
                             'miniRules0_statusInfos_uid_q25', 'miniRules0_statusInfos_uid_q75']

                    INFO     2025-08-25 04:45:21,525 [INFO] len(new_cols): 72                      ]8;id=835772;file:///tmp/ipykernel_74/4113492531.py\4113492531.py]8;;\:]8;id=99169;file:///tmp/ipykernel_74/4113492531.py#20\20]8;;\

                    INFO     2025-08-25 04:45:21,530 [INFO]  ################ make_history_avg       ]8;id=98090;file:///tmp/ipykernel_74/99047541.py\99047541.py]8;;\:]8;id=149160;file:///tmp/ipykernel_74/99047541.py#10\10]8;;\
                             elapsed: 650.8016 seconds

                    INFO     2025-08-25 04:45:21,683 [INFO]  ---------------- make_history_avg start  ]8;id=172349;file:///tmp/ipykernel_74/99047541.py\99047541.py]8;;\:]8;id=635989;file:///tmp/ipykernel_74/99047541.py#6\6]8;;\

Обработка ranker_id:   0%|          | 0/105539 [00:00<?, ?it/s]

Обработка ranker_id:   1%|▏         | 1408/105539 [00:10<12:19, 140.76it/s]

Обработка ranker_id:   3%|▎         | 2816/105539 [00:20<12:09, 140.73it/s]

Обработка ranker_id:   4%|▍         | 4233/105539 [00:30<11:57, 141.17it/s]

Обработка ranker_id:   5%|▌         | 5650/105539 [00:40<11:47, 141.14it/s]

Обработка ranker_id:   7%|▋         | 7062/105539 [00:50<11:38, 141.06it/s]

Обработка ranker_id:   8%|▊         | 8472/105539 [01:00<11:28, 140.89it/s]

Обработка ranker_id:   9%|▉         | 9884/105539 [01:10<11:18, 140.98it/s]

Обработка ranker_id:  11%|█         | 11296/105539 [01:20<11:10, 140.64it/s]

Обработка ranker_id:  12%|█▏        | 12696/105539 [01:30<11:01, 140.39it/s]

Обработка ranker_id:  13%|█▎        | 14095/105539 [01:40<10:53, 140.02it/s]

Обработка ranker_id:  15%|█▍        | 15503/105539 [01:50<10:42, 140.24it/s]

Обработка ranker_id:  16%|█▌        | 16911/105539 [02:00<10:33, 139.80it/s]

Обработка ranker_id:  17%|█▋        | 18309/105539 [02:10<10:24, 139.78it/s]

Обработка ranker_id:  19%|█▊        | 19715/105539 [02:20<10:12, 140.01it/s]

Обработка ranker_id:  20%|██        | 21121/105539 [02:30<10:03, 139.92it/s]

Обработка ranker_id:  21%|██▏       | 22529/105539 [02:40<09:52, 140.16it/s]

Обработка ranker_id:  23%|██▎       | 23937/105539 [02:50<09:42, 140.06it/s]

Обработка ranker_id:  24%|██▍       | 25348/105539 [03:00<09:31, 140.35it/s]

Обработка ranker_id:  25%|██▌       | 26765/105539 [03:10<09:19, 140.74it/s]

Обработка ranker_id:  27%|██▋       | 28182/105539 [03:20<09:10, 140.47it/s]

Обработка ranker_id:  28%|██▊       | 29585/105539 [03:30<09:00, 140.40it/s]

Обработка ranker_id:  29%|██▉       | 30989/105539 [03:40<08:51, 140.39it/s]

Обработка ranker_id:  31%|███       | 32395/105539 [03:50<08:40, 140.43it/s]

Обработка ranker_id:  32%|███▏      | 33801/105539 [04:00<08:31, 140.28it/s]

Обработка ranker_id:  33%|███▎      | 35209/105539 [04:10<08:20, 140.42it/s]

Обработка ranker_id:  35%|███▍      | 36617/105539 [04:20<08:11, 140.29it/s]

Обработка ranker_id:  36%|███▌      | 38034/105539 [04:30<07:59, 140.70it/s]

Обработка ranker_id:  37%|███▋      | 39451/105539 [04:40<07:50, 140.48it/s]

Обработка ranker_id:  39%|███▊      | 40857/105539 [04:50<07:40, 140.50it/s]

Обработка ranker_id:  40%|████      | 42263/105539 [05:00<07:30, 140.46it/s]

Обработка ranker_id:  41%|████▏     | 43667/105539 [05:11<07:21, 140.19it/s]

Обработка ranker_id:  43%|████▎     | 45064/105539 [05:21<07:11, 140.04it/s]

Обработка ranker_id:  44%|████▍     | 46468/105539 [05:31<07:01, 140.13it/s]

Обработка ranker_id:  45%|████▌     | 47873/105539 [05:41<06:51, 140.23it/s]

Обработка ranker_id:  47%|████▋     | 49282/105539 [05:51<06:40, 140.41it/s]

Обработка ranker_id:  48%|████▊     | 50691/105539 [06:01<06:30, 140.52it/s]

Обработка ranker_id:  49%|████▉     | 52099/105539 [06:11<06:20, 140.44it/s]

Обработка ranker_id:  51%|█████     | 53502/105539 [06:21<06:10, 140.39it/s]

Обработка ranker_id:  52%|█████▏    | 54917/105539 [06:31<05:59, 140.72it/s]

Обработка ranker_id:  53%|█████▎    | 56332/105539 [06:41<05:49, 140.63it/s]

Обработка ranker_id:  55%|█████▍    | 57740/105539 [06:51<05:39, 140.67it/s]

Обработка ranker_id:  56%|█████▌    | 59148/105539 [07:01<05:29, 140.60it/s]

Обработка ranker_id:  57%|█████▋    | 60553/105539 [07:11<05:20, 140.27it/s]

Обработка ranker_id:  59%|█████▊    | 61948/105539 [07:21<05:11, 139.90it/s]

Обработка ranker_id:  60%|██████    | 63347/105539 [07:31<05:01, 139.88it/s]

Обработка ranker_id:  61%|██████▏   | 64751/105539 [07:41<04:51, 140.01it/s]

Обработка ranker_id:  63%|██████▎   | 66159/105539 [07:51<04:40, 140.23it/s]

Обработка ranker_id:  64%|██████▍   | 67571/105539 [08:01<04:30, 140.52it/s]

Обработка ranker_id:  65%|██████▌   | 68983/105539 [08:11<04:20, 140.54it/s]

Обработка ranker_id:  67%|██████▋   | 70390/105539 [08:21<04:10, 140.58it/s]

Обработка ranker_id:  68%|██████▊   | 71800/105539 [08:31<03:59, 140.68it/s]

Обработка ranker_id:  69%|██████▉   | 73210/105539 [08:41<03:50, 140.51it/s]

Обработка ranker_id:  71%|███████   | 74612/105539 [08:51<03:40, 140.39it/s]

Обработка ranker_id:  72%|███████▏  | 76015/105539 [09:01<03:30, 140.35it/s]

Обработка ranker_id:  73%|███████▎  | 77418/105539 [09:11<03:20, 140.23it/s]

Обработка ranker_id:  75%|███████▍  | 78822/105539 [09:21<03:10, 140.26it/s]

Обработка ranker_id:  76%|███████▌  | 80233/105539 [09:31<03:00, 140.49it/s]

Обработка ranker_id:  77%|███████▋  | 81644/105539 [09:41<02:50, 140.45it/s]

Обработка ranker_id:  79%|███████▊  | 83055/105539 [09:51<02:39, 140.64it/s]

Обработка ranker_id:  80%|████████  | 84467/105539 [10:01<02:29, 140.79it/s]

Обработка ranker_id:  81%|████████▏ | 85879/105539 [10:11<02:19, 140.61it/s]

Обработка ranker_id:  83%|████████▎ | 87284/105539 [10:21<02:09, 140.56it/s]

Обработка ranker_id:  84%|████████▍ | 88689/105539 [10:31<01:59, 140.51it/s]

Обработка ranker_id:  85%|████████▌ | 90096/105539 [10:41<01:49, 140.56it/s]

Обработка ranker_id:  87%|████████▋ | 91503/105539 [10:51<01:40, 140.20it/s]

Обработка ranker_id:  88%|████████▊ | 92915/105539 [11:01<01:29, 140.48it/s]

Обработка ranker_id:  89%|████████▉ | 94327/105539 [11:11<01:19, 140.34it/s]

Обработка ranker_id:  91%|█████████ | 95748/105539 [11:21<01:09, 140.86it/s]

Обработка ranker_id:  92%|█████████▏| 97169/105539 [11:31<00:59, 140.67it/s]

Обработка ranker_id:  93%|█████████▎| 98572/105539 [11:41<00:49, 140.49it/s]

Обработка ranker_id:  95%|█████████▍| 99973/105539 [11:51<00:39, 140.34it/s]

Обработка ranker_id:  96%|█████████▌| 101379/105539 [12:01<00:29, 140.41it/s]

Обработка ranker_id:  97%|█████████▋| 102785/105539 [12:11<00:19, 140.41it/s]

Обработка ranker_id:  99%|█████████▊| 104192/105539 [12:21<00:09, 140.47it/s]

Обработка ranker_id: 100%|██████████| 105539/105539 [12:31<00:00, 140.43it/s]

[08/25/25 04:57:57] INFO     2025-08-25 04:57:57,061 [INFO]  make_history_avg added:                 ]8;id=771603;file:///tmp/ipykernel_74/99047541.py\99047541.py]8;;\:]8;id=438600;file:///tmp/ipykernel_74/99047541.py#37\37]8;;\

                    INFO     2025-08-25 04:57:57,069 [INFO] new_cols first 10:                     ]8;id=791217;file:///tmp/ipykernel_74/4113492531.py\4113492531.py]8;;\:]8;id=410202;file:///tmp/ipykernel_74/4113492531.py#16\16]8;;\
                             ['time_legs0_departureAt_hour_company_mean',
                             'time_legs0_departureAt_hour_company_std',
                             'time_legs0_departureAt_hour_company_count',
                             'time_legs0_departureAt_hour_company_median',
                             'time_legs0_departureAt_hour_company_q25',
                             'time_legs0_departureAt_hour_company_q75',
                             'time_legs1_departureAt_hour_company_mean',
                             'time_legs1_departureAt_hour_company_std',
                             'time_legs1_departureAt_hour_company_count',
                             'time_legs1_departureAt_hour_company_median']

                    INFO     2025-08-25 04:57:57,075 [INFO] new_cols last 10:                      ]8;id=116234;file:///tmp/ipykernel_74/4113492531.py\4113492531.py]8;;\:]8;id=47621;file:///tmp/ipykernel_74/4113492531.py#17\17]8;;\
                             ['miniRules1_statusInfos_company_count',
                             'miniRules1_statusInfos_company_median',
                             'miniRules1_statusInfos_company_q25',
                             'miniRules1_statusInfos_company_q75',
                             'miniRules0_statusInfos_company_mean',
                             'miniRules0_statusInfos_company_std',
                             'miniRules0_statusInfos_company_count',
                             'miniRules0_statusInfos_company_median',
                             'miniRules0_statusInfos_company_q25',
                             'miniRules0_statusInfos_company_q75']

                    INFO     2025-08-25 04:57:57,080 [INFO] len(new_cols): 72                      ]8;id=243983;file:///tmp/ipykernel_74/4113492531.py\4113492531.py]8;;\:]8;id=115483;file:///tmp/ipykernel_74/4113492531.py#20\20]8;;\

                    INFO     2025-08-25 04:57:57,085 [INFO]  ################ make_history_avg       ]8;id=765089;file:///tmp/ipykernel_74/99047541.py\99047541.py]8;;\:]8;id=71456;file:///tmp/ipykernel_74/99047541.py#10\10]8;;\
                             elapsed: 755.3964 seconds

[08/25/25 04:57:58] INFO     2025-08-25 04:57:58,278 [INFO]  gen_feats added:                        ]8;id=841797;file:///tmp/ipykernel_74/99047541.py\99047541.py]8;;\:]8;id=518405;file:///tmp/ipykernel_74/99047541.py#37\37]8;;\

                    INFO     2025-08-25 04:57:58,284 [INFO] new_cols first 10: ['group_size',      ]8;id=770220;file:///tmp/ipykernel_74/4113492531.py\4113492531.py]8;;\:]8;id=698016;file:///tmp/ipykernel_74/4113492531.py#16\16]8;;\
                             'ff_- ЮТэйр ЗАО', 'ff_2G', 'ff_5N', 'ff_6R', 'ff_6W', 'ff_9W',
                             'ff_9X', 'ff_A3', 'ff_A4']

                    INFO     2025-08-25 04:57:58,290 [INFO] new_cols last 10:                      ]8;id=108681;file:///tmp/ipykernel_74/4113492531.py\4113492531.py]8;;\:]8;id=35421;file:///tmp/ipykernel_74/4113492531.py#17\17]8;;\
                             ['miniRules1_statusInfos_company_count',
                             'miniRules1_statusInfos_company_median',
                             'miniRules1_statusInfos_company_q25',
                             'miniRules1_statusInfos_company_q75',
                             'miniRules0_statusInfos_company_mean',
                             'miniRules0_statusInfos_company_std',
                             'miniRules0_statusInfos_company_count',
                             'miniRules0_statusInfos_company_median',
                             'miniRules0_statusInfos_company_q25',
                             'miniRules0_statusInfos_company_q75']

                    INFO     2025-08-25 04:57:58,296 [INFO] len(new_cols): 569                     ]8;id=371931;file:///tmp/ipykernel_74/4113492531.py\4113492531.py]8;;\:]8;id=440040;file:///tmp/ipykernel_74/4113492531.py#20\20]8;;\

                    INFO     2025-08-25 04:57:58,300 [INFO]  ################ gen_feats elapsed:     ]8;id=283894;file:///tmp/ipykernel_74/99047541.py\99047541.py]8;;\:]8;id=538615;file:///tmp/ipykernel_74/99047541.py#10\10]8;;\
                             1726.3089 seconds

                    INFO     2025-08-25 04:57:58,316 [INFO]  ---------------- smart_fillnull start    ]8;id=810337;file:///tmp/ipykernel_74/99047541.py\99047541.py]8;;\:]8;id=467604;file:///tmp/ipykernel_74/99047541.py#6\6]8;;\

[08/25/25 04:58:01] INFO     2025-08-25 04:58:01,567 [INFO]  ################ smart_fillnull         ]8;id=917594;file:///tmp/ipykernel_74/99047541.py\99047541.py]8;;\:]8;id=370650;file:///tmp/ipykernel_74/99047541.py#10\10]8;;\
                             elapsed: 3.2457 seconds

                    INFO     2025-08-25 04:58:01,577 [INFO]  ---------------- encode_cat_unified      ]8;id=834390;file:///tmp/ipykernel_74/99047541.py\99047541.py]8;;\:]8;id=560851;file:///tmp/ipykernel_74/99047541.py#6\6]8;;\
                             start

                    INFO     2025-08-25 04:58:01,583 [INFO]  ---------------- encode_unified_cats     ]8;id=976836;file:///tmp/ipykernel_74/99047541.py\99047541.py]8;;\:]8;id=477776;file:///tmp/ipykernel_74/99047541.py#6\6]8;;\
                             start

encode_unified_cats:   0%|          | 0/8 [00:00<?, ?it/s]

encode_unified_cats:  12%|█▎        | 1/8 [01:44<12:09, 104.24s/it]

encode_unified_cats:  25%|██▌       | 2/8 [02:34<07:14, 72.41s/it]

encode_unified_cats:  38%|███▊      | 3/8 [03:16<04:53, 58.66s/it]

encode_unified_cats:  50%|█████     | 4/8 [03:59<03:28, 52.23s/it]

encode_unified_cats:  62%|██████▎   | 5/8 [04:41<02:25, 48.55s/it]

encode_unified_cats:  75%|███████▌  | 6/8 [05:28<01:36, 48.33s/it]

encode_unified_cats:  88%|████████▊ | 7/8 [05:47<00:38, 38.56s/it]

encode_unified_cats: 100%|██████████| 8/8 [05:47<00:00, 43.43s/it]

[08/25/25 05:03:50] INFO     2025-08-25 05:03:50,351 [INFO]  ################ encode_unified_cats    ]8;id=784075;file:///tmp/ipykernel_74/99047541.py\99047541.py]8;;\:]8;id=907790;file:///tmp/ipykernel_74/99047541.py#10\10]8;;\
                             elapsed: 348.7633 seconds

                    INFO     2025-08-25 05:03:50,356 [INFO]  ---------------- encode_cat start        ]8;id=706135;file:///tmp/ipykernel_74/99047541.py\99047541.py]8;;\:]8;id=203973;file:///tmp/ipykernel_74/99047541.py#6\6]8;;\

                    INFO     2025-08-25 05:03:50,361 [INFO]  ---------------- encode_cat_bycount      ]8;id=750884;file:///tmp/ipykernel_74/99047541.py\99047541.py]8;;\:]8;id=365071;file:///tmp/ipykernel_74/99047541.py#6\6]8;;\
                             start

encode_cat_bycount:   0%|          | 0/5 [00:00<?, ?it/s]

encode_cat_bycount:  20%|██        | 1/5 [00:03<00:14,  3.63s/it]

encode_cat_bycount:  40%|████      | 2/5 [00:06<00:10,  3.42s/it]

encode_cat_bycount:  60%|██████    | 3/5 [00:10<00:06,  3.36s/it]

encode_cat_bycount:  80%|████████  | 4/5 [00:13<00:03,  3.20s/it]

encode_cat_bycount: 100%|██████████| 5/5 [00:16<00:00,  3.18s/it]

encode_cat_bycount: 100%|██████████| 5/5 [00:16<00:00,  3.26s/it]

[08/25/25 05:04:06] INFO     2025-08-25 05:04:06,675 [INFO]  ################ encode_cat_bycount     ]8;id=122027;file:///tmp/ipykernel_74/99047541.py\99047541.py]8;;\:]8;id=85940;file:///tmp/ipykernel_74/99047541.py#10\10]8;;\
                             elapsed: 16.3094 seconds

                    INFO     2025-08-25 05:04:06,680 [INFO]  ################ encode_cat elapsed:    ]8;id=302587;file:///tmp/ipykernel_74/99047541.py\99047541.py]8;;\:]8;id=982975;file:///tmp/ipykernel_74/99047541.py#10\10]8;;\
                             16.3185 seconds

                    INFO     2025-08-25 05:04:06,685 [INFO]  ################ encode_cat_unified     ]8;id=448498;file:///tmp/ipykernel_74/99047541.py\99047541.py]8;;\:]8;id=716979;file:///tmp/ipykernel_74/99047541.py#10\10]8;;\
                             elapsed: 365.1023 seconds

                    INFO     2025-08-25 05:04:06,717 [INFO] cats.keys():                            ]8;id=554299;file:///usr/local/lib/python3.10/site-packages/icecream/icecream.py\icecream.py]8;;\:]8;id=394017;file:///usr/local/lib/python3.10/site-packages/icecream/icecream.py#185\185]8;;\
                             odict_keys(['airport_iata', 'airport_city_iata',
                             'marketingCarrier_code', 'operatingCarrier_code', 'aircraft_code',
                             'flightNumber', 'searchRoute', 'companyID', 'corporateTariffCode',
                             'nationality', 'profileId', 'ff_primary'])

[08/25/25 05:04:12] INFO     2025-08-25 05:04:12,088 [INFO] numer_cols first 10: ['isAccess3D',    ]8;id=856813;file:///tmp/ipykernel_74/4113492531.py\4113492531.py]8;;\:]8;id=551450;file:///tmp/ipykernel_74/4113492531.py#16\16]8;;\
                             'isVip', 'legs0_duration',
                             'legs0_segments0_baggageAllowance_weightMeasurementType',
                             'legs0_segments0_cabinClass', 'legs0_segments0_duration',
                             'legs0_segments0_seatsAvailable',
                             'legs0_segments1_baggageAllowance_weightMeasurementType',
                             'legs0_segments1_cabinClass', 'legs0_segments1_duration']

                    INFO     2025-08-25 05:04:12,096 [INFO] numer_cols last 10:                    ]8;id=728324;file:///tmp/ipykernel_74/4113492531.py\4113492531.py]8;;\:]8;id=227315;file:///tmp/ipykernel_74/4113492531.py#17\17]8;;\
                             ['legs1_segments3_flightNumber',
                             'legs1_segments3_marketingCarrier_code',
                             'legs1_segments3_operatingCarrier_code', 'profileId', 'searchRoute',
                             'ff_primary', 'base_searchRoute', 'normed_searchRoute',
                             'legs0_arrival_airport_iata', 'legs1_arrival_airport_iata']

                    INFO     2025-08-25 05:04:12,102 [INFO] len(numer_cols): 667                   ]8;id=269250;file:///tmp/ipykernel_74/4113492531.py\4113492531.py]8;;\:]8;id=934398;file:///tmp/ipykernel_74/4113492531.py#20\20]8;;\

                    INFO     2025-08-25 05:04:12,107 [INFO] cat_cols: []                           ]8;id=15140;file:///tmp/ipykernel_74/4113492531.py\4113492531.py]8;;\:]8;id=888041;file:///tmp/ipykernel_74/4113492531.py#19\19]8;;\

                    INFO     2025-08-25 05:04:12,111 [INFO] len(cat_cols): 0                       ]8;id=259834;file:///tmp/ipykernel_74/4113492531.py\4113492531.py]8;;\:]8;id=95763;file:///tmp/ipykernel_74/4113492531.py#20\20]8;;\

shape: (25_043_148, 690)
┌──────────┬────────┬───────────┬────────────┬───┬────────────┬────────────┬───────────┬───────────┐
│ Id       ┆ bySelf ┆ companyID ┆ corporateT ┆ … ┆ miniRules0 ┆ miniRules0 ┆ miniRules ┆ miniRules │
│ ---      ┆ ---    ┆ ---       ┆ ariffCode  ┆   ┆ _statusInf ┆ _statusInf ┆ 0_statusI ┆ 0_statusI │
│ i64      ┆ i8     ┆ i64       ┆ ---        ┆   ┆ os_company ┆ os_company ┆ nfos_comp ┆ nfos_comp │
│          ┆        ┆           ┆ i64        ┆   ┆ …          ┆ …          ┆ any…      ┆ any…      │
│          ┆        ┆           ┆            ┆   ┆ ---        ┆ ---        ┆ ---       ┆ ---       │
│          ┆        ┆           ┆            ┆   ┆ i32        ┆ f32        ┆ f32       ┆ f32       │
╞══════════╪════════╪═══════════╪════════════╪═══╪════════════╪════════════╪═══════════╪═══════════╡
│ 0        ┆ 1      ┆ 16        ┆ 0          ┆ … ┆ 0          ┆ -1.0       ┆ -1.0      ┆ -1.0      │
│ 1        ┆ 1      ┆ 16        ┆ 42         ┆ … ┆ 0          ┆ -1.0       ┆ -1.0      ┆ -1.0      │
│ 2        ┆ 1      ┆ 16        ┆ 0          ┆ … ┆ 0          ┆ -1.0       ┆ -1.0      ┆ -1.0      │
│ 3        ┆ 1      ┆ 16        ┆ 42         ┆ … ┆ 0          ┆ -1.0       ┆ -1.0      ┆ -1.0      │
│ 4        ┆ 1      ┆ 16        ┆ 0          ┆ … ┆ 0          ┆ -1.0       ┆ -1.0      ┆ -1.0      │
│ …        ┆ …      ┆ …         ┆ …          ┆ … ┆ …          ┆ …          ┆ …         ┆ …         │
│ 25043143 ┆ 0      ┆ 188       ┆ 92         ┆ … ┆ 375        ┆ 1.0        ┆ 1.0       ┆ 1.0       │
│ 25043144 ┆ 0      ┆ 188       ┆ 92         ┆ … ┆ 375        ┆ 1.0        ┆ 1.0       ┆ 1.0       │
│ 25043145 ┆ 0      ┆ 188       ┆ 92         ┆ … ┆ 375        ┆ 1.0        ┆ 1.0       ┆ 1.0       │
│ 25043146 ┆ 0      ┆ 188       ┆ 92         ┆ … ┆ 375        ┆ 1.0        ┆ 1.0       ┆ 1.0       │
│ 25043147 ┆ 0      ┆ 188       ┆ 92         ┆ … ┆ 375        ┆ 1.0        ┆ 1.0       ┆ 1.0       │
└──────────┴────────┴───────────┴────────────┴───┴────────────┴────────────┴───────────┴───────────┘

In [30]:
def preprocess_cat_cols(df, cat_cols):
  if not cat_cols:
    return df
  
  for col in cat_cols:
    df[col] = df[col].astype('category')
  return df

def get_num_boost_round(params):
  if FLAGS.fast:
    return 100
  if FLAGS.trees:
    return FLAGS.trees
  if 'iterations' in params:
    return params['iterations']
  if 'num_iterations' in params:
    return params['num_iterations']
  if 'n_estimators' in params:
    return params['n_estimators']

In [31]:
cat_cols = cols_dict['cat']
feat_cols = cols_dict['feat']
df_train, df_valid = get_train_valid(df)  
df_test = get_test(df)

if FLAGS.mode == 'train':
  X_train = df_train.to_pandas()
  X_train = X_train[feat_cols]
  X_train = preprocess_cat_cols(X_train, cat_cols)
  
  y_train = df_train['selected'].to_pandas()
  group = df_train.select('ranker_id').group_by('ranker_id', maintain_order=True).agg(pl.len())['len'].to_numpy()
  ic(X_train.shape, group.shape)

  X_valid = df_valid.to_pandas()
  X_valid = X_valid[feat_cols]
  X_valid = preprocess_cat_cols(X_valid, cat_cols)

X_test = df_test.to_pandas()
X_test = X_test[feat_cols]
X_test = preprocess_cat_cols(X_test, cat_cols)

In [32]:
import xgboost as xgb
if FLAGS.mode == 'train':
  dtrain = xgb.DMatrix(
    X_train,
    y_train,
    group=group,
    enable_categorical=True)
# dvalid = xgb.DMatrix(X_valid, enable_categorical=True)
# dtest = xgb.DMatrix(X_test, enable_categorical=True)

In [33]:
def show_feat_importance(model):
  imp = model.get_score(importance_type="gain")

  imp_df = (
    pd.DataFrame({
      "feat": list(imp.keys()), 
      "importance": list(imp.values())
      })
    .sort_values("importance", ascending=False)
    .reset_index(drop=True)
  )
  return imp_df

In [34]:
class XGBTQDMCallback(xgb.callback.TrainingCallback):

  def __init__(self, total_iterations, desc='', eval_name='valid'):
    self.pbar = tqdm(total=total_iterations, desc=desc)
    self.eval_name = eval_name

  def after_iteration(self, model, epoch, evals_log):
    self.pbar.update(1)
    for eval_name, metrics in evals_log.items():
      if eval_name == self.eval_name:
        m = {}
        for metric_name, values in metrics.items():
          m.update({metric_name: values[-1]})
        self.pbar.set_postfix(m)

    if epoch + 1 == self.pbar.total:
      self.pbar.close()

    return False

In [35]:
def batch_predict(model, X, batch_size=50_000, proba=False, inplace=False, progress=True):
  results = []
  n = len(X)
  iterator = range(0, n, batch_size)
  if progress:
    iterator = tqdm(iterator, desc="Batch Prediction")

  for start in iterator:
    end = min(start + batch_size, n)
    batch = X[start:end]

    if inplace and hasattr(model, "inplace_predict"):
      batch_pred = model.inplace_predict(batch)
    elif proba and hasattr(model, "predict_proba"):
      batch_pred = model.predict_proba(batch)
    else:
      batch_pred = model.predict(batch)

    results.append(batch_pred)

  first = results[0]
  if isinstance(first, np.ndarray):
    if first.ndim == 1:
      return np.concatenate(results)
    else:
      return np.vstack(results)
  else:
    return [item for sublist in results for item in sublist]

In [36]:
models = []
preds = []

In [37]:
params = params_xgb.copy()
objectives = [
  'rank:ndcg',
  'rank:map',
  'rank:pairwise',
  'binary:logistic'
]
if FLAGS.n_models > 0:
  objectives = objectives[:FLAGS.n_models]
params['device'] = FLAGS.device
# params['predictor'] = 'cpu_predictor'
ic(params)

[08/25/25 05:05:29] INFO     2025-08-25 05:05:29,847 [INFO] params: {'colsample_bytree': 0.8,       ]8;id=687516;file:///usr/local/lib/python3.10/site-packages/icecream/icecream.py\icecream.py]8;;\:]8;id=6487;file:///usr/local/lib/python3.10/site-packages/icecream/icecream.py#185\185]8;;\
                                      'device': 'gpu',
                                      'eval_metric': 'ndcg@3',
                                      'lambda': 100,
                                      'learning_rate': 0.05,
                                      'max_depth': 12,
                                      'min_child_weight': 10,
                                      'n_estimators': 1000,
                                      'objective': 'rank:ndcg',
                                      'seed': 42,
                                      'subsample': 0.8}

{'objective': 'rank:ndcg',
 'eval_metric': 'ndcg@3',
 'max_depth': 12,
 'min_child_weight': 10,
 'subsample': 0.8,
 'colsample_bytree': 0.8,
 'lambda': 100,
 'learning_rate': 0.05,
 'n_estimators': 1000,
 'seed': 42,
 'device': 'gpu'}

# XGB training

In [38]:
if FLAGS.mode == 'train':
  for objective in tqdm(objectives, desc='objectives'):
    params['objective'] = objective
    model = xgb.train(
              params=params,
              dtrain=dtrain,
              num_boost_round=get_num_boost_round(params),
              evals=None,
              callbacks=[XGBTQDMCallback(get_num_boost_round(params), f'xgb_train_{objective}')],
              verbose_eval=100,
          )
    model.set_param({"device": "cpu"}) 
    # pred = model.predict(dvalid)
    # pred = model.inplace_predict(X_valid)
    pred = batch_predict(model, X_valid, inplace=True)
    ic(objective, pred)
    preds.append(pred)
    ic(objective)
    display(show_feat_importance(model))
    models.append(model)

In [39]:
def hitrate_at_3(y_true, y_pred, groups):
  df = pl.DataFrame({'group': groups, 'pred': y_pred, 'true': y_true})

  return (df.filter(pl.col("group").count().over("group") > 10).sort(
      ["group", "pred"], descending=[False, True]).group_by(
          "group", maintain_order=True).head(3).group_by("group").agg(
              pl.col("true").max()).select(pl.col("true").mean()).item())
  
def eval_df(df):
  score = hitrate_at_3(
      df['selected'].to_numpy(),
      df['pred'].to_numpy(),
      df['ranker_id'].to_numpy()
  )
  return score

In [40]:
def rerank(df: pl.DataFrame, penalty_factor=0.12):
  df = df.with_columns(
      pl.max("pred").over(["ranker_id", "flight_hash"]).alias("max_score_same_flight"))

  df = df.with_columns((pl.col("pred") - penalty_factor * (pl.col("max_score_same_flight") - pl.col("pred"))).alias("pred"))

  return df

# XGB eval

In [41]:
for objective, pred in zip(objectives, preds):
  df_valid = df_valid.with_columns(
    pl.Series("pred", pred)
  )
  score = eval_df(df_valid)
  ic(objective, score)

In [42]:
def ensemble(preds):
  preds = np.array(preds)
  i = 0
  for pred in preds:
    ic(pred.shape)
    min_val = pred.min()
    max_val = pred.max()
    if not (min_val >= 0 and max_val <= 1):
      pred = 1 / (1 + np.exp(-pred))
    preds[i] = pred
    i += 1
  pred = preds.mean(0)
  return pred

In [43]:
if FLAGS.mode == 'train':
  for i, model in tqdm(enumerate(models), total=len(models)):
    with open(f'{FLAGS.out_dir}/{i}.pkl', 'wb') as f:
      pickle.dump(model, f)

# XGB load pretrain model

In [44]:
if FLAGS.mode != 'train':
  models = []
  preds = []
  model_dir = FLAGS.model_dir if os.path.exists(FLAGS.model_dir) else FLAGS.out_dir
  for i, objective in tqdm(enumerate(objectives), total=len(objectives)):
    with open(f'{model_dir}/{i}.pkl', 'rb') as f:
      model = pickle.load(f)
      models.append(model)
      #preds.append(model.inplace_predict(X_valid))

  0%|          | 0/4 [00:00<?, ?it/s]

/tmp/ipykernel_74/2123753009.py:7: UserWarning: [05:05:32] WARNING: /workspace/src/collective/../data/../common/error_msg.h:82: If you are loading a serialized model (like pickle in Python, RDS in R) or
configuration generated by an older version of XGBoost, please export the model by calling
`Booster.save_model` from that version first, then load it back in current version. See:

    https://xgboost.readthedocs.io/en/stable/tutorials/saving_model.html

for more details about differences between saving model and serializing.

  model = pickle.load(f)

 25%|██▌       | 1/4 [00:01<00:03,  1.31s/it]

 50%|█████     | 2/4 [00:02<00:02,  1.19s/it]

 75%|███████▌  | 3/4 [00:03<00:01,  1.09s/it]

100%|██████████| 4/4 [00:03<00:00,  1.13it/s]

100%|██████████| 4/4 [00:03<00:00,  1.01it/s]

In [45]:
if preds:
  pred = ensemble(preds)
  ic(pred, pred.shape)
  df_valid = df_valid.with_columns(
    pl.Series("pred", pred)
  )
  score = eval_df(df_valid)
  ic('ori', score)
  df_valid = df_valid.with_columns(
    pl.Series("pred", pred)
  )
  df_valid = rerank(df_valid)
  score = eval_df(df_valid)
  ic('rerank', score)

# Dump result of 4 xgb models ensemble to submission.parquet

In [46]:
preds = []
for model in tqdm(models):
  # pred = model.predict(dtest)
  # pred = model.inplace_predict(X_test)
  pred = batch_predict(model, X_test, inplace=True)
  preds.append(pred)
  
pred = ensemble(preds)
pred

  0%|          | 0/4 [00:00<?, ?it/s]

Batch Prediction:   0%|          | 0/138 [00:00<?, ?it/s]

Batch Prediction:   1%|          | 1/138 [00:00<00:45,  3.02it/s]

Batch Prediction:   1%|▏         | 2/138 [00:00<00:38,  3.50it/s]

Batch Prediction:   2%|▏         | 3/138 [00:00<00:37,  3.63it/s]

Batch Prediction:   3%|▎         | 4/138 [00:01<00:36,  3.64it/s]

Batch Prediction:   4%|▎         | 5/138 [00:01<00:45,  2.93it/s]

Batch Prediction:   4%|▍         | 6/138 [00:01<00:42,  3.14it/s]

Batch Prediction:   5%|▌         | 7/138 [00:02<00:39,  3.31it/s]

Batch Prediction:   6%|▌         | 8/138 [00:02<00:37,  3.48it/s]

Batch Prediction:   7%|▋         | 9/138 [00:02<00:35,  3.58it/s]

Batch Prediction:   7%|▋         | 10/138 [00:02<00:35,  3.65it/s]

Batch Prediction:   8%|▊         | 11/138 [00:03<00:34,  3.70it/s]

Batch Prediction:   9%|▊         | 12/138 [00:03<00:35,  3.59it/s]

Batch Prediction:   9%|▉         | 13/138 [00:03<00:42,  2.92it/s]

Batch Prediction:  10%|█         | 14/138 [00:04<00:39,  3.13it/s]

Batch Prediction:  11%|█         | 15/138 [00:04<00:36,  3.33it/s]

Batch Prediction:  12%|█▏        | 16/138 [00:04<00:34,  3.50it/s]

Batch Prediction:  12%|█▏        | 17/138 [00:05<00:34,  3.52it/s]

Batch Prediction:  13%|█▎        | 18/138 [00:05<00:33,  3.62it/s]

Batch Prediction:  14%|█▍        | 19/138 [00:05<00:32,  3.69it/s]

Batch Prediction:  14%|█▍        | 20/138 [00:05<00:36,  3.22it/s]

Batch Prediction:  15%|█▌        | 21/138 [00:06<00:31,  3.74it/s]

Batch Prediction:  16%|█▌        | 22/138 [00:06<00:27,  4.22it/s]

Batch Prediction:  17%|█▋        | 23/138 [00:06<00:24,  4.61it/s]

Batch Prediction:  17%|█▋        | 24/138 [00:06<00:22,  4.98it/s]

Batch Prediction:  18%|█▊        | 25/138 [00:06<00:21,  5.22it/s]

Batch Prediction:  19%|█▉        | 26/138 [00:06<00:20,  5.35it/s]

Batch Prediction:  20%|█▉        | 27/138 [00:07<00:19,  5.56it/s]

Batch Prediction:  20%|██        | 28/138 [00:07<00:21,  5.01it/s]

Batch Prediction:  21%|██        | 29/138 [00:07<00:20,  5.27it/s]

Batch Prediction:  22%|██▏       | 30/138 [00:07<00:19,  5.47it/s]

Batch Prediction:  22%|██▏       | 31/138 [00:07<00:19,  5.63it/s]

Batch Prediction:  23%|██▎       | 32/138 [00:08<00:18,  5.73it/s]

Batch Prediction:  24%|██▍       | 33/138 [00:08<00:19,  5.50it/s]

Batch Prediction:  25%|██▍       | 34/138 [00:08<00:18,  5.66it/s]

Batch Prediction:  25%|██▌       | 35/138 [00:08<00:18,  5.70it/s]

Batch Prediction:  26%|██▌       | 36/138 [00:08<00:21,  4.76it/s]

Batch Prediction:  27%|██▋       | 37/138 [00:09<00:20,  5.01it/s]

Batch Prediction:  28%|██▊       | 38/138 [00:09<00:19,  5.20it/s]

Batch Prediction:  28%|██▊       | 39/138 [00:09<00:19,  5.20it/s]

Batch Prediction:  29%|██▉       | 40/138 [00:09<00:18,  5.16it/s]

Batch Prediction:  30%|██▉       | 41/138 [00:09<00:19,  5.07it/s]

Batch Prediction:  30%|███       | 42/138 [00:09<00:19,  5.05it/s]

Batch Prediction:  31%|███       | 43/138 [00:10<00:18,  5.01it/s]

Batch Prediction:  32%|███▏      | 44/138 [00:10<00:20,  4.53it/s]

Batch Prediction:  33%|███▎      | 45/138 [00:10<00:18,  4.93it/s]

Batch Prediction:  33%|███▎      | 46/138 [00:10<00:18,  5.01it/s]

Batch Prediction:  34%|███▍      | 47/138 [00:10<00:17,  5.25it/s]

Batch Prediction:  35%|███▍      | 48/138 [00:11<00:16,  5.45it/s]

Batch Prediction:  36%|███▌      | 49/138 [00:11<00:16,  5.47it/s]

Batch Prediction:  36%|███▌      | 50/138 [00:11<00:16,  5.31it/s]

Batch Prediction:  37%|███▋      | 51/138 [00:11<00:16,  5.24it/s]

Batch Prediction:  38%|███▊      | 52/138 [00:12<00:18,  4.65it/s]

Batch Prediction:  38%|███▊      | 53/138 [00:12<00:17,  4.95it/s]

Batch Prediction:  39%|███▉      | 54/138 [00:12<00:16,  5.18it/s]

Batch Prediction:  40%|███▉      | 55/138 [00:12<00:15,  5.39it/s]

Batch Prediction:  41%|████      | 56/138 [00:12<00:14,  5.53it/s]

Batch Prediction:  41%|████▏     | 57/138 [00:12<00:14,  5.61it/s]

Batch Prediction:  42%|████▏     | 58/138 [00:13<00:14,  5.37it/s]

Batch Prediction:  43%|████▎     | 59/138 [00:13<00:14,  5.30it/s]

Batch Prediction:  43%|████▎     | 60/138 [00:13<00:16,  4.85it/s]

Batch Prediction:  44%|████▍     | 61/138 [00:13<00:14,  5.14it/s]

Batch Prediction:  45%|████▍     | 62/138 [00:13<00:14,  5.39it/s]

Batch Prediction:  46%|████▌     | 63/138 [00:14<00:13,  5.57it/s]

Batch Prediction:  46%|████▋     | 64/138 [00:14<00:12,  5.72it/s]

Batch Prediction:  47%|████▋     | 65/138 [00:14<00:12,  5.79it/s]

Batch Prediction:  48%|████▊     | 66/138 [00:14<00:12,  5.84it/s]

Batch Prediction:  49%|████▊     | 67/138 [00:14<00:12,  5.90it/s]

Batch Prediction:  49%|████▉     | 68/138 [00:14<00:13,  5.16it/s]

Batch Prediction:  50%|█████     | 69/138 [00:15<00:13,  5.31it/s]

Batch Prediction:  51%|█████     | 70/138 [00:15<00:12,  5.45it/s]

Batch Prediction:  51%|█████▏    | 71/138 [00:15<00:12,  5.55it/s]

Batch Prediction:  52%|█████▏    | 72/138 [00:15<00:11,  5.64it/s]

Batch Prediction:  53%|█████▎    | 73/138 [00:15<00:12,  5.35it/s]

Batch Prediction:  54%|█████▎    | 74/138 [00:16<00:12,  5.11it/s]

Batch Prediction:  54%|█████▍    | 75/138 [00:16<00:13,  4.70it/s]

Batch Prediction:  55%|█████▌    | 76/138 [00:16<00:12,  4.84it/s]

Batch Prediction:  56%|█████▌    | 77/138 [00:16<00:11,  5.10it/s]

Batch Prediction:  57%|█████▋    | 78/138 [00:16<00:11,  5.14it/s]

Batch Prediction:  57%|█████▋    | 79/138 [00:17<00:11,  5.35it/s]

Batch Prediction:  58%|█████▊    | 80/138 [00:17<00:10,  5.52it/s]

Batch Prediction:  59%|█████▊    | 81/138 [00:17<00:10,  5.61it/s]

Batch Prediction:  59%|█████▉    | 82/138 [00:17<00:10,  5.23it/s]

Batch Prediction:  60%|██████    | 83/138 [00:17<00:12,  4.55it/s]

Batch Prediction:  61%|██████    | 84/138 [00:18<00:11,  4.88it/s]

Batch Prediction:  62%|██████▏   | 85/138 [00:18<00:10,  5.15it/s]

Batch Prediction:  62%|██████▏   | 86/138 [00:18<00:09,  5.27it/s]

Batch Prediction:  63%|██████▎   | 87/138 [00:18<00:09,  5.11it/s]

Batch Prediction:  64%|██████▍   | 88/138 [00:18<00:09,  5.11it/s]

Batch Prediction:  64%|██████▍   | 89/138 [00:18<00:09,  5.05it/s]

Batch Prediction:  65%|██████▌   | 90/138 [00:19<00:09,  5.05it/s]

Batch Prediction:  66%|██████▌   | 91/138 [00:19<00:10,  4.40it/s]

Batch Prediction:  67%|██████▋   | 92/138 [00:19<00:09,  4.75it/s]

Batch Prediction:  67%|██████▋   | 93/138 [00:19<00:08,  5.03it/s]

Batch Prediction:  68%|██████▊   | 94/138 [00:19<00:08,  5.20it/s]

Batch Prediction:  69%|██████▉   | 95/138 [00:20<00:08,  5.19it/s]

Batch Prediction:  70%|██████▉   | 96/138 [00:20<00:08,  5.10it/s]

Batch Prediction:  70%|███████   | 97/138 [00:20<00:07,  5.23it/s]

Batch Prediction:  71%|███████   | 98/138 [00:20<00:07,  5.26it/s]

Batch Prediction:  72%|███████▏  | 99/138 [00:21<00:08,  4.57it/s]

Batch Prediction:  72%|███████▏  | 100/138 [00:21<00:07,  4.90it/s]

Batch Prediction:  73%|███████▎  | 101/138 [00:21<00:07,  5.15it/s]

Batch Prediction:  74%|███████▍  | 102/138 [00:21<00:06,  5.24it/s]

Batch Prediction:  75%|███████▍  | 103/138 [00:21<00:06,  5.29it/s]

Batch Prediction:  75%|███████▌  | 104/138 [00:21<00:06,  5.25it/s]

Batch Prediction:  76%|███████▌  | 105/138 [00:22<00:06,  5.38it/s]

Batch Prediction:  77%|███████▋  | 106/138 [00:22<00:05,  5.47it/s]

Batch Prediction:  78%|███████▊  | 107/138 [00:22<00:06,  4.50it/s]

Batch Prediction:  78%|███████▊  | 108/138 [00:22<00:06,  4.65it/s]

Batch Prediction:  79%|███████▉  | 109/138 [00:23<00:06,  4.62it/s]

Batch Prediction:  80%|███████▉  | 110/138 [00:23<00:05,  4.86it/s]

Batch Prediction:  80%|████████  | 111/138 [00:23<00:05,  5.16it/s]

Batch Prediction:  81%|████████  | 112/138 [00:23<00:04,  5.40it/s]

Batch Prediction:  82%|████████▏ | 113/138 [00:23<00:04,  5.47it/s]

Batch Prediction:  83%|████████▎ | 114/138 [00:23<00:04,  4.86it/s]

Batch Prediction:  83%|████████▎ | 115/138 [00:24<00:04,  5.15it/s]

Batch Prediction:  84%|████████▍ | 116/138 [00:24<00:04,  5.23it/s]

Batch Prediction:  85%|████████▍ | 117/138 [00:24<00:03,  5.40it/s]

Batch Prediction:  86%|████████▌ | 118/138 [00:24<00:03,  5.56it/s]

Batch Prediction:  86%|████████▌ | 119/138 [00:24<00:03,  5.66it/s]

Batch Prediction:  87%|████████▋ | 120/138 [00:25<00:03,  5.71it/s]

Batch Prediction:  88%|████████▊ | 121/138 [00:25<00:02,  5.76it/s]

Batch Prediction:  88%|████████▊ | 122/138 [00:25<00:03,  4.82it/s]

Batch Prediction:  89%|████████▉ | 123/138 [00:25<00:02,  5.13it/s]

Batch Prediction:  90%|████████▉ | 124/138 [00:25<00:02,  5.15it/s]

Batch Prediction:  91%|█████████ | 125/138 [00:26<00:02,  5.18it/s]

Batch Prediction:  91%|█████████▏| 126/138 [00:26<00:02,  5.27it/s]

Batch Prediction:  92%|█████████▏| 127/138 [00:26<00:02,  5.28it/s]

Batch Prediction:  93%|█████████▎| 128/138 [00:26<00:01,  5.26it/s]

Batch Prediction:  93%|█████████▎| 129/138 [00:26<00:01,  5.18it/s]

Batch Prediction:  94%|█████████▍| 130/138 [00:27<00:01,  4.51it/s]

Batch Prediction:  95%|█████████▍| 131/138 [00:27<00:01,  4.71it/s]

Batch Prediction:  96%|█████████▌| 132/138 [00:27<00:01,  4.95it/s]

Batch Prediction:  96%|█████████▋| 133/138 [00:27<00:00,  5.08it/s]

Batch Prediction:  97%|█████████▋| 134/138 [00:27<00:00,  5.29it/s]

Batch Prediction:  98%|█████████▊| 135/138 [00:27<00:00,  5.27it/s]

Batch Prediction:  99%|█████████▊| 136/138 [00:28<00:00,  5.41it/s]

Batch Prediction:  99%|█████████▉| 137/138 [00:28<00:00,  5.56it/s]

Batch Prediction: 100%|██████████| 138/138 [00:28<00:00,  4.73it/s]

Batch Prediction: 100%|██████████| 138/138 [00:28<00:00,  4.82it/s]

 25%|██▌       | 1/4 [00:28<01:25, 28.64s/it]

Batch Prediction:   0%|          | 0/138 [00:00<?, ?it/s]

Batch Prediction:   1%|          | 1/138 [00:00<00:22,  6.07it/s]

Batch Prediction:   1%|▏         | 2/138 [00:00<00:24,  5.45it/s]

Batch Prediction:   2%|▏         | 3/138 [00:00<00:24,  5.53it/s]

Batch Prediction:   3%|▎         | 4/138 [00:00<00:23,  5.61it/s]

Batch Prediction:   4%|▎         | 5/138 [00:00<00:24,  5.43it/s]

Batch Prediction:   4%|▍         | 6/138 [00:01<00:25,  5.19it/s]

Batch Prediction:   5%|▌         | 7/138 [00:01<00:25,  5.19it/s]

Batch Prediction:   6%|▌         | 8/138 [00:01<00:29,  4.46it/s]

Batch Prediction:   7%|▋         | 9/138 [00:01<00:26,  4.85it/s]

Batch Prediction:   7%|▋         | 10/138 [00:01<00:24,  5.14it/s]

Batch Prediction:   8%|▊         | 11/138 [00:02<00:23,  5.35it/s]

Batch Prediction:   9%|▊         | 12/138 [00:02<00:23,  5.43it/s]

Batch Prediction:   9%|▉         | 13/138 [00:02<00:22,  5.45it/s]

Batch Prediction:  10%|█         | 14/138 [00:02<00:22,  5.54it/s]

Batch Prediction:  11%|█         | 15/138 [00:02<00:26,  4.71it/s]

Batch Prediction:  12%|█▏        | 16/138 [00:03<00:25,  4.83it/s]

Batch Prediction:  12%|█▏        | 17/138 [00:03<00:24,  4.98it/s]

Batch Prediction:  13%|█▎        | 18/138 [00:03<00:24,  5.00it/s]

Batch Prediction:  14%|█▍        | 19/138 [00:03<00:22,  5.19it/s]

Batch Prediction:  14%|█▍        | 20/138 [00:03<00:22,  5.28it/s]

Batch Prediction:  15%|█▌        | 21/138 [00:04<00:23,  5.08it/s]

Batch Prediction:  16%|█▌        | 22/138 [00:04<00:21,  5.28it/s]

Batch Prediction:  17%|█▋        | 23/138 [00:04<00:24,  4.61it/s]

Batch Prediction:  17%|█▋        | 24/138 [00:04<00:24,  4.74it/s]

Batch Prediction:  18%|█▊        | 25/138 [00:04<00:23,  4.83it/s]

Batch Prediction:  19%|█▉        | 26/138 [00:05<00:22,  4.94it/s]

Batch Prediction:  20%|█▉        | 27/138 [00:05<00:21,  5.09it/s]

Batch Prediction:  20%|██        | 28/138 [00:05<00:20,  5.28it/s]

Batch Prediction:  21%|██        | 29/138 [00:05<00:19,  5.47it/s]

Batch Prediction:  22%|██▏       | 30/138 [00:05<00:19,  5.47it/s]

Batch Prediction:  22%|██▏       | 31/138 [00:06<00:22,  4.79it/s]

Batch Prediction:  23%|██▎       | 32/138 [00:06<00:22,  4.81it/s]

Batch Prediction:  24%|██▍       | 33/138 [00:06<00:21,  4.91it/s]

Batch Prediction:  25%|██▍       | 34/138 [00:06<00:20,  5.17it/s]

Batch Prediction:  25%|██▌       | 35/138 [00:06<00:19,  5.18it/s]

Batch Prediction:  26%|██▌       | 36/138 [00:07<00:19,  5.19it/s]

Batch Prediction:  27%|██▋       | 37/138 [00:07<00:19,  5.16it/s]

Batch Prediction:  28%|██▊       | 38/138 [00:07<00:19,  5.22it/s]

Batch Prediction:  28%|██▊       | 39/138 [00:07<00:20,  4.77it/s]

Batch Prediction:  29%|██▉       | 40/138 [00:07<00:19,  5.06it/s]

Batch Prediction:  30%|██▉       | 41/138 [00:08<00:18,  5.23it/s]

Batch Prediction:  30%|███       | 42/138 [00:08<00:17,  5.42it/s]

Batch Prediction:  31%|███       | 43/138 [00:08<00:17,  5.54it/s]

Batch Prediction:  32%|███▏      | 44/138 [00:08<00:16,  5.62it/s]

Batch Prediction:  33%|███▎      | 45/138 [00:08<00:16,  5.72it/s]

Batch Prediction:  33%|███▎      | 46/138 [00:08<00:15,  5.77it/s]

Batch Prediction:  34%|███▍      | 47/138 [00:09<00:19,  4.59it/s]

Batch Prediction:  35%|███▍      | 48/138 [00:09<00:18,  4.89it/s]

Batch Prediction:  36%|███▌      | 49/138 [00:09<00:17,  5.00it/s]

Batch Prediction:  36%|███▌      | 50/138 [00:09<00:16,  5.21it/s]

Batch Prediction:  37%|███▋      | 51/138 [00:09<00:16,  5.37it/s]

Batch Prediction:  38%|███▊      | 52/138 [00:10<00:16,  5.28it/s]

Batch Prediction:  38%|███▊      | 53/138 [00:10<00:16,  5.20it/s]

Batch Prediction:  39%|███▉      | 54/138 [00:10<00:16,  5.19it/s]

Batch Prediction:  40%|███▉      | 55/138 [00:10<00:18,  4.44it/s]

Batch Prediction:  41%|████      | 56/138 [00:10<00:17,  4.78it/s]

Batch Prediction:  41%|████▏     | 57/138 [00:11<00:16,  4.91it/s]

Batch Prediction:  42%|████▏     | 58/138 [00:11<00:15,  5.08it/s]

Batch Prediction:  43%|████▎     | 59/138 [00:11<00:14,  5.28it/s]

Batch Prediction:  43%|████▎     | 60/138 [00:11<00:14,  5.46it/s]

Batch Prediction:  44%|████▍     | 61/138 [00:11<00:14,  5.31it/s]

Batch Prediction:  45%|████▍     | 62/138 [00:12<00:14,  5.18it/s]

Batch Prediction:  46%|████▌     | 63/138 [00:12<00:17,  4.35it/s]

Batch Prediction:  46%|████▋     | 64/138 [00:12<00:16,  4.60it/s]

Batch Prediction:  47%|████▋     | 65/138 [00:12<00:15,  4.84it/s]

Batch Prediction:  48%|████▊     | 66/138 [00:12<00:14,  4.99it/s]

Batch Prediction:  49%|████▊     | 67/138 [00:13<00:14,  5.01it/s]

Batch Prediction:  49%|████▉     | 68/138 [00:13<00:13,  5.00it/s]

Batch Prediction:  50%|█████     | 69/138 [00:13<00:13,  4.97it/s]

Batch Prediction:  51%|█████     | 70/138 [00:13<00:13,  4.98it/s]

Batch Prediction:  51%|█████▏    | 71/138 [00:14<00:15,  4.23it/s]

Batch Prediction:  52%|█████▏    | 72/138 [00:14<00:14,  4.53it/s]

Batch Prediction:  53%|█████▎    | 73/138 [00:14<00:13,  4.81it/s]

Batch Prediction:  54%|█████▎    | 74/138 [00:14<00:12,  5.08it/s]

Batch Prediction:  54%|█████▍    | 75/138 [00:14<00:11,  5.30it/s]

Batch Prediction:  55%|█████▌    | 76/138 [00:14<00:11,  5.46it/s]

Batch Prediction:  56%|█████▌    | 77/138 [00:15<00:10,  5.60it/s]

Batch Prediction:  57%|█████▋    | 78/138 [00:15<00:12,  4.71it/s]

Batch Prediction:  57%|█████▋    | 79/138 [00:15<00:11,  5.00it/s]

Batch Prediction:  58%|█████▊    | 80/138 [00:15<00:11,  5.23it/s]

Batch Prediction:  59%|█████▊    | 81/138 [00:15<00:10,  5.24it/s]

Batch Prediction:  59%|█████▉    | 82/138 [00:16<00:10,  5.30it/s]

Batch Prediction:  60%|██████    | 83/138 [00:16<00:10,  5.22it/s]

Batch Prediction:  61%|██████    | 84/138 [00:16<00:10,  5.39it/s]

Batch Prediction:  62%|██████▏   | 85/138 [00:16<00:09,  5.48it/s]

Batch Prediction:  62%|██████▏   | 86/138 [00:16<00:11,  4.46it/s]

Batch Prediction:  63%|██████▎   | 87/138 [00:17<00:10,  4.70it/s]

Batch Prediction:  64%|██████▍   | 88/138 [00:17<00:10,  4.93it/s]

Batch Prediction:  64%|██████▍   | 89/138 [00:17<00:09,  5.15it/s]

Batch Prediction:  65%|██████▌   | 90/138 [00:17<00:08,  5.36it/s]

Batch Prediction:  66%|██████▌   | 91/138 [00:17<00:08,  5.48it/s]

Batch Prediction:  67%|██████▋   | 92/138 [00:18<00:08,  5.56it/s]

Batch Prediction:  67%|██████▋   | 93/138 [00:18<00:07,  5.65it/s]

Batch Prediction:  68%|██████▊   | 94/138 [00:18<00:09,  4.78it/s]

Batch Prediction:  69%|██████▉   | 95/138 [00:18<00:08,  5.02it/s]

Batch Prediction:  70%|██████▉   | 96/138 [00:18<00:08,  5.18it/s]

Batch Prediction:  70%|███████   | 97/138 [00:19<00:07,  5.31it/s]

Batch Prediction:  71%|███████   | 98/138 [00:19<00:07,  5.17it/s]

Batch Prediction:  72%|███████▏  | 99/138 [00:19<00:07,  5.15it/s]

Batch Prediction:  72%|███████▏  | 100/138 [00:19<00:07,  5.09it/s]

Batch Prediction:  73%|███████▎  | 101/138 [00:19<00:07,  5.04it/s]

Batch Prediction:  74%|███████▍  | 102/138 [00:20<00:08,  4.21it/s]

Batch Prediction:  75%|███████▍  | 103/138 [00:20<00:07,  4.47it/s]

Batch Prediction:  75%|███████▌  | 104/138 [00:20<00:07,  4.77it/s]

Batch Prediction:  76%|███████▌  | 105/138 [00:20<00:06,  4.98it/s]

Batch Prediction:  77%|███████▋  | 106/138 [00:20<00:06,  5.08it/s]

Batch Prediction:  78%|███████▊  | 107/138 [00:21<00:05,  5.18it/s]

Batch Prediction:  78%|███████▊  | 108/138 [00:21<00:05,  5.25it/s]

Batch Prediction:  79%|███████▉  | 109/138 [00:21<00:06,  4.54it/s]

Batch Prediction:  80%|███████▉  | 110/138 [00:21<00:05,  4.87it/s]

Batch Prediction:  80%|████████  | 111/138 [00:21<00:05,  5.14it/s]

Batch Prediction:  81%|████████  | 112/138 [00:22<00:04,  5.24it/s]

Batch Prediction:  82%|████████▏ | 113/138 [00:22<00:04,  5.38it/s]

Batch Prediction:  83%|████████▎ | 114/138 [00:22<00:04,  5.49it/s]

Batch Prediction:  83%|████████▎ | 115/138 [00:22<00:04,  5.42it/s]

Batch Prediction:  84%|████████▍ | 116/138 [00:22<00:03,  5.53it/s]

Batch Prediction:  85%|████████▍ | 117/138 [00:23<00:04,  4.50it/s]

Batch Prediction:  86%|████████▌ | 118/138 [00:23<00:04,  4.72it/s]

Batch Prediction:  86%|████████▌ | 119/138 [00:23<00:03,  4.93it/s]

Batch Prediction:  87%|████████▋ | 120/138 [00:23<00:03,  5.03it/s]

Batch Prediction:  88%|████████▊ | 121/138 [00:23<00:03,  4.87it/s]

Batch Prediction:  88%|████████▊ | 122/138 [00:24<00:03,  5.02it/s]

Batch Prediction:  89%|████████▉ | 123/138 [00:24<00:02,  5.16it/s]

Batch Prediction:  90%|████████▉ | 124/138 [00:24<00:02,  5.34it/s]

Batch Prediction:  91%|█████████ | 125/138 [00:24<00:02,  4.59it/s]

Batch Prediction:  91%|█████████▏| 126/138 [00:24<00:02,  4.87it/s]

Batch Prediction:  92%|█████████▏| 127/138 [00:25<00:02,  4.97it/s]

Batch Prediction:  93%|█████████▎| 128/138 [00:25<00:01,  5.16it/s]

Batch Prediction:  93%|█████████▎| 129/138 [00:25<00:01,  5.34it/s]

Batch Prediction:  94%|█████████▍| 130/138 [00:25<00:01,  5.44it/s]

Batch Prediction:  95%|█████████▍| 131/138 [00:25<00:01,  5.31it/s]

Batch Prediction:  96%|█████████▌| 132/138 [00:26<00:01,  5.31it/s]

Batch Prediction:  96%|█████████▋| 133/138 [00:26<00:01,  4.23it/s]

Batch Prediction:  97%|█████████▋| 134/138 [00:26<00:00,  4.35it/s]

Batch Prediction:  98%|█████████▊| 135/138 [00:26<00:00,  4.55it/s]

Batch Prediction:  99%|█████████▊| 136/138 [00:26<00:00,  4.71it/s]

Batch Prediction:  99%|█████████▉| 137/138 [00:27<00:00,  4.89it/s]

Batch Prediction: 100%|██████████| 138/138 [00:27<00:00,  5.03it/s]

Batch Prediction: 100%|██████████| 138/138 [00:27<00:00,  5.05it/s]

 50%|█████     | 2/4 [00:56<00:55, 27.89s/it]

Batch Prediction:   0%|          | 0/138 [00:00<?, ?it/s]

Batch Prediction:   1%|          | 1/138 [00:00<00:22,  6.09it/s]

Batch Prediction:   1%|▏         | 2/138 [00:00<00:22,  5.98it/s]

Batch Prediction:   2%|▏         | 3/138 [00:00<00:30,  4.36it/s]

Batch Prediction:   3%|▎         | 4/138 [00:00<00:27,  4.81it/s]

Batch Prediction:   4%|▎         | 5/138 [00:01<00:27,  4.88it/s]

Batch Prediction:   4%|▍         | 6/138 [00:01<00:25,  5.17it/s]

Batch Prediction:   5%|▌         | 7/138 [00:01<00:24,  5.38it/s]

Batch Prediction:   6%|▌         | 8/138 [00:01<00:23,  5.49it/s]

Batch Prediction:   7%|▋         | 9/138 [00:01<00:23,  5.58it/s]

Batch Prediction:   7%|▋         | 10/138 [00:02<00:28,  4.54it/s]

Batch Prediction:   8%|▊         | 11/138 [00:02<00:25,  4.89it/s]

Batch Prediction:   9%|▊         | 12/138 [00:02<00:24,  5.12it/s]

Batch Prediction:   9%|▉         | 13/138 [00:02<00:23,  5.30it/s]

Batch Prediction:  10%|█         | 14/138 [00:02<00:23,  5.33it/s]

Batch Prediction:  11%|█         | 15/138 [00:02<00:22,  5.39it/s]

Batch Prediction:  12%|█▏        | 16/138 [00:03<00:22,  5.43it/s]

Batch Prediction:  12%|█▏        | 17/138 [00:03<00:22,  5.39it/s]

Batch Prediction:  13%|█▎        | 18/138 [00:03<00:26,  4.53it/s]

Batch Prediction:  14%|█▍        | 19/138 [00:03<00:24,  4.79it/s]

Batch Prediction:  14%|█▍        | 20/138 [00:03<00:24,  4.91it/s]

Batch Prediction:  15%|█▌        | 21/138 [00:04<00:22,  5.15it/s]

Batch Prediction:  16%|█▌        | 22/138 [00:04<00:21,  5.32it/s]

Batch Prediction:  17%|█▋        | 23/138 [00:04<00:21,  5.41it/s]

Batch Prediction:  17%|█▋        | 24/138 [00:04<00:20,  5.44it/s]

Batch Prediction:  18%|█▊        | 25/138 [00:04<00:21,  5.29it/s]

Batch Prediction:  19%|█▉        | 26/138 [00:05<00:25,  4.41it/s]

Batch Prediction:  20%|█▉        | 27/138 [00:05<00:24,  4.51it/s]

Batch Prediction:  20%|██        | 28/138 [00:05<00:23,  4.65it/s]

Batch Prediction:  21%|██        | 29/138 [00:05<00:23,  4.73it/s]

Batch Prediction:  22%|██▏       | 30/138 [00:05<00:22,  4.85it/s]

Batch Prediction:  22%|██▏       | 31/138 [00:06<00:20,  5.13it/s]

Batch Prediction:  23%|██▎       | 32/138 [00:06<00:20,  5.29it/s]

Batch Prediction:  24%|██▍       | 33/138 [00:06<00:20,  5.11it/s]

Batch Prediction:  25%|██▍       | 34/138 [00:06<00:22,  4.59it/s]

Batch Prediction:  25%|██▌       | 35/138 [00:06<00:21,  4.79it/s]

Batch Prediction:  26%|██▌       | 36/138 [00:07<00:21,  4.79it/s]

Batch Prediction:  27%|██▋       | 37/138 [00:07<00:20,  4.92it/s]

Batch Prediction:  28%|██▊       | 38/138 [00:07<00:19,  5.20it/s]

Batch Prediction:  28%|██▊       | 39/138 [00:07<00:19,  5.21it/s]

Batch Prediction:  29%|██▉       | 40/138 [00:07<00:18,  5.30it/s]

Batch Prediction:  30%|██▉       | 41/138 [00:08<00:18,  5.35it/s]

Batch Prediction:  30%|███       | 42/138 [00:08<00:20,  4.71it/s]

Batch Prediction:  31%|███       | 43/138 [00:08<00:18,  5.01it/s]

Batch Prediction:  32%|███▏      | 44/138 [00:08<00:18,  5.03it/s]

Batch Prediction:  33%|███▎      | 45/138 [00:08<00:18,  5.06it/s]

Batch Prediction:  33%|███▎      | 46/138 [00:09<00:17,  5.20it/s]

Batch Prediction:  34%|███▍      | 47/138 [00:09<00:16,  5.40it/s]

Batch Prediction:  35%|███▍      | 48/138 [00:09<00:16,  5.50it/s]

Batch Prediction:  36%|███▌      | 49/138 [00:09<00:16,  5.54it/s]

Batch Prediction:  36%|███▌      | 50/138 [00:09<00:18,  4.73it/s]

Batch Prediction:  37%|███▋      | 51/138 [00:10<00:17,  4.85it/s]

Batch Prediction:  38%|███▊      | 52/138 [00:10<00:16,  5.06it/s]

Batch Prediction:  38%|███▊      | 53/138 [00:10<00:16,  5.21it/s]

Batch Prediction:  39%|███▉      | 54/138 [00:10<00:15,  5.40it/s]

Batch Prediction:  40%|███▉      | 55/138 [00:10<00:15,  5.51it/s]

Batch Prediction:  41%|████      | 56/138 [00:11<00:15,  5.31it/s]

Batch Prediction:  41%|████▏     | 57/138 [00:11<00:18,  4.40it/s]

Batch Prediction:  42%|████▏     | 58/138 [00:11<00:17,  4.67it/s]

Batch Prediction:  43%|████▎     | 59/138 [00:11<00:16,  4.84it/s]

Batch Prediction:  43%|████▎     | 60/138 [00:11<00:16,  4.86it/s]

Batch Prediction:  44%|████▍     | 61/138 [00:12<00:15,  5.06it/s]

Batch Prediction:  45%|████▍     | 62/138 [00:12<00:14,  5.21it/s]

Batch Prediction:  46%|████▌     | 63/138 [00:12<00:13,  5.41it/s]

Batch Prediction:  46%|████▋     | 64/138 [00:12<00:13,  5.51it/s]

Batch Prediction:  47%|████▋     | 65/138 [00:12<00:15,  4.63it/s]

Batch Prediction:  48%|████▊     | 66/138 [00:13<00:14,  4.93it/s]

Batch Prediction:  49%|████▊     | 67/138 [00:13<00:13,  5.18it/s]

Batch Prediction:  49%|████▉     | 68/138 [00:13<00:13,  5.35it/s]

Batch Prediction:  50%|█████     | 69/138 [00:13<00:12,  5.49it/s]

Batch Prediction:  51%|█████     | 70/138 [00:13<00:12,  5.37it/s]

Batch Prediction:  51%|█████▏    | 71/138 [00:13<00:12,  5.30it/s]

Batch Prediction:  52%|█████▏    | 72/138 [00:14<00:12,  5.23it/s]

Batch Prediction:  53%|█████▎    | 73/138 [00:14<00:14,  4.49it/s]

Batch Prediction:  54%|█████▎    | 74/138 [00:14<00:13,  4.79it/s]

Batch Prediction:  54%|█████▍    | 75/138 [00:14<00:12,  5.06it/s]

Batch Prediction:  55%|█████▌    | 76/138 [00:14<00:11,  5.28it/s]

Batch Prediction:  56%|█████▌    | 77/138 [00:15<00:11,  5.43it/s]

Batch Prediction:  57%|█████▋    | 78/138 [00:15<00:11,  5.15it/s]

Batch Prediction:  57%|█████▋    | 79/138 [00:15<00:11,  5.13it/s]

Batch Prediction:  58%|█████▊    | 80/138 [00:15<00:11,  5.15it/s]

Batch Prediction:  59%|█████▊    | 81/138 [00:16<00:12,  4.40it/s]

Batch Prediction:  59%|█████▉    | 82/138 [00:16<00:11,  4.74it/s]

Batch Prediction:  60%|██████    | 83/138 [00:16<00:11,  4.95it/s]

Batch Prediction:  61%|██████    | 84/138 [00:16<00:10,  4.98it/s]

Batch Prediction:  62%|██████▏   | 85/138 [00:16<00:10,  5.15it/s]

Batch Prediction:  62%|██████▏   | 86/138 [00:16<00:09,  5.22it/s]

Batch Prediction:  63%|██████▎   | 87/138 [00:17<00:09,  5.30it/s]

Batch Prediction:  64%|██████▍   | 88/138 [00:17<00:09,  5.14it/s]

Batch Prediction:  64%|██████▍   | 89/138 [00:17<00:11,  4.44it/s]

Batch Prediction:  65%|██████▌   | 90/138 [00:17<00:10,  4.78it/s]

Batch Prediction:  66%|██████▌   | 91/138 [00:18<00:09,  4.92it/s]

Batch Prediction:  67%|██████▋   | 92/138 [00:18<00:09,  4.98it/s]

Batch Prediction:  67%|██████▋   | 93/138 [00:18<00:08,  5.07it/s]

Batch Prediction:  68%|██████▊   | 94/138 [00:18<00:08,  5.26it/s]

Batch Prediction:  69%|██████▉   | 95/138 [00:18<00:08,  5.37it/s]

Batch Prediction:  70%|██████▉   | 96/138 [00:19<00:09,  4.58it/s]

Batch Prediction:  70%|███████   | 97/138 [00:19<00:08,  4.89it/s]

Batch Prediction:  71%|███████   | 98/138 [00:19<00:07,  5.17it/s]

Batch Prediction:  72%|███████▏  | 99/138 [00:19<00:07,  5.35it/s]

Batch Prediction:  72%|███████▏  | 100/138 [00:19<00:06,  5.44it/s]

Batch Prediction:  73%|███████▎  | 101/138 [00:19<00:06,  5.41it/s]

Batch Prediction:  74%|███████▍  | 102/138 [00:20<00:06,  5.53it/s]

Batch Prediction:  75%|███████▍  | 103/138 [00:20<00:06,  5.64it/s]

Batch Prediction:  75%|███████▌  | 104/138 [00:20<00:07,  4.73it/s]

Batch Prediction:  76%|███████▌  | 105/138 [00:20<00:06,  5.02it/s]

Batch Prediction:  77%|███████▋  | 106/138 [00:20<00:06,  5.23it/s]

Batch Prediction:  78%|███████▊  | 107/138 [00:21<00:05,  5.44it/s]

Batch Prediction:  78%|███████▊  | 108/138 [00:21<00:05,  5.33it/s]

Batch Prediction:  79%|███████▉  | 109/138 [00:21<00:05,  5.17it/s]

Batch Prediction:  80%|███████▉  | 110/138 [00:21<00:05,  5.14it/s]

Batch Prediction:  80%|████████  | 111/138 [00:21<00:05,  5.12it/s]

Batch Prediction:  81%|████████  | 112/138 [00:22<00:06,  4.32it/s]

Batch Prediction:  82%|████████▏ | 113/138 [00:22<00:05,  4.63it/s]

Batch Prediction:  83%|████████▎ | 114/138 [00:22<00:04,  4.92it/s]

Batch Prediction:  83%|████████▎ | 115/138 [00:22<00:04,  4.95it/s]

Batch Prediction:  84%|████████▍ | 116/138 [00:22<00:04,  4.93it/s]

Batch Prediction:  85%|████████▍ | 117/138 [00:23<00:04,  4.91it/s]

Batch Prediction:  86%|████████▌ | 118/138 [00:23<00:04,  4.98it/s]

Batch Prediction:  86%|████████▌ | 119/138 [00:23<00:03,  5.10it/s]

Batch Prediction:  87%|████████▋ | 120/138 [00:23<00:04,  4.25it/s]

Batch Prediction:  88%|████████▊ | 121/138 [00:24<00:03,  4.48it/s]

Batch Prediction:  88%|████████▊ | 122/138 [00:24<00:03,  4.82it/s]

Batch Prediction:  89%|████████▉ | 123/138 [00:24<00:02,  5.07it/s]

Batch Prediction:  90%|████████▉ | 124/138 [00:24<00:02,  5.12it/s]

Batch Prediction:  91%|█████████ | 125/138 [00:24<00:02,  5.11it/s]

Batch Prediction:  91%|█████████▏| 126/138 [00:24<00:02,  5.08it/s]

Batch Prediction:  92%|█████████▏| 127/138 [00:25<00:02,  5.26it/s]

Batch Prediction:  93%|█████████▎| 128/138 [00:25<00:02,  4.54it/s]

Batch Prediction:  93%|█████████▎| 129/138 [00:25<00:01,  4.87it/s]

Batch Prediction:  94%|█████████▍| 130/138 [00:25<00:01,  5.13it/s]

Batch Prediction:  95%|█████████▍| 131/138 [00:25<00:01,  5.31it/s]

Batch Prediction:  96%|█████████▌| 132/138 [00:26<00:01,  5.46it/s]

Batch Prediction:  96%|█████████▋| 133/138 [00:26<00:00,  5.55it/s]

Batch Prediction:  97%|█████████▋| 134/138 [00:26<00:00,  5.59it/s]

Batch Prediction:  98%|█████████▊| 135/138 [00:26<00:00,  4.68it/s]

Batch Prediction:  99%|█████████▊| 136/138 [00:26<00:00,  4.94it/s]

Batch Prediction:  99%|█████████▉| 137/138 [00:27<00:00,  5.19it/s]

Batch Prediction: 100%|██████████| 138/138 [00:27<00:00,  5.42it/s]

Batch Prediction: 100%|██████████| 138/138 [00:27<00:00,  5.05it/s]

 75%|███████▌  | 3/4 [01:23<00:27, 27.64s/it]

Batch Prediction:   0%|          | 0/138 [00:00<?, ?it/s]

Batch Prediction:   1%|          | 1/138 [00:00<00:20,  6.70it/s]

Batch Prediction:   1%|▏         | 2/138 [00:00<00:21,  6.30it/s]

Batch Prediction:   2%|▏         | 3/138 [00:00<00:21,  6.25it/s]

Batch Prediction:   3%|▎         | 4/138 [00:00<00:21,  6.22it/s]

Batch Prediction:   4%|▎         | 5/138 [00:00<00:25,  5.16it/s]

Batch Prediction:   4%|▍         | 6/138 [00:01<00:24,  5.47it/s]

Batch Prediction:   5%|▌         | 7/138 [00:01<00:25,  5.18it/s]

Batch Prediction:   6%|▌         | 8/138 [00:01<00:26,  4.97it/s]

Batch Prediction:   7%|▋         | 9/138 [00:01<00:25,  5.00it/s]

Batch Prediction:   7%|▋         | 10/138 [00:01<00:25,  5.04it/s]

Batch Prediction:   8%|▊         | 11/138 [00:02<00:23,  5.29it/s]

Batch Prediction:   9%|▊         | 12/138 [00:02<00:22,  5.50it/s]

Batch Prediction:   9%|▉         | 13/138 [00:02<00:27,  4.62it/s]

Batch Prediction:  10%|█         | 14/138 [00:02<00:27,  4.51it/s]

Batch Prediction:  11%|█         | 15/138 [00:02<00:25,  4.78it/s]

Batch Prediction:  12%|█▏        | 16/138 [00:03<00:24,  4.91it/s]

Batch Prediction:  12%|█▏        | 17/138 [00:03<00:23,  5.20it/s]

Batch Prediction:  13%|█▎        | 18/138 [00:03<00:22,  5.24it/s]

Batch Prediction:  14%|█▍        | 19/138 [00:03<00:22,  5.30it/s]

Batch Prediction:  14%|█▍        | 20/138 [00:03<00:22,  5.15it/s]

Batch Prediction:  15%|█▌        | 21/138 [00:04<00:25,  4.64it/s]

Batch Prediction:  16%|█▌        | 22/138 [00:04<00:23,  4.99it/s]

Batch Prediction:  17%|█▋        | 23/138 [00:04<00:21,  5.28it/s]

Batch Prediction:  17%|█▋        | 24/138 [00:04<00:21,  5.39it/s]

Batch Prediction:  18%|█▊        | 25/138 [00:04<00:20,  5.61it/s]

Batch Prediction:  19%|█▉        | 26/138 [00:04<00:19,  5.79it/s]

Batch Prediction:  20%|█▉        | 27/138 [00:05<00:18,  5.89it/s]

Batch Prediction:  20%|██        | 28/138 [00:05<00:21,  5.18it/s]

Batch Prediction:  21%|██        | 29/138 [00:05<00:19,  5.46it/s]

Batch Prediction:  22%|██▏       | 30/138 [00:05<00:19,  5.65it/s]

Batch Prediction:  22%|██▏       | 31/138 [00:05<00:18,  5.82it/s]

Batch Prediction:  23%|██▎       | 32/138 [00:06<00:17,  5.92it/s]

Batch Prediction:  24%|██▍       | 33/138 [00:06<00:17,  6.01it/s]

Batch Prediction:  25%|██▍       | 34/138 [00:06<00:17,  6.10it/s]

Batch Prediction:  25%|██▌       | 35/138 [00:06<00:17,  6.05it/s]

Batch Prediction:  26%|██▌       | 36/138 [00:06<00:19,  5.33it/s]

Batch Prediction:  27%|██▋       | 37/138 [00:06<00:18,  5.57it/s]

Batch Prediction:  28%|██▊       | 38/138 [00:07<00:17,  5.79it/s]

Batch Prediction:  28%|██▊       | 39/138 [00:07<00:16,  5.92it/s]

Batch Prediction:  29%|██▉       | 40/138 [00:07<00:16,  5.90it/s]

Batch Prediction:  30%|██▉       | 41/138 [00:07<00:16,  5.79it/s]

Batch Prediction:  30%|███       | 42/138 [00:07<00:16,  5.96it/s]

Batch Prediction:  31%|███       | 43/138 [00:07<00:15,  6.05it/s]

Batch Prediction:  32%|███▏      | 44/138 [00:08<00:18,  5.06it/s]

Batch Prediction:  33%|███▎      | 45/138 [00:08<00:17,  5.25it/s]

Batch Prediction:  33%|███▎      | 46/138 [00:08<00:18,  5.09it/s]

Batch Prediction:  34%|███▍      | 47/138 [00:08<00:17,  5.16it/s]

Batch Prediction:  35%|███▍      | 48/138 [00:08<00:17,  5.12it/s]

Batch Prediction:  36%|███▌      | 49/138 [00:09<00:17,  5.01it/s]

Batch Prediction:  36%|███▌      | 50/138 [00:09<00:17,  4.91it/s]

Batch Prediction:  37%|███▋      | 51/138 [00:09<00:17,  4.92it/s]

Batch Prediction:  38%|███▊      | 52/138 [00:09<00:18,  4.57it/s]

Batch Prediction:  38%|███▊      | 53/138 [00:09<00:17,  4.86it/s]

Batch Prediction:  39%|███▉      | 54/138 [00:10<00:17,  4.88it/s]

Batch Prediction:  40%|███▉      | 55/138 [00:10<00:17,  4.82it/s]

Batch Prediction:  41%|████      | 56/138 [00:10<00:16,  4.92it/s]

Batch Prediction:  41%|████▏     | 57/138 [00:10<00:15,  5.24it/s]

Batch Prediction:  42%|████▏     | 58/138 [00:10<00:14,  5.48it/s]

Batch Prediction:  43%|████▎     | 59/138 [00:11<00:15,  4.99it/s]

Batch Prediction:  43%|████▎     | 60/138 [00:11<00:14,  5.29it/s]

Batch Prediction:  44%|████▍     | 61/138 [00:11<00:13,  5.50it/s]

Batch Prediction:  45%|████▍     | 62/138 [00:11<00:13,  5.55it/s]

Batch Prediction:  46%|████▌     | 63/138 [00:11<00:13,  5.66it/s]

Batch Prediction:  46%|████▋     | 64/138 [00:11<00:12,  5.82it/s]

Batch Prediction:  47%|████▋     | 65/138 [00:12<00:12,  5.92it/s]

Batch Prediction:  48%|████▊     | 66/138 [00:12<00:12,  5.97it/s]

Batch Prediction:  49%|████▊     | 67/138 [00:12<00:14,  4.99it/s]

Batch Prediction:  49%|████▉     | 68/138 [00:12<00:13,  5.29it/s]

Batch Prediction:  50%|█████     | 69/138 [00:12<00:12,  5.52it/s]

Batch Prediction:  51%|█████     | 70/138 [00:13<00:11,  5.70it/s]

Batch Prediction:  51%|█████▏    | 71/138 [00:13<00:11,  5.82it/s]

Batch Prediction:  52%|█████▏    | 72/138 [00:13<00:11,  5.83it/s]

Batch Prediction:  53%|█████▎    | 73/138 [00:13<00:11,  5.83it/s]

Batch Prediction:  54%|█████▎    | 74/138 [00:13<00:10,  5.91it/s]

Batch Prediction:  54%|█████▍    | 75/138 [00:13<00:12,  5.25it/s]

Batch Prediction:  55%|█████▌    | 76/138 [00:14<00:11,  5.49it/s]

Batch Prediction:  56%|█████▌    | 77/138 [00:14<00:10,  5.70it/s]

Batch Prediction:  57%|█████▋    | 78/138 [00:14<00:10,  5.78it/s]

Batch Prediction:  57%|█████▋    | 79/138 [00:14<00:10,  5.87it/s]

Batch Prediction:  58%|█████▊    | 80/138 [00:14<00:10,  5.46it/s]

Batch Prediction:  59%|█████▊    | 81/138 [00:15<00:10,  5.58it/s]

Batch Prediction:  59%|█████▉    | 82/138 [00:15<00:09,  5.69it/s]

Batch Prediction:  60%|██████    | 83/138 [00:15<00:11,  4.92it/s]

Batch Prediction:  61%|██████    | 84/138 [00:15<00:11,  4.78it/s]

Batch Prediction:  62%|██████▏   | 85/138 [00:15<00:11,  4.71it/s]

Batch Prediction:  62%|██████▏   | 86/138 [00:16<00:11,  4.56it/s]

Batch Prediction:  63%|██████▎   | 87/138 [00:16<00:11,  4.58it/s]

Batch Prediction:  64%|██████▍   | 88/138 [00:16<00:10,  4.62it/s]

Batch Prediction:  64%|██████▍   | 89/138 [00:16<00:10,  4.72it/s]

Batch Prediction:  65%|██████▌   | 90/138 [00:16<00:09,  4.96it/s]

Batch Prediction:  66%|██████▌   | 91/138 [00:17<00:10,  4.63it/s]

Batch Prediction:  67%|██████▋   | 92/138 [00:17<00:09,  4.76it/s]

Batch Prediction:  67%|██████▋   | 93/138 [00:17<00:09,  4.79it/s]

Batch Prediction:  68%|██████▊   | 94/138 [00:17<00:08,  4.97it/s]

Batch Prediction:  69%|██████▉   | 95/138 [00:17<00:08,  5.09it/s]

Batch Prediction:  70%|██████▉   | 96/138 [00:18<00:07,  5.36it/s]

Batch Prediction:  70%|███████   | 97/138 [00:18<00:07,  5.57it/s]

Batch Prediction:  71%|███████   | 98/138 [00:18<00:06,  5.73it/s]

Batch Prediction:  72%|███████▏  | 99/138 [00:18<00:07,  5.12it/s]

Batch Prediction:  72%|███████▏  | 100/138 [00:18<00:07,  5.38it/s]

Batch Prediction:  73%|███████▎  | 101/138 [00:19<00:06,  5.57it/s]

Batch Prediction:  74%|███████▍  | 102/138 [00:19<00:06,  5.73it/s]

Batch Prediction:  75%|███████▍  | 103/138 [00:19<00:06,  5.76it/s]

Batch Prediction:  75%|███████▌  | 104/138 [00:19<00:05,  5.88it/s]

Batch Prediction:  76%|███████▌  | 105/138 [00:19<00:05,  5.96it/s]

Batch Prediction:  77%|███████▋  | 106/138 [00:19<00:05,  6.02it/s]

Batch Prediction:  78%|███████▊  | 107/138 [00:20<00:05,  5.33it/s]

Batch Prediction:  78%|███████▊  | 108/138 [00:20<00:05,  5.56it/s]

Batch Prediction:  79%|███████▉  | 109/138 [00:20<00:05,  5.67it/s]

Batch Prediction:  80%|███████▉  | 110/138 [00:20<00:04,  5.62it/s]

Batch Prediction:  80%|████████  | 111/138 [00:20<00:04,  5.79it/s]

Batch Prediction:  81%|████████  | 112/138 [00:20<00:04,  5.89it/s]

Batch Prediction:  82%|████████▏ | 113/138 [00:21<00:04,  5.92it/s]

Batch Prediction:  83%|████████▎ | 114/138 [00:21<00:04,  5.87it/s]

Batch Prediction:  83%|████████▎ | 115/138 [00:21<00:04,  5.19it/s]

Batch Prediction:  84%|████████▍ | 116/138 [00:21<00:04,  5.09it/s]

Batch Prediction:  85%|████████▍ | 117/138 [00:21<00:04,  5.13it/s]

Batch Prediction:  86%|████████▌ | 118/138 [00:22<00:03,  5.16it/s]

Batch Prediction:  86%|████████▌ | 119/138 [00:22<00:03,  5.01it/s]

Batch Prediction:  87%|████████▋ | 120/138 [00:22<00:03,  4.92it/s]

Batch Prediction:  88%|████████▊ | 121/138 [00:22<00:03,  4.71it/s]

Batch Prediction:  88%|████████▊ | 122/138 [00:22<00:03,  4.72it/s]

Batch Prediction:  89%|████████▉ | 123/138 [00:23<00:03,  4.17it/s]

Batch Prediction:  90%|████████▉ | 124/138 [00:23<00:03,  4.33it/s]

Batch Prediction:  91%|█████████ | 125/138 [00:23<00:02,  4.52it/s]

Batch Prediction:  91%|█████████▏| 126/138 [00:23<00:02,  4.67it/s]

Batch Prediction:  92%|█████████▏| 127/138 [00:24<00:02,  5.01it/s]

Batch Prediction:  93%|█████████▎| 128/138 [00:24<00:01,  5.30it/s]

Batch Prediction:  93%|█████████▎| 129/138 [00:24<00:01,  5.35it/s]

Batch Prediction:  94%|█████████▍| 130/138 [00:24<00:01,  5.54it/s]

Batch Prediction:  95%|█████████▍| 131/138 [00:24<00:01,  4.84it/s]

Batch Prediction:  96%|█████████▌| 132/138 [00:25<00:01,  4.84it/s]

Batch Prediction:  96%|█████████▋| 133/138 [00:25<00:00,  5.12it/s]

Batch Prediction:  97%|█████████▋| 134/138 [00:25<00:00,  5.12it/s]

Batch Prediction:  98%|█████████▊| 135/138 [00:25<00:00,  5.35it/s]

Batch Prediction:  99%|█████████▊| 136/138 [00:25<00:00,  5.56it/s]

Batch Prediction:  99%|█████████▉| 137/138 [00:25<00:00,  5.74it/s]

Batch Prediction: 100%|██████████| 138/138 [00:26<00:00,  5.93it/s]

Batch Prediction: 100%|██████████| 138/138 [00:26<00:00,  5.30it/s]

100%|██████████| 4/4 [01:49<00:00, 27.02s/it]

100%|██████████| 4/4 [01:49<00:00, 27.35s/it]

[08/25/25 05:07:24] INFO     2025-08-25 05:07:24,475 [INFO] pred.shape: (6897776,)                  ]8;id=794123;file:///usr/local/lib/python3.10/site-packages/icecream/icecream.py\icecream.py]8;;\:]8;id=72804;file:///usr/local/lib/python3.10/site-packages/icecream/icecream.py#185\185]8;;\

                    INFO     2025-08-25 05:07:24,610 [INFO] pred.shape: (6897776,)                  ]8;id=173368;file:///usr/local/lib/python3.10/site-packages/icecream/icecream.py\icecream.py]8;;\:]8;id=554221;file:///usr/local/lib/python3.10/site-packages/icecream/icecream.py#185\185]8;;\

                    INFO     2025-08-25 05:07:24,658 [INFO] pred.shape: (6897776,)                  ]8;id=38415;file:///usr/local/lib/python3.10/site-packages/icecream/icecream.py\icecream.py]8;;\:]8;id=461854;file:///usr/local/lib/python3.10/site-packages/icecream/icecream.py#185\185]8;;\

                    INFO     2025-08-25 05:07:24,707 [INFO] pred.shape: (6897776,)                  ]8;id=71184;file:///usr/local/lib/python3.10/site-packages/icecream/icecream.py\icecream.py]8;;\:]8;id=429712;file:///usr/local/lib/python3.10/site-packages/icecream/icecream.py#185\185]8;;\

array([0.4094596 , 0.35326123, 0.02461513, ..., 0.07985739, 0.51260316,
       0.05522128], dtype=float32)

In [47]:
def probs2rank(df):
  df = df.with_columns(
      pl.col('pred').rank(method='ordinal',
                          descending=True).over('ranker_id').cast(
                              pl.Int32).alias('selected')).select(
                                  ['Id', 'ranker_id', 'selected'])
  return df

In [48]:
df_test = df_test.with_columns(
    pl.Series("pred", pred)
)

In [49]:
sub = probs2rank(df_test)
sub

shape: (6_897_776, 3)
┌──────────┬─────────────────────────────────┬──────────┐
│ Id       ┆ ranker_id                       ┆ selected │
│ ---      ┆ ---                             ┆ ---      │
│ i64      ┆ str                             ┆ i32      │
╞══════════╪═════════════════════════════════╪══════════╡
│ 18144679 ┆ c9373e5f772e43d593dd6ad2fa90f6… ┆ 6        │
│ 18144680 ┆ c9373e5f772e43d593dd6ad2fa90f6… ┆ 14       │
│ 18144681 ┆ c9373e5f772e43d593dd6ad2fa90f6… ┆ 225      │
│ 18144682 ┆ c9373e5f772e43d593dd6ad2fa90f6… ┆ 76       │
│ 18144683 ┆ c9373e5f772e43d593dd6ad2fa90f6… ┆ 80       │
│ …        ┆ …                               ┆ …        │
│ 25043143 ┆ c5622e0de0594bde95a4dd8c1fcff7… ┆ 11       │
│ 25043144 ┆ c5622e0de0594bde95a4dd8c1fcff7… ┆ 1        │
│ 25043145 ┆ c5622e0de0594bde95a4dd8c1fcff7… ┆ 9        │
│ 25043146 ┆ c5622e0de0594bde95a4dd8c1fcff7… ┆ 4        │
│ 25043147 ┆ c5622e0de0594bde95a4dd8c1fcff7… ┆ 12       │
└──────────┴─────────────────────────────────┴──────────┘

In [50]:
FLAGS.out_dir

'../working/fast0-online1-use_ext1-history_avg1'

# Dump result of best single model to single.parquet

In [51]:
df_test = df_test.with_columns(
    pl.Series("pred", preds[0])
)
sub_single = probs2rank(df_test)
sub_single

shape: (6_897_776, 3)
┌──────────┬─────────────────────────────────┬──────────┐
│ Id       ┆ ranker_id                       ┆ selected │
│ ---      ┆ ---                             ┆ ---      │
│ i64      ┆ str                             ┆ i32      │
╞══════════╪═════════════════════════════════╪══════════╡
│ 18144679 ┆ c9373e5f772e43d593dd6ad2fa90f6… ┆ 4        │
│ 18144680 ┆ c9373e5f772e43d593dd6ad2fa90f6… ┆ 20       │
│ 18144681 ┆ c9373e5f772e43d593dd6ad2fa90f6… ┆ 240      │
│ 18144682 ┆ c9373e5f772e43d593dd6ad2fa90f6… ┆ 78       │
│ 18144683 ┆ c9373e5f772e43d593dd6ad2fa90f6… ┆ 71       │
│ …        ┆ …                               ┆ …        │
│ 25043143 ┆ c5622e0de0594bde95a4dd8c1fcff7… ┆ 9        │
│ 25043144 ┆ c5622e0de0594bde95a4dd8c1fcff7… ┆ 2        │
│ 25043145 ┆ c5622e0de0594bde95a4dd8c1fcff7… ┆ 11       │
│ 25043146 ┆ c5622e0de0594bde95a4dd8c1fcff7… ┆ 3        │
│ 25043147 ┆ c5622e0de0594bde95a4dd8c1fcff7… ┆ 12       │
└──────────┴─────────────────────────────────┴──────────┘

In [52]:
sub_single.write_parquet(f'{FLAGS.out_dir}/best_single.parquet')
sub.write_csv(f'submission.csv')